### ISSUE TITLE
Wake-on-LAN has a very long delay comparing to moonlight-android in the same local network

### ISSUE THREAD

**Issue by RadarNyan** [moonlight-stream/moonlight-qt#1037]
When I try to wake my desktop from my laptop using Moonlight-Qt for Windows, it takes up to 15 seconds before I can hear the desktop turn on (not booting to Windows, just powering up: fan spinning and whatnot).

Both the desktop and laptop are connected to the same router with Ethernet cables. If I try to wake the desktop from my phone using moonlight-android or any other app, I can hear the desktop wake up as soon as I tap on the button.

The desktop is configured to wake only with magic packets, and this behavior is independent of how long the desktop has been sleeping. Even if I try to wake it right away after putting it to sleep for a few seconds, there's still a very notable delay in moonlight-qt compared to instant wake-up with moonlight-android.

**Comment by cgutman** [comment]
Can you collect a Wireshark capture of the Wake-on-LAN traffic? Also please upload the Moonlight.log file after attempting to wake your PC.

**Comment by RadarNyan** [comment]
I've checked the log, it seems that Moonlight-qt sends WoL packet to the server IP address first:
> Qt Info: Sent WoL packet to [SERVER] via 192.168.1.100:9
Then after a few seconds it sends WoL packets to many other IP addresses, including the broadcast:
> Qt Info: Sent WoL packet to [SERVER] via 192.168.1.255:9
Then my desktop wakes up.

From my limited internet search, it seems using the broadcast IP is the appropriate way. Why does Moonlight-qt spam a bunch of WoL packets to all kinds of unrelated IP addresses?

BTW, is there a way to disable logging to disk? Writing a new log file to disk every time the program launches seems excessive. IMO, it should only be exported when needed.

**Comment by cgutman** [comment]
> From my limited internet search, it seems using the broadcast IP is the appropriate way. Why does Moonlight-qt spam WoL packets to all kinds of unrelated IP addresses?

They're not unrelated addresses. They're addresses that are associated with your host (either manually via the Add PC dialog or automatically via STUN or mDNS) and the IPv4 subnet broadcast and IPv6 all-nodes multicast addresses for all network interfaces.

The issue is that we're calling `QHostInfo::fromName()` on these IP addresses. Rather than just returning the address, it performs a reverse lookup which leads to delays waiting for a response. Easy fix.

> BTW, is there a way to disable logging to disk? Writing a new log file to disk every time the program launches seems excessive. IMO, it should only be exported when needed.

Not currently on Windows. We cap the size of each log and Storage Sense cleans them up after 30 days, so it doesn't end up being a huge space hog. Keeping multiple logs is deliberate (otherwise it would be easy for someone to accidentally overwrite an important log just by starting Moonlight again), but we could clean up old ones on startup.

**Comment by RadarNyan** [comment]
By "unrelated IP addresses", I'm referring to those non-broadcast IP addresses.

WoL packets should be and almost always are sent via broadcast (quote from [dd-wrt wiki](https://wiki.dd-wrt.com/wiki/index.php/WOL)), not to every single address associated with the host. If a machine is not turned on (sleeping), it doesn't have an IP address. The way moonlight-qt first attempts to send WoL packets to the (last seen?) LAN IP address for my desktop (192.168.1.100) is incorrect and never gonna work.

**Comment by cgutman** [comment]
>  If a machine is not turned on (sleeping), it doesn't have an IP address.

It's not that simple. Connected Standby hosts do maintain IP leases and respond to ARP requests while sleeping. The unicast traffic will reach and wake them. It's also possible that the unicast address we see is actually a NAT device, which will not forward broadcast traffic to host behind it but will forward unicast traffic.

Likewise, there are relays that can be run to support Wake-on-WAN (and some routers can even use UPnP to redirect to the subnet broadcast address), so unicast to the last WAN address can be useful too.

Ultimately, we're talking about a handful of ~150 byte packets which are dwarfed by less than one second of actual streaming. Network configurations can be incredibly complex, so I'd much rather send some that are not needed than break somebody's configuration because I over-optimized things.

**Comment by RadarNyan** [comment]
Knowing how many codes rely on behaviors of bugs that are now kept as features for backward compatibility, I perfectly understand your mindset of keeping the current behavior. After all, if it ain't broke don't fix it.

**Comment by makedir** [comment]
> The issue is that we're calling `QHostInfo::fromName()` on these IP addresses. Rather than just returning the address, it performs a reverse lookup which leads to delays waiting for a response. Easy fix.

So why wasnt it fixed then so far? Also instead of name resolv why is there no option in the Windows Moonlight client to add manually ip adresses?

**Comment by cgutman** [comment]
It is fixed in nightly by the commit associated with this issue. The fix has not been released in an official client yet, but it will be included in v5.0.0.

You can edit the manually stored IP address or hostname for any PC by simply adding the PC again via the new IP address or hostname.

The client polls for updates to PC state in the background every few seconds when the Moonlight window is focused, so a refresh button is not necessary.

**Comment by makedir** [comment]
> You can edit the manually stored IP address or hostname for any PC by simply adding the PC again via the new IP address or hostname.

Annoying. Add an edit button.


> The client polls for updates to PC state in the background every few seconds when the Moonlight window is focused, so a refresh button is not necessary.

Annoying. The refresh is too slow. Add a refresh button.

**Comment by makedir** [comment]
@cgutman when will the next release of Moonlight be? It is now almost a year with no update. I dont want to install a debug version.
