### ISSUE TITLE
Image Upscaling (FSR/DLSS/XESS)

### ISSUE THREAD

**Issue by haroonsyed** [moonlight-stream/moonlight-qt#1061]
Hello all, 
I was wondering if anyone is already working on an implementation, or if I should give it a go. 

I have no idea if the added latency/overhead even makes this viable, but I think it would be great for attaining a higher resolution at a given bandwidth.

I understand that the client could turn some of these technologies on for their desktop, but I feel an integrated version is less invasive.

**Comment by oneoctilliondollars** [comment]
DLSS/FSR2.0+/XeSS need access to game motion vectors and other data in order to properly upscale. You are looking for scaling technologies such as NiS FSR1 and any other suitable scalars for video. Other programs such as lossless scaling and Magpie can be used in this capacity as long as moonlight is ran in a window and you allow tearing in either app to not add unnecessary latency. Integrating this into moonlight itself sounds interesting but probably not needed as the use case is really quite niche but I wouldn't try to stop you :)

In a perfect world you would have a framework for dropping in your own more obscure choice of algorithms like FSRCNNX or heavier GAN based scalers like you can in mpv. I am not sure how moonlight presents video but those filtering choices could be useful or at least better frame pacing options as in my experience those are quite lacking too. Anyway I hope I managed to answer your question and point you in the right direction.

Also don't overestimate the overhead for most of these, they are really quite cheap up until using GANs, then we are talking about 4090s not being able to go above 24fps, otherwise 16ms is plenty of time to render.

I can leave some screenshots showing what you can expect from current technologies but they really won't blow your socks off, not even close to temporal scalers.

**Comment by oneoctilliondollars** [comment]
After a bit more reading DLSS 1.0 could also fit under this umbrella, at least the upscale stage as it is also a cheap GAN but even those have moved far forward since 2019.

**Comment by cgutman** [comment]
Another complication is the API support. I believe FSR, DLSS, and XeSS also only support D3D12 and Vulkan, but we (mainly) use D3D11 and OpenGL(ES) for rendering. D3D12 and Vulkan video decoding are very new and aren't supported by a lot of hardware, software, and drivers out there yet. I don't think Khronos has even finalized the Vulkan AV1 decoding extension yet.

For FFmpeg, which we use for decoding, Vulkan Video will be supported starting in FFmpeg 6.1 (which isn't yet released) and I've seen D3D12 decoding patches floating around on the mailing list but nothing actually merged yet.

**Comment by haroonsyed** [comment]
Thanks so much for the insights!

In that case I probably won't try to pursue this, but my understanding is that currently the problems are:

1. Spatial Upscaling (since temporal requires per-game support or some fancy driver level stuff) -> Artifacts
2. Significant API differences
3. The tech isn't mature anyway and will probably be more integratable/available/advanced in a couple years
