### ISSUE TITLE
No audio when joining a Discord voice channel on Mac OS

### ISSUE THREAD

**Issue by giejay** [moonlight-stream/moonlight-qt#1071]
**Describe the bug**
Im facing an issue with the audio when joining a discord channel using voice. Whenever Im connected with a (Bluetooth/2.4 ghz) headset to my Mac Air M2 and I join a voice discord channel, the audio stops. When I leave the channel, the audio comes back again. I can now sort of workaround it by using the dongle of my Sony Inzone H9 and then selecting the "Game" speaker and I think thats because its not marked as a Headphone by Mac OS. Anyone face this issue before? I saw that the IOS client did have the same issue: https://github.com/moonlight-stream/moonlight-ios/issues/437

**Steps to reproduce**
Connect to my Windows Sunshine server from my Macbook Air M2, play some audio, join a discord channel using voice on my Mac OS, audio stops in Moonlight. 

**Affected games**
All

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android? Not anymore apparently. 

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? All defaults

**Client PC details (please complete the following information)**
 - OS: Mac OS Ventura
 - Moonlight Version: Latest nightly

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
This issue is not present in the latest released version on Github. But the audio does become a lot worse when connecting to a Discord channel.

**Comment by cgutman** [comment]
Hmm, that's very strange. I suspect it's related to the device switching between A2DP for music/audio and HSP/HFP for voice. The latter have much reduced audio bitrate because they're designed for phone calls, not music or other general audio. 

We use SDL for audio output and I don't see many changes in the [macOS audio code in SDL](https://github.com/libsdl-org/SDL/commits/SDL2/src/audio/coreaudio/) between now and the what we shipped back in v4.3.1 in November 2022. Nothing there looks at a glance like it would cause the issue you're describing.

The only change on the Moonlight side was a buffer size increase in da1fcd49fc2069095f140c021f7455241cdef7ed. This was the last nightly build before the change went in, so you could try it and see if it restores the old behavior - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/47995562/job/uv0gk4sh8nm5vve4/artifacts

**Comment by giejay** [comment]
Thanks for the quick response, I tried that build and indeed, Im seeing the same behaviour as the november 2022 release. So I do have sound, but the quality is bad.

**Comment by mrjoshuak** [comment]
I have an issue that may be similar to this.  I have two clients running.  One on a MacBook Pro and one on a MacBook Air, I can get audio on one client but not the other.  It could be discord, because that was running on the MacBook Air, but quitting discord on that client did not restore audio. Still doing more testing, but there is some kind of inconsistant los of audio bug on Mac clients for sure.
