### ISSUE TITLE
Very slow stream, impossible to use, over internet, if I use Moonlight v 4.3.1 or newer, but quite perfect with 4.3.0

### ISSUE THREAD

**Issue by Info-BC** [moonlight-stream/moonlight-qt#1101]
Hello,

I use a sunshine server 0.20 on Windows 11 PC (Nvidia GTX1650) on a fiber internet connection (around 900Mb/s down and 300Mb/s up). I connect over internet from a Windows 11 client (AMD Radeon) on full desktop with Moonlight 4.3.0, runs really fine on 1080p 60fps 20Mb/s, quite flawlessly. If I update the client to 4.3.1 or 5.0.0, it's impossible to use, stream is very very slow and disconnect very often. I've seen the same on another Windows 10 client.

Any ideas on this problem?

Thanks,

**Comment by cgutman** [comment]
The only possibly relevant change for networking between v4.3.0 and v4.3.1 is https://github.com/moonlight-stream/moonlight-qt/commit/411998d4e39f11ce6d3d8fc60657b699b19d5dd1

Are you connecting over the Internet using a VPN?

Please post your `Moonlight.log` file from your `%TEMP%` directory (or the app directory for the portable version).

**Comment by massltoff** [comment]
Same issue here. 
Server: Windows Sunshine v0.22.0 
Client: Arch Linux, Moonlight 5.0.1 (tried AUR and flatpak)
1fps and then disconnect.

Moonlight 4.3.0 works perfectly.

I am not connected through a VPN but I have an inactive wireguard connection.

**Comment by cgutman** [comment]
@massltoff Can you describe your network topology a bit to help me better understand what's going on?

I'm not really sure why #1216 would change things because we already opt to use remote streaming mode (smaller packets) for non-RFC1918 IP addresses [here in moonlight-common-c](https://github.com/moonlight-stream/moonlight-common-c/blob/eb21561541874d9e9dbd7da26000c6dd55050748/src/PlatformSockets.c#L668-L693).

Are you hitting the [on-link case](https://github.com/moonlight-stream/moonlight-qt/pull/1216/files#diff-15e5cd8a70b20aaa51d4475fc32d24f219babe5dd434a2e92ad7878f4dfaf40dR437-R440) with your host's IP address?

**Comment by massltoff** [comment]
@cgutman Thanks for your feedback. 
My PC is connected to my dsl-router (fritzbox) via ethernet. I have a raspberry pi-hole (dnsmaq) running which also is registered as the DNS server.

I have entered an IP Address for the host PC (something like 162.56.112.181).

**I am indeed hitting on-link-case. I logged the variables:**
addr.prefixLength() = 24 
s.localAddress() = QHostAddress("192.168.178.24") 
addr.ip() = QHostAddress("192.168.178.24") 
addr.prefixLength() = 24

At this point aren't s.localAddress() and addr.ip() always equal because of [this condition](https://github.com/moonlight-stream/moonlight-qt/blob/89a628a0dde50264fd2170125588c15d8dd80a2c/app/backend/nvcomputer.cpp#L384) before?

**Comment by cgutman** [comment]
> At this point aren't s.localAddress() and addr.ip() always equal because of [this condition](https://github.com/moonlight-stream/moonlight-qt/blob/89a628a0dde50264fd2170125588c15d8dd80a2c/app/backend/nvcomputer.cpp#L384) before?

Yep, you are 100% correct. I was staring at that code (even found the commit that broke it months ago!) and didn't see the obvious bug. We should be checking the peer address, not our local address there.

**Comment by massltoff** [comment]
@cgutman I can confirm, with the latest commit it is working with MTU 1500. Thank your for taking care of this. Best regards.
