### ISSUE TITLE
Picture in Picture Bug when using Moonlight with RDP

### ISSUE THREAD

**Issue by Neflite** [moonlight-stream/moonlight-qt#1115]
I´m using Moonlight from my Laptop to make an RDP to my Gaming Rig. The resolution on all devices is 1080. Same is the setting within Moonlight.
But when i try to connect to my Gaming Rig, he always shows me some kind of "Picture in picture", which is totally confusing. The small picture is the real desktop.....the larger one is only a kind of "frozen background" from the moment when i connect.

Only when i start a real game, he switches to "real fullscreen" and everything works perfectly. If i turn of the game i have this "Picture in picture" - Bug again.

Pls see this picture below for better understand.

![image](https://github.com/moonlight-stream/moonlight-qt/assets/37070827/6bfaa01f-cb54-4765-b765-851471110197)

**Comment by cgutman** [comment]
This is a GeForce Experience bug that happens when your display scaling option in Nvidia Control Panel is set to "Display" rather than "GPU". Adjust the option shown below and that should fix it. You can also switch to [Sunshine](https://github.com/LizardByte/Sunshine) which doesn't have this bug when not using GPU scaling.

<img width="804" alt="Screenshot 2023-11-15 at 6 50 05 PM" src="https://github.com/moonlight-stream/moonlight-qt/assets/2695644/a29df3bf-d947-4356-a6cc-55c51bacf2e4">

**Comment by Neflite** [comment]
You`re my hero - that was the problem. Thanks!

**Comment by cotwitch** [comment]
This should be in README/FAQ 🤦‍♂️
