### ISSUE TITLE
Mouse Sensitivity option in client?

### ISSUE THREAD

**Issue by somerandomperson123** [moonlight-stream/moonlight-qt#116]
The PC I typically use to connect as the client uses both a lower DPI office mouse (no DPI adjustment) and is also lower resolution compared to the host PC.

Changing Windows sensitivity on the client PC doesn't seem to impact anything. Nor would any DPI/sensitivity adjustment be ideal client side as then this would negatively impact mouse control outside of moonlight. 

Changing DPI/sensitivity host side would also not be ideal as that would negatively impact mouse control when physically using the host PC. 

Just enabling mouse acceleration is not an ideal solution either as I'd prefer to keep existing muscle memory familiarity with respect to linear movement.

**Comment by euroclydon37** [comment]
On Mac, the mouse acceleration doesn't seem to do anything for trackpad. Haven't tested a physical mouse.

**Comment by cgutman** [comment]
The "mouse acceleration" toggle is more aptly named the "use client OS mouse ballistics" (i.e. disable raw input), but nobody would understand that in the UI.

Checking the checkbox means the mouse events sent to the host are affected by client PC pointer processing (mouse acceleration, sensitivity options, and others), rather than the raw input events that SDL games receive by default.

If you have mouse acceleration disabled on your client PC, you won't get mouse acceleration when you check the box either. Windows will still adjust the mouse motion events for the selected mouse sensitivity, which sounds like what you want.

**Comment by euroclydon37** [comment]
That makes total sense. But the behavior I saw was that the mouse moved slower than it normally does on either client or server. So they seem to be interacting in funky ways. It's probably server side because the mouse movement was very slow on iOS too. I'll take a look at my setup when I get the chance.

**Comment by JuniorJPDJ** [comment]
Could you please rename option to "raw mouse input" or something?
It's not nice to understand what it does after reading random issue...
It actually solves other problems, eg. jumpy touchpads on thinkpad

**Comment by cgutman** [comment]
I renamed the mouse acceleration toggle to "raw mouse input" as suggested. Thanks.

**Comment by neyz** [comment]
I want to reopen this one because no matter what i choose : "RAW input" or not, the client seems to apply the client's mouse acceleration inside the session.

Tested with Mac OS, moonlight client is latest version (can't seem to find in GUI the version number)

Tell me if i can do anything to help,

thanks !

**Comment by Silent-Hunter** [comment]
Where did this option go? I really need it, as my special ergonomic mouse is too slow, so I use an xinput command to make it faster. But Moonlight ignores this because it's bypassing X11's mouse settings.
