### ISSUE TITLE
Seemingly random crashes on Windows 10

### ISSUE THREAD

**Issue by Kevin43** [moonlight-stream/moonlight-qt#120]
**Describe the bug**
Occasionally. out of nowhere, your screen will go entirely black and the computer will no longer receive any input. This has started happening with the newest release, not before.

**Steps to reproduce**
Start Moonlight, use it for a bit, and wait.

**Screenshots**
Completely black. Even remote access software can't help, unresponsive.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Yes
- If so, which settings have been changed? Play audio on host PC, disabled auto find PC on local network, and disabled V-Sync
- Have not tested, but I will try putting it on windowed borderless. **edit: didn't work.**

**Client PC details (please complete the following information)**
 - OS: Windows 10 1709
 - Moonlight Version: 0.6.2

**Logs (please attach)**
[Moonlight-1540822354.log](https://github.com/moonlight-stream/moonlight-qt/files/2525902/Moonlight-1540822354.log)
[Moonlight-1540824450.log](https://github.com/moonlight-stream/moonlight-qt/files/2525903/Moonlight-1540824450.log)
I also have two dump files, as well.
[Moonlight-1540826510.zip](https://github.com/moonlight-stream/moonlight-qt/files/2525909/Moonlight-1540826510.zip)

**Comment by Kevin43** [comment]
Oh weird, that really shouldn't be happening. I've tried the older version before the newest one, which was proven to work before, but now it also results in a crash after some period of time. If you do give me that build, I can test it on Wednesday.

By the way, I am using the portable version.

**Comment by cgutman** [comment]
@Kevin43 here's a build of SDL2.dll. Please overwrite the copy in the 0.6.2 portable folder with this version, then run Moonlight. When you get a crash, upload the dump here.

[SDL2.zip](https://github.com/moonlight-stream/moonlight-qt/files/2532908/SDL2.zip)

**Comment by Kevin43** [comment]
[Moonlight-1540992627.zip](https://github.com/moonlight-stream/moonlight-qt/files/2534655/Moonlight-1540992627.zip)

Here you go.

**Comment by cgutman** [comment]
Thanks again. I submitted a patch to SDL which was approved, so it will be fixed for all games/apps using SDL in the next release.

I'll backport the fix to Moonlight when I integrate SDL 2.0.9.

**Comment by Kevin43** [comment]
Oh, thank you for the quick fix! Hopefully that's soon, then.

**Comment by Warboss777** [comment]
Hello, this is my first github comment and Im not sure it's in the right place.
However, I am using a 27" Dell s2719dgf monitor at 155/ 144hz displayport, and I downloaded moonlight to try it and then tried to force change the resolution of the display to match that of the phone I was playing on. 
And then the display went black and crashed.

The problem is every other day my display flickers black and a few seconds and then both my monitors freeze and the PC needs manual resetting. This has been going on for months.

I am not sure how to fix this or if moonlight fried my display forever. 
I have another display attached and that display does not have these issues. 
Please help if you know how.
