### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by Fuckingnameless** [moonlight-stream/moonlight-qt#1238]
```

00:00:01 - Qt Warning: "serverinfo" request failed with error: QNetworkReply::ContentNotFoundError
00:00:01 - Qt Debug: Current Moonlight version: "5.0.1"
00:00:01 - Qt Info: Gamepad mappings are up to date
00:00:01 - Qt Info: Latest supported GFE server: "99.99.99.99"
00:00:01 - Qt Debug: Found update manifest match for current platform
00:00:01 - Qt Debug: Latest version of Moonlight for this platform is: "5.0
```

**Comment by cgutman** [comment]
`00:00:01 - Qt Warning: "serverinfo" request failed with error: QNetworkReply::ContentNotFoundError`

This is an invalid response ([HTTP 404](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) error) from your host PC. The bug should be filed on the software running on your host PC rather than the Moonlight client.
