### ISSUE TITLE
Moonlight closing a few second after launching

### ISSUE THREAD

**Issue by Lexe4F** [moonlight-stream/moonlight-qt#1283]
Moonlight open the app on PC few second after launching the app closing and on Moonlight pops up a Error: "Connection Error / Streamer could not be started."

Windows 10 
Version 10.0.19045 Build 19045
Moonlight 9.02.2 on i-pad
Nvidia Driver 552.44
Geforce Experience 3.28.0.412
Card: Nividia GeForce RTX 2080 Ti

[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-qt/files/15368985/NvStreamerCurrent.log)

Br 
Lexe

**Comment by cgutman** [comment]
We can't really assist in troubleshooting GeForce Experience here (we didn't write it) and Nvidia has discontinued support for GameStream so they probably won't help either.

You can try a reinstall of GFE and/or your Nvidia drivers, but if that doesn't work, you'll have to use [Sunshine](https://app.lizardbyte.dev/Sunshine/?lng=en-US) for hosting. Sunshine is probably a better idea anyway because it's still receiving active development and support.
