### ISSUE TITLE
compiled Moonlight.exe not running on Windows 7 (application error 0xc0000005)

### ISSUE THREAD

**Issue by comsyspro** [moonlight-stream/moonlight-qt#1294]
**Is your feature request related to a problem? Please describe.**
Moonlight was compiled as described using `scripts\build-arch.bat` and `scripts\generate-bundle.bat` here:
https://github.com/moonlight-stream/moonlight-qt?tab=readme-ov-file#build-setup-steps
-Visual Studio 2022 Community
-Qt 5.15.2 for 32bit
-Qt 6.7.1 for 64bit and arm64

On Windows 10 and 11 Moonlight.exe works but on Windows 7 it doesn't and bringing up the following application error 0xc0000005:
![image](https://github.com/moonlight-stream/moonlight-qt/assets/13809377/db16e440-96dd-4877-b5cc-3dda698f5498)

**Describe alternatives you've considered**
When you download Moonlight from here (https://github.com/moonlight-stream/moonlight-qt/releases/tag/v5.0.1), it also works on Windows 7, so why this download release doesn't have the problem with application error 0xc0000005? How can you compile Moonlight so it will work on Windows 7, 10 and 11?

**Comment by comsyspro** [comment]
I found it out. For Windows 7 it has to be compiled with Qt 5.15.2 for 64bit. Only question would be if there is an advantage using Qt 6 over Qt 5?

**Comment by cgutman** [comment]
Well Qt 5.15 has been basically unmaintained since 2020 when development transitioned to Qt 6. There are a lot of features and bugfixes from the last 4 years that haven't made it into (non-commercial) versions of Qt 5.

FYI, Windows 7 support will not remain for long in official releases. After the next release, I intend to remove support for older versions of Windows (pre-Win10 1809) and macOS (pre-Big Sur) and update to Qt 6.7 for Windows and macOS builds. Qt 5 support will still remain in the codebase for Linux (which probably would work fine on Windows too), but you'll need to maintain your own builds of the [Moonlight dependencies](https://github.com/cgutman/moonlight-deps) if you want to continue to support Windows 7 beyond the v5.1.x series of Moonlight.
