### ISSUE TITLE
Moonlight Desktop Version 0.6.3 (Mac) does not map Xbox one Wireless controller correctly

### ISSUE THREAD

**Issue by estimablesir** [moonlight-stream/moonlight-qt#133]
Version 0.6.3 on OSX Mojave does not map the xbox one wireless controller buttons correctly when interacting with a Windows 10 host.  The streaming works perfectly, but certain buttons are mapped incorrectly. (for instance, the right shoulder being mapped to the start button).

I've attached the moonlight log here.  
[Moonlight-1542504990.log](https://github.com/moonlight-stream/moonlight-qt/files/2592452/Moonlight-1542504990.log)

**Comment by estimablesir** [comment]
Running the following command from the terminal seems to fix the issue: SDL_JOYSTICK_HIDAPI=0 /Applications/Moonlight.app/Contents/MacOS/Moonlight

**Comment by cgutman** [comment]
Looks like a regression from the new joystick HID API added in SDL 2.0.9. I think the issue is that it's assuming that it knows the right protocol to talk to the device based on its device ID, however this gamepad uses different message formats for BT HID and USB, so the messages aren't correctly interpreted.

**Comment by cgutman** [comment]
Actually, the PID is different when on BT vs USB. The real issue is that the mapping is different on older firmware even though both are connected via BT.

Filed SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=4395
