### ISSUE TITLE
No audio with Raspberry Pi 4 running Raspberry Pi OS Lite 64bit (Bookworm)

### ISSUE THREAD

**Issue by dvnkln** [moonlight-stream/moonlight-qt#1330]
**Description**
moonlight doesn't seem to default to pulse as described [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4). Seems to be buggy or the doc is outdated.

**Steps to reproduce**

- Fresh install of Raspberry Pi OS Lite 64bit (Bookworm) on a Raspberry Pi 4 B 8GB via Raspberry Pi Imager.

- Get the OS up-to-date:

```
sudo apt update
sudo apt upgrade
```

- Make sure pulseaudio is even installed (it wasn't for me by default):

```
sudo apt install pulseaudio
```

- Set pulseaudio to be the audio system:

`sudo raspi-config` -> Advanced Options -> Audio Config

- Double-check that you have audio:

```
speaker-test
```

- Install moonlight-qt as described [here](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4).

- Run moonlight-qt normally (via `moonlight-qt,` pair your host (win 11 client running Sunshine in my case) and stream anything (i tried Steam Big Picture Mode).

There will be no audio. I also tried to specifically TELL moonlight to use pulse and had audio like once:

```
SDL_AUDIODRIVER=pulse moonlight-qt
```

**Other Moonlight clients**
Did a test with my android using the moonlight app to rule out the source of the problem and it was running just fine.

**Moonlight settings**
Happened with default settings and after adjusting resolution, fps, bitrate and video encoding.

**Client PC details**
 - OS: Raspberry Pi OS Lite 64Bit (Bookworm)
 - Moonlight Version: 6.0.0
 - Linux package type (if applicable): apt package

**Server PC details (please complete the following information)**
 - OS: Windows 11 Pro 10.0.22631 Build 22631
 - Sunshine or GeForce Experience version: Sunshine v0.23.1
 - GPU: NVIDIA GeForce RTX 3070
 - GPU driver: Game Ready 555.99

**Moonlight Logs**
[moonlight.log](https://github.com/user-attachments/files/15914876/moonlight.log)

**Comment by cgutman** [comment]
Moonlight uses SDL for audio. SDL seems to be using PulseAudio as expected per your logs:
> 00:00:11 - SDL Info (0): Starting audio stream...
> 00:00:11 - SDL Info (0): Desired audio buffer: 720 samples (2880 bytes)
> 00:00:11 - SDL Info (0): Obtained audio buffer: 720 samples (2880 bytes)
> 00:00:11 - SDL Info (0): SDL audio driver: pulseaudio
> 00:00:11 - SDL Info (0): Audio stream has 2 channels

You can try `SDL_AUDIODRIVER=alsa` or `SDL_AUDIODRIVER=pipewire` to see if either of those work properly.

> Set pulseaudio to be the audio system:

What was the default audio system before you adjusted it?

**Comment by mpendel** [comment]
I'm not OP but I fixed my issue. OS Lite doesn't come with any audio driver. So I did the following:
```
sudo apt install pulseaudio
sudo raspi-config
```
- System Settings -> Audio -> select vc4-hdmi-0
- Advanced Settings -> Audio Config -> pulseaudio
- Exit, then `sudo reboot`

(My problem was I didn't select hdmi-0 output.)

**Comment by cgutman** [comment]
Yeah, I confirmed those steps work for me on Pi OS Lite and updated the docs.

FWIW, Pi OS Lite will output just fine to the 3.5mm analog jack using ALSA right out of the box without any additional configuration. HDMI audio appears to require PulseAudio (or at least I couldn't make it work with ALSA alone).

**Comment by epthewizard** [comment]
Having this same issue on Pi OS lite. I installed pulseaudio, set it in advanced options and then set hdmi as my audio output like above.

**Comment by JamesNelson2410** [comment]
I was running into this issue as well. I used Claude to resolve the issue. I 100% had no idea what I was doing but it walked me through how to fix. Here is the summary Claude gave me:

 Solution for Moonlight-Qt No Audio on Raspberry Pi OS Lite with HDMI

  Problem: Moonlight-qt streams video but no audio on Raspberry Pi OS Lite 64-bit with HDMI
  output.

  Root Cause:
  1. Raspberry Pi HDMI audio requires IEC958_SUBFRAME_LE format, which raw ALSA can't handle
  without proper conversion
  2. Moonlight-qt doesn't automatically use PulseAudio on headless systems
  3. When auto-starting via cron, environment variables aren't set for SDL audio

  Solution:

  1. Configure audio in raspi-config:
  sudo raspi-config
  1. Navigate to: System Options → Audio → Select vc4-hdmi-0
  2. Ensure PulseAudio is installed and running:
  sudo apt install pulseaudio
  pulseaudio --start
  pactl set-default-sink alsa_output.platform-fef00700.hdmi.hdmi-stereo
  3. Create a startup script (~/start-moonlight.sh):
  #!/bin/bash

  # Wait for system to be ready
  sleep 10

  # Ensure HDMI is the default
  export XDG_RUNTIME_DIR=/run/user/1000
  pactl set-default-sink alsa_output.platform-fef00700.hdmi.hdmi-stereo

  # Launch Moonlight with PulseAudio
  exec env SDL_AUDIODRIVER=pulseaudio moonlight-qt "$@"
  4. Make it executable:
  chmod +x ~/start-moonlight.sh
  5. For autostart, add to crontab:
  crontab -e
  5. Add: @reboot /home/USERNAME/start-moonlight.sh (replace USERNAME)

  Why this works: The script forces Moonlight to use PulseAudio (via
  SDL_AUDIODRIVER=pulseaudio), which handles the IEC958 format conversion that Raspberry Pi
  HDMI requires. The XDG_RUNTIME_DIR variable ensures pactl can communicate with PulseAudio
  when run from cron.

  ---
