### ISSUE TITLE
SteamOS upgrades shows 6.0.0 -> 5.0.1

### ISSUE THREAD

**Issue by michellabbe** [moonlight-stream/moonlight-qt#1344]
I happened to install all available upgrades on Steam Deck yesterday.

Current version:
- SteamOS 3.5.19
- Moonlight 6.0.0 from Flathub (user)

New Moonlight update appear today with a lower version number:
![image](https://github.com/moonlight-stream/moonlight-qt/assets/16291382/b7500af1-78be-4abb-b224-418ee0a645be)

You see 6.0.0 is installed and 5.0.1 is the current version in both Flathub branches:
![image](https://github.com/moonlight-stream/moonlight-qt/assets/16291382/22e9ea9b-0056-4703-9aac-fbfe4ce9e99c)

Description for new version really fits with 5.0.1 (I compared "What's new" with github releases):
![image](https://github.com/moonlight-stream/moonlight-qt/assets/16291382/be0c0727-d71f-4b73-a5e0-ee7c360a8565)

Flathub website shows 6.0.1 is really available:
![image](https://github.com/moonlight-stream/moonlight-qt/assets/16291382/f47c8c14-82e0-4411-bc3f-eda40ef7b824)

Not sure if it's just a typo in displayed informations or if it wants to downgrade to the older version.  I didn't apply it yet.
I'm leaving for vacation in the next hour and missing time to investigate more, but I wanted to report it.

**Comment by devnull34** [comment]
Confirmed, same issue.  6.0.0 on Windows 11, upgraded to 6.0.1, but 6.0.0 still displays.

**Comment by cgutman** [comment]
I think this may be caused by a couple of possible things:
- If you're running the `beta` branch of Moonlight on Flathub, please switch to the `stable` branch to receive updates. Beta isn't always used, so it may be out of date because Flathub doesn't automatically supersede older beta versions with newer stable ones.
- If you're on stable, it might just be an issue with KDE Discover. I noticed on the Updates tab of Discover that Moonlight v6.0.1 appeared incorrectly being a refresh of v6.0.0, while opening Moonlight and checking on the Settings page revealed that it indeed did update to v6.0.1. On my Fedora system, GNOME Software did correctly identify the same update as being an update to v6.0.1.

**Comment by michellabbe** [comment]
Looks like it's a KDE Discover cosmetic issue.  I applied the update and it updated to 6.0.1.

I'm not sure how to tell wether I'm running the `beta` or `stable` branch.  I installed it long ago but it was most likely with `sudo flatpak install flathub com.moonlight_stream.Moonlight`.   SteamOS itself is on `stable` branch.

If it's not an error on your side (ex. typo in version numbers) when pushing the update to some repos, then I believe there is no reason to leave this issue open.
