### ISSUE TITLE
Windows 6.0.1 

### ISSUE THREAD

**Issue by tamoanxx** [moonlight-stream/moonlight-qt#1347]
**Describe the bug**
Windows Installer is showing up not be me trusted and safe to SmartScreen. 

**Steps to reproduce**
Download the file and open it on windows. 

![image](https://github.com/moonlight-stream/moonlight-qt/assets/3393558/15d6fcd6-503b-4b94-8e58-f5c8568926dc)

I am running Windows 11 ARM latest 24H2 build.

**Comment by cgutman** [comment]
The Moonlight v6.0.1 binaries for Windows were signed with a new code signing certificate, since the old one was nearly expired. It takes some time for Microsoft SmartScreen to build trust of new certificates, so that's why you see the warnings initially.

The SmartScreen warning seems to be gone now when I tested today on a couple PCs, so I will close this issue.
