### ISSUE TITLE
Bitrate unlock to 1000Mbps

### ISSUE THREAD

**Issue by PlayXboxtion963** [moonlight-stream/moonlight-qt#1375]
Many users PC has a 1Gbit or even higher Network card.So we need unlock Bitrate to 1000Mbps instead of 150Mbps

I modify a version which can use 1000mbps. From real test with sunshine can get 100Mb/s video stream, which just need edit UI parameters.

**Additional context**
<img width="490" alt="截屏2024-08-02 07 32 45" src="https://github.com/user-attachments/assets/22478729-0d82-4930-a48d-5da18c19049a">

**Comment by Romanychev** [comment]
Can you share instructions?

**Comment by WinkelCode** [comment]
+1 From me as well, I am running 800Mbit bitrate (confirmed by Little Snitch w/ some motion on screen) just fine from an Nvidia RTX 4070 to an Apple M2 Pro Mac Mini via a direct Ethernet cable connection.

3440x1440 at 144hz, 4:4:4 RGB and 800Mbit bitrate is really cool to be able to use.

@Romanychev I can't speak for Windows, but on macOS you can run 

`defaults read ~/Library/Preferences/com.moonlight-stream.Moonlight.plist bitrate` to check the current bitrate setting
`defaults write ~/Library/Preferences/com.moonlight-stream.Moonlight.plist bitrate 800000` to set the bitrate (in my case 800000).

**Note:** The bitrate is reset to the 150Mbit (150000) when the settings are opened, so you will have to use the command again if you intentionally or accidentally click on the cog button.

I assume on Windows it will be similar, most likely a config file or registry entry.

Side note: On macOS, `.plist` files like the one above are cached, so you need to use `defaults` to change them and restart the application, in this case Moonlight, afterwards. Also, I am using very recent CI builds of Sunshine and Moonlight.

**Comment by cgutman** [comment]
I decided to add an experimental option to raise the limit to 500 Mbps. There are some protocol limits in play here (such as max packets per frame based on the 10-bit FEC packet index) and packet pacing code on the Sunshine side that is currently static and assuming we stay well clear of 1 Gbps. We'll need to solve that before we can unlock 1+ Gb speeds without issues.

**Comment by Snarfster** [comment]
Thanks for getting this rolled into builds along with 4:4:4. Between this at 250Mbps and 4:4:4 the quality is absolutely ridiculous with a super low latency. Simply amazing work here!

**Comment by ns6089** [comment]
@cgutman A note regarding this, we may also have to trick hardware encoders by passing lower frame rates to them during the initialization. For example HEVC in our 4:4:4 profile goes only up to 720mbit (level 6.2), and at least NVENC is known to enforce this limit seemingly out of nowhere.

**Comment by WinkelCode** [comment]
@cgutman @ns6089 I made a test video here: https://www.youtube.com/watch?v=65Z444q8Vo4

In the top right there is a bandwidth indicator, as you can see, it reaches ~95MB/s at times. The game is called Teardown and for some reason looking at the sky (max FPS + noise texture/rendering effects?) it fully utilizes the bandwidth. While messing around a bit in game I didn't notice any egregious performance issues, maybe a barely noticeable micro-stutter every so often. But overall totally playable, especially for network game streaming.

Possibly relevant non-default settings:
* Single-frame VBV/HRD percentage increase set to `400`
* FEC set to `0`.
* Two-pass disabled
* Quantization set to 10 (probably not relevant here)
* CPU thread count set to 4 (probably also not relevant)
* Moonlight bitrate set to 800Mbit/s (which is clearly exceeded, maybe because of the percentage VBV/HRD setting?)

Note: All of these settings come from me messing around with the options to see what (if any) effect they have, these are by no means "optimized" in any way.

**Comment by ns6089** [comment]
95MB is 760Mbit, which is expected by everything involved to be honest. That's close the rrate sunshine does network packet pacing, requested bitrate and the limit of HEVC profile level.

**Comment by WinkelCode** [comment]
> 95MB is 760Mbit, which is expected by everything involved to be honest. That's close to the rate sunshine does network packet pacing, requested bitrate and the limit of HEVC profile level.

Argh, MiB to Mbit conversion strikes again. Intuitively I thought it would've been something like 850Mbit but you're right, it seems to match the 760Mbit limit, my bad. Based on an iPerf UDP test I did between the devices, ideally we would be looking for around 117 MB/s (reported by the *Stats* app widget) or 950Mbit/s (reported by iPerf).
