### ISSUE TITLE
Does not work at all on windows 11

### ISSUE THREAD

**Issue by lokman2k5** [moonlight-stream/moonlight-qt#1393]
I'm trying to connect through moonlight to my windows 11 computer (Geforce experience) but all I see is a blank screen. I searched through the GitHub issues and followed the troubleshooting guide but nothing so far
I've tried using moonlight to connect to it using many devices with the same issue so the problem is from the host
this is a screenshot of what I see:
![image](https://github.com/user-attachments/assets/68e69a75-3fb6-4325-9bce-8c8781909b27)
after entering the pin into Geforce experience on the host.
i have tried sunshine, it works, but it's really slow and laggy

**Comment by cgutman** [comment]
> I've tried using moonlight to connect to it using many devices with the same issue so the problem is from the host

Moonlight is just the client. If GeForce Experience is having issues, that's provided by Nvidia (though I doubt you will get support from them either since they discontinued GameStream over a year ago).

It also looks like you're using the Android client, while this bug tracker and source code are for the PC client.

**Comment by wsu98633-cloud** [comment]
`

**Comment by wsu98633-cloud** [comment]
`[](url)`

**Comment by wsu98633-cloud** [comment]
A
