### ISSUE TITLE
Windows Lock screen input

### ISSUE THREAD

**Issue by roncamma** [moonlight-stream/moonlight-qt#162]
Hello ! First, thank you a lot for your work, it's amazing !

I have an issue when I lock my remote PC. Mouse and keyboard doesn't work to type my password. It works great whith the MacOS app.
Also, I think the issue was a same, when I launch specific app or want to install new one, mouse and keyboard are locked when Windows display a splash screen (where you must clic on Yes or No).

**Comment by cgutman** [comment]
This is a GFE 3.16 bug, not a Moonlight issue. Please comment in this thread to bring awareness to Nvidia: https://forums.geforce.com/default/topic/1082300/gamestream/gfe-3-16-regression-mouse-and-keyboard-doesn-t-work-on-uac-prompts-on-win8-1/

**Comment by roncamma** [comment]
Thanks for your answer !
I maybe have an older version of GFE when I used MacOS.

**Comment by roncamma** [comment]
Hi cgutman,
I verified GFE version on my remote PC, it's 3.16.0.140. And it works well on Moonlight MacOS app.

**Comment by b1be** [comment]
i am using this app
https://store.steampowered.com/app/367670/Controller_Companion/
with all options toggled on
http://pic.cr173.com/up/2017-2/20172221408542640.jpg

i enter password on lockscreen with L3 and type with controller, and it works.

mouse & keyboard doesnt work. but since i use controller it's ok.
Nvidia shield (clinet) supposed to have Controller Attached.

**Comment by cgutman** [comment]
It looks like the GFE 3.17 beta build at least fixes keyboard support, so it is possible to advance through the UAC dialog or login prompt with your keyboard.

**Comment by cgutman** [comment]
Fixed in GeForce Experience 3.19.0.94 Beta.
