### ISSUE TITLE
Black Screen on any games when starting 

### ISSUE THREAD

**Issue by johnblaze00** [moonlight-stream/moonlight-qt#167]
**Describe the bug**
After connecting to machine and launching a game, screen is all black. 

Tested on two macs running 10.14.3 and 10.14.2 

**Steps to reproduce**
Trying to connect to a game

**Screenshots**
No Screenshots

**Affected games**
All of them

**Moonlight settings (please complete the following information)**
- Tried changing rendering from software to hardware, no difference

**Client PC details (please complete the following information)**
 - OS: MacOS 10.14.3 & 10.14.2
 - Moonlight Version: Latest

**Server PC details (please complete the following information)**
 - OS: Windows 10 1809
 - GeForce Experience version: latest
 - Nvidia GPU driver: latest

**Moonlight Logs (please attach)**
Log attached of 10.14.3 machine 
[Moonlight-1548347863.log](https://github.com/moonlight-stream/moonlight-qt/files/2792649/Moonlight-1548347863.log)

**Comment by cgutman** [comment]
Is your host PC's monitor connected to the Nvidia GPU and turned on?

Does the issue happen if you're connected to the same network as your host PC?

**Comment by johnblaze00** [comment]
Same network or outside network. 

And host pc has no monitor attached. Never has and worked before. 

-g

**Comment by cgutman** [comment]
The lack of a monitor is probably the issue. When did it last work for you?

**Comment by johnblaze00** [comment]
I’ve been using it fo over a year without a monitor. That can’t be the reason. I tried it last in December. Been playing the PlayStation (Spider-Man) for a while. 

-g

**Comment by cgutman** [comment]
Can you try a different Moonlight client, like Android or iOS?

**Comment by johnblaze00** [comment]
Same thing on iOS app 

-g

**Comment by YueKnowWho** [comment]
the problem is that you need a monitor. I have been trying to use moonlight with my monitor powered off but that doesn't work and it disconnects so you need a monitor and it does have to be on. I would recommend investing in a small monitor like

https://de.aliexpress.com/item/3-5-zoll-LCD-HDMI-USB-Touch-Screen-Echt-HD-1920x1080-LCD-Display-f-r-Raspberri/32908609103.html?spm=a2g0x.search0604.3.1.465e4f875c64Vn&transAbTest=ae803_4&ws_ab_test=searchweb0_0%2Csearchweb201602_2_10065_10068_10130_10890_10547_319_10546_317_10548_10545_10696_453_10084_454_10083_433_10618_431_10307_537_536_10902_10059_10884_10887_100031_321_322_10103%2Csearchweb201603_54%2CppcSwitch_0&algo_pvid=7d7eefdb-a0b1-4f24-ab8c-de8d3ef3a0bb&algo_expid=7d7eefdb-a0b1-4f24-ab8c-de8d3ef3a0bb-0

or

https://www.amazon.com/TOOGOO-1920x1080-Display-Raspberri-MPI3508/dp/B07G6ZWFC3/ref=sr_1_1?s=electronics&ie=UTF8&qid=1548632964&sr=1-1&keywords=MPI3508

I don't know why this is but it might be a new update.

gl though.

**Comment by johnblaze00** [comment]
Thanks for the help/suggestions both of you. 

Yueknowwho is right, I needed to have a monitor attached all of a sudden (not sure what changed, I swear it worked without a monitor attached for about a year) but I bought this:

https://www.amazon.ca/gp/product/B0746HLHKM/ref=ppx_od_dt_b_asin_title_o00_s00?ie=UTF8&psc=1 <https://www.amazon.ca/gp/product/B0746HLHKM/ref=ppx_od_dt_b_asin_title_o00_s00?ie=UTF8&psc=1>

And its working now. Stupid how something like this is an issue…. Steam streaming works fine without a monitor, but not this (I am not blaming moonlight but nvidia, you guys are awesome). 

Thanks for all the suggestions! 

-g

**Comment by antonavy** [comment]
Damn, that sucks, switched off my monitor so save power. No idea when I would be able to get there next time to switch it on. No workaround? Or am I stuck with steam and parsec for now?

**Comment by bverkron** [comment]
This only started happening for me after switching to a new monitor and a Display Port connection instead of HDMI. Teamviewer, Parsec, and others worked fine with the previous setup (connected to my TCL 4K TV with HDMI) even when the display was powered off. Not sure if it's because the PC could still detect the display was there even though it was off or if it has to do with the connection type. I have found no workaround yet in software. Would rather not sped $20 on a dumb piece of hardware, will keep hunting.

**Comment by pdcmoreira** [comment]
I have a dual monitor setup, 1 through DisplayPort and 1 through HDMI.
If I try to stream with the DisplayPort monitor connected, alone or together with the HDMI one, all I get is a black screen.
For this to work, I must unplug the DisplayPort cable from the monitor and have just the HDMI monitor connected! Everything seems to work properly this way.

**Comment by jorismak** [comment]
Discovered that I'm in the same boat.

Two monitors connected, both displayport. The whole 'monitor needs to be connected' wasn't news to me.

But now (haven't used it for a while) I actually need both my monitors _enabled and on_.

So, my 'main' monitor actually has to be switched to the correct input so that my nvidia PC sees the monitor. Then streaming works fine. The moment I switch that main monitor to another input, my nvidia PC is still displaying the desktop fine on the other displayport monitor. But connecting through moonlight gives me the black screen.

While Windows really only sees one monitor connected?!

**Comment by darabos** [comment]
I hit this too with a headless setup. This virtual display device fixed it for me: https://www.amyuni.com/forum/viewtopic.php?t=3030
