### ISSUE TITLE
Customise Wake on LAN port for WOL via WAN

### ISSUE THREAD

**Issue by TAGinside** [moonlight-stream/moonlight-qt#184]
Hello,
i want send my WOL packet via internet directly in Moonlight App.

my custom port at my adress is : 9532 and after is forwarded.

its possible implement this ?

Thanks and great job

**Comment by cgutman** [comment]
Can you describe your scenario more?

Why are the default ports (7, 9, 47998, 47999, 48000) insufficient?

**Comment by TAGinside** [comment]
hello the port 7 and 9 are so simple and anybody can wake my pc if he knows my fixed IP WAN.

can i make a WOL packet in 47998, 47999,48000 ? in this case i can imagine foward theses port in 9 to my PC

**Comment by TAGinside** [comment]
Scénario: I have configured the port 9532 via internet to forward the packet magic to 9 internal.

with my phone this works great, but i have an android tv box in other house and when i make i wake on lan in Moonlight App does not work. i know its logic. thats why i demand if its possible set up a custom WOL port.

Thanks

**Comment by cgutman** [comment]
Wake-on-LAN also requires knowledge of the MAC address to wake the PC (though MAC addresses aren't secrets either).

I'm still not understanding something here. If you didn't have UDP 47998, 47999, or 48000 properly forwarded, you wouldn't be able to stream at all. So if you can stream, wake-on-LAN packets should be able to reach your PC via those forwarded ports, even if UDP 7 and 9 aren't forwarded.

**Comment by TAGinside** [comment]
Hello, i know mac adress is needed.

My stream works great.

My router is able to send a magic packet by forwarding a packet external port (at choice) to internal at port 9 for my case.

I have a Ubiqiti router.

You can check that link.

https://community.ubnt.com/t5/EdgeRouter/Wake-On-Lan-from-WAN/td-p/2264533

**Comment by cgutman** [comment]
ok, I think I understand. If you're concerned about security, I would suggest using a Wake-on-LAN password (supported by some devices) and an app that supports WoL with a password (which still isn't that secure, since the password is in plain-text and can be sniffed by an attacker). Unfortunately, WoL is just inherently not a very secure protocol.

Changing the port is probably not going to deter an attacker that has already figured out your MAC address. They will just send WoL packets to all UDP ports, since sending lots of UDP traffic is very easy for an attacker.

Moonlight will probably not integrate this feature itself due to the limited use case for it.
