### ISSUE TITLE
RAW mouse input not working on Mac OS

### ISSUE THREAD

**Issue by neyz** [moonlight-stream/moonlight-qt#187]
No matter what i choose : "RAW input" or not, the client seems to apply the client's mouse acceleration inside the session.

Tested with Mac OS and multiple games, moonlight client is latest version (can't seem to find in GUI the version number)

Tell me if i can do anything to help,

thanks !

**Steps to reproduce**
Put Mac OS maximum mouse sensitivity, enable RAW input and watch your mouse fly of the screen, disable RAW input and same behavior.

**Affected games**
Stelaris, steam client..

**Moonlight settings (please complete the following information)**
Tested with RAW input / on / off and full screen / borderless 

**Client PC details (please complete the following information)**
 - OS: Mac OS Mojave
 - Moonlight Version: 0.9.1

**Server PC details (please complete the following information)**
 - OS: Windows 10 1809]
 - GeForce Experience version: [e.g. 3.17.0.126]
 - Nvidia GPU driver: [e.g. 419.17]

**Moonlight Logs (please attach)**
Logs attached
[Moonlight-1551736941.log](https://github.com/moonlight-stream/moonlight-qt/files/2928458/Moonlight-1551736941.log)
[Moonlight-1551737970.log](https://github.com/moonlight-stream/moonlight-qt/files/2928459/Moonlight-1551737970.log)
[Moonlight-1551737996.log](https://github.com/moonlight-stream/moonlight-qt/files/2928460/Moonlight-1551737996.log)

**Comment by cgutman** [comment]
This is a limitation of macOS. There is no equivalent of WM_INPUT for raw input like Windows or XInput2 like Linux. The best you can do is disabling mouse scaling to reduce the acceleration curve.

There are tons of similar issues with various games on macOS:
https://www.reddit.com/r/GlobalOffensive/comments/3y6hzo/cant_turn_on_raw_input_mac_os_x_1095/
https://stackoverflow.com/questions/5782884/disabling-mouse-acceleration-in-mac-os-x
https://www.reddit.com/r/MouseReview/comments/7bg0n1/removing_mouse_acceleration_in_macos_and_osx_high/
https://www.reddit.com/r/GlobalOffensive/comments/5b6074/how_to_disable_forced_mouse_acceleration_on_mac/

The only way to get true raw input would be to use HID Manager to read the raw HID reports, but that comes with additional complexity as some devices may require fixups to return values that are even slightly reasonable (see libinput on Linux) and some devices like modern trackpads report absolute coordinates of each finger rather than a single motion value.

In any case, this is an SDL feature request, not a Moonlight one. You can ask for it on https://bugzilla.libsdl.org/
