### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by BloodWolfe** [moonlight-stream/moonlight-qt#193]
**Describe the bug**
At first this worked just fine for a week or 2 but suddenly (maybe a week or so ago) it seems I get constant lag. My mouse moves fine then suddenly very erratic and same with keyboard movements (in-game) where it will act as if the key is still pressed and move further than I want (or the opposite and doesn't respond). I assume its lag since the picture quality does degrade when this happens most of the time. It even lags when I open just to the desktop of my host (home) PC (added mstsc.exe in GeForce Experience as a program). It worked fine for me at the start but now I cannot get this fixed.

**Steps to reproduce**
I have tried it on 2 computers and tried playing around with all the different settings and nothing works. This was tried on 2 different computers over the internet and same issue. I tried it also on the one of those computers (laptop) at home and tried it connected over the internet as well as connected locally on the network (I tried both 5Ghz WiFi and Ethernet) and still the same issues.

My home (host) PC is connected via Ethernet on a 150 Mbps/15 Mbps connection to an AC2400 router. I have everything configured exactly as per the setup instructions and have tried clearing and setting it all up again but with no luck.

I even tried connecting to my computer using Chrome Remote Desktop (unfortunately I can't game in this since mouse input is ridiculous) but absolutely ZERO lag or issues when connected using CRD (even with a game opened and using the keyboard to move, everything is smooth). So this leads me to believe this is isolated to either the Moonlight Game Stream client OR maybe the latest Nvidia drivers? I even reverted back to 0.9.0 of Moonlight with no luck so I cleaned up and reinstalled 0.9.1 again.

**Affected games**
Tried playing Assassin's Creed Odyssey, World of Warcraft and For Honor.

**Moonlight settings**
- Have any settings been adjusted from defaults?
--> Yes, but I have tried defaults and all sorts of playing with the different settings.
- If so, which settings have been changed?
--> Settings used when it was working were (just listing the enabled check boxes): “1080p”, “30fps”, “10Mbps”, “V-Sync”, “Window (borderless)”, “Stereo”, “Maximize Moonlight Window on startup”, “Raw Mouse Input”, “Video Coded” and “Video Decoder” both kept with “Automatic (recommended)”, “Automatically find PC’s on the local network (recommended)”.
- Does the problem still occur after reverting settings back to default?
--> Yes.

**Client PC details**
 - OS: 1) Desktop PC is Windows 10 64-bit, build 1803 (still hasn't given update to 1809);
          2) Laptop is Windows 10 64-bit, build 1809.
 - Moonlight Version: 0.9.0 and 0.9.1

**Server PC details**
 - OS: Windows 10 Pro 64-bit, build 1809
 - GeForce Experience version: 3.17.0.126
 - Nvidia GPU driver: 419.35

**Moonlight Logs**
[Moonlight-1552653029.log](https://github.com/moonlight-stream/moonlight-qt/files/2971233/Moonlight-1552653029.log)
[Moonlight-1552654596.log](https://github.com/moonlight-stream/moonlight-qt/files/2971234/Moonlight-1552654596.log)
[Moonlight-1552655819.log](https://github.com/moonlight-stream/moonlight-qt/files/2971235/Moonlight-1552655819.log)
[Moonlight-1552655905.log](https://github.com/moonlight-stream/moonlight-qt/files/2971236/Moonlight-1552655905.log)
[Moonlight-1552655919.log](https://github.com/moonlight-stream/moonlight-qt/files/2971237/Moonlight-1552655919.log)

**Additional context**
Not sure if this helps but at home I usually stream from my Nvidia Shield TV (2017 model) with no issues on lag or delays of any sort. It’s literally only when using Moonlight Game Stream.

**Comment by cgutman** [comment]
It appears your issues are largely network-related.

```
Average receive time: 19.62 ms
Average receive time: 14.70 ms
Average receive time: 22.09 ms
Average receive time: 19.62 ms
```

Your receive time values are very high. This is the time from the first packet of a frame to the last packet of the frame. A high value indicates there is significant network jitter (latency variance) on your connection. Values around ~5 ms are acceptable, with good wired connections being under 0.5 ms receive time.

Can you post SpeedTest.net results for both your client and host?

The jitter can often be caused by pushing more data than your connection can handle consistently (regardless of what SpeedTest says), so lowering your bitrate in Moonlight may help. Your connection appears to be able to handle 5 Mbps, but not consistently. It could be that a link between the client and host flutters around 5 Mbps capacity with a big enough buffer to avoid outright packet loss, but the buffering is still visible as jitter.

Chrome Remote Desktop uses more efficient, but slower compression, because it's designed to work over very limited connections. It also uses client-side mouse rendering like MS RDP, so you can't rely on that to "test" latency. GameStream's compression is optimized for lowest pixel-to-network latency, so it will take more bandwidth to encode the same image because of the reduce amount of time for encoding to take place.

The Internet is a significant variable in your performance. We should debug the issue on your LAN first, since you say it also happens there. Please get logs from LAN streaming

**Comment by BloodWolfe** [comment]
1) Host SpeedTest results: https://beta.speedtest.net/result/8115410244 (9ms / 139.88 Mbps download / 14.31 Mbps upload).

2) Client SpeedTest results (not the best connection but it was fine initially for a couple of weeks or so when I first tried Moonlight out): https://beta.speedtest.net/result/8115420138 (8ms / 10.22 Mbps download / 11.52 Mbps upload).

3) As for the logs for LAN, I will get that later when I have the time and post that tonight or tomorrow (don't have access to the laptop to get the previous logs from last night and I am away from home at a friends where the desktop client is).

**Comment by BloodWolfe** [comment]
So, all weekend I was unable to reproduce this problem from the laptop I tried out at home and had the same input lag as with the desktop computer but I had some Windows updates waiting on the laptop and I read about an update MS put out that caused some input lag with some games. Who knows if that was the issue but laptop on the home network worked fine all weekend so no idea.

Trying out the computer again and will see today what happens but this one had no Windows updates waiting but is still 1803 and not 1809 update so maybe that is part of the problem?

**Comment by cgutman** [comment]
Are you still able to reproduce the issue?

**Comment by BloodWolfe** [comment]
At home on the laptop it seems fine now still and unable to reproduce that. Out of the house on a friends desktop I still have the same issues.
