### ISSUE TITLE
Add pair/unpair/list actions for command line

### ISSUE THREAD

**Issue by posti85** [moonlight-stream/moonlight-qt#209]
The only actions available through command line are `stream` and `quit`. But you still can't `pair`/`unpair` a host or `list` the games available in it. So moonlight-qt could never be used unless the GUI is opened, at lest to pair the PC. Sometimes that is impossible in some linux distros (like OSMC, RetroPie...). (Are there any workarround for this while this funcionality isn't available?)

**Comment by cgutman** [comment]
I think I'm missing something here, because I'm not sure why the Qt GUI is not okay, but streaming (which runs in a GUI window) is okay.

Can these distros not load the Qt-based GUI at all? Or is this to support launching directly into games from a centralized launcher? Can you not navigate the Qt GUI using gamepad/remote/whatever that you're using to navigate the distro's UI itself? Is it a problem that using the command-line options still launches the GUI to display the loading screen?

I'm not opposed to adding more command-line functionality. I just want to make sure we're solving the whole problem.

**Comment by posti85** [comment]
Oh... well. I was thinking about making it run in a Raspberry Pi running a distro without a graphical environment. But first, I've found out that it is impossible making it run in Rpi (https://github.com/moonlight-stream/moonlight-qt/issues/160) and also, of course, the streaming is done via de gui... So you are right, it doesn't make sense at all.

**Comment by cgutman** [comment]
I ended up writing the hardware video decoder code for the Pi, so I've re-opened #160 

I'm still aiming to make the GUI work without X, rather than trying to make Moonlight work completely without a GUI.

**Comment by posti85** [comment]
OMG @cgutman that is amazing! The same client for all the platforms with or without X :dancer: Thank you very much!

**Comment by cgutman** [comment]
Done in https://github.com/moonlight-stream/moonlight-qt/commit/de881769950bf34ed8af6ba8786dcfe378452f6d and https://github.com/moonlight-stream/moonlight-qt/commit/aaf59c2d015d4cca71a55bee7bbf2b268509f202
