### ISSUE TITLE
希望能像VMware一样，捕获所有键盘事件

### ISSUE THREAD

**Issue by h1ve2** [moonlight-stream/moonlight-qt#234]
希望能像**VMware**、RemoteDesktop(mstsc.exe)一样，捕获所有键盘事件，**包括windows系统快捷键**。只有在用户按下**Ctrl + Alt + Shift + Q** 之后moonlight暂停对所有按键的捕获。

在游戏中出现问题的话，无法使用**Ctrl+Alt+Del**来使用任务管理器(taskmgr)进行强制关闭。

**Comment by cgutman** [comment]
This is not possible with GameStream since it filters out certain key combinations. What you can do is [add the game into GeForce Experience manually](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#adding-custom-programs-that-are-not-automatically-found) then if it stops responding you can quit it by disconnecting the stream and clicking the close button on the app.
