### ISSUE TITLE
Enhance usability with multiple monitors

### ISSUE THREAD

**Issue by koshisan** [moonlight-stream/moonlight-qt#248]
**Is your feature request related to a problem? Please describe.**

I use moonlight with two displays. I have it running on the left screen while working on the right. This causes two issues:

* When switching to fullscreen by keyboard command, the setting for Display Borderless Windowed/Fullscreen is not honored. It does always switch to native Fullscreen. This is a problem, because if you release the mouse and click anywhere outside moonlight, the resolution is changed back and the window disappears...

* Even with "Raw mouse input" the mouse is grabbed exclusively, so you have to use a keyboard command to release it. Unfortunately the commands are hardcoded, so this causes inputs to the running game, if it uses some of the keys...

**Describe the solution you'd like**
A perfect solution would be to alter the menu settings in the following way:
Display mode should be renamed "Fullscreen Method" with selectable "Borderless windows/Exclusive". Startup Mode Option "Fullscreen/Windows" should be added.

Option for "Use mouse exclusively" or "lock mouse" should be added. The Keyboard command ctrl-alt-shift-z should be used to toogle between modes

**Describe alternatives you've considered**
When I start with "Borderless windowed" and then toggle into windowed mode the window behaves as desired, so that is a work around at the moment. As for the mouse I have not found a workaround yet.

**Comment by cgutman** [comment]
Unless I'm misunderstanding, the mouse capture behavior is working as intended. GameStream uses relative mouse motion events (as do many games) so there is no way to have the full range of mouse motion without capturing (otherwise you'd run into the borders of the window). When you Alt+Tab out of the window, mouse and keyboard focus should be uncaptured automatically.

The window -> full-screen transition issue is noted. I'm not really jazzed about adding yet another option to the "basic options" group. Maybe I will just make borderless windowed the default full-screen when toggling from windowed.

**Comment by koshisan** [comment]
I see. I was using Shadows streaming client until recently and they had an option for the mouse handling, so I thought it might be somewhat easy to implement. Seems I was mistaken ;) 

I am not sure what you mean with "otherwise you'd run into the borders of the window"? Think of it as running Minesweeper on the server on the right screen in borderless window mode while using outlook on the client on the left screen and simply moving the mouse cursor from one window to the other. It would not be practical for FPS games or something like that of course...

Alt-Tab works! Could have noticed that myself...

As for the full-screen transition: Yes, I think making borderless windowed the default would be a perfect solution!

**Comment by cgutman** [comment]
If the mouse wasn't captured, your local cursor wouldn't stay in sync with the remote one (remember, all we  are sending is offsets from the previous location of the mouse, not an exact location to move to).

For example, if you had a lower resolution monitor on your client than your host PC, your local cursor would reach the edge of the screen before the remote cursor did and so you wouldn't be able to click stuff in the corners. Similar things happen if mouse acceleration or pointer speed is not exactly the same between the client and host. You'd also see two cursors (one local, and one remote).

With all that said, I do see evidence that Nvidia is working on client-side cursor rendering which would solve this issue for games/apps that don't capture the mouse themselves. Hopefully we'll see that finished soon.

**Comment by koshisan** [comment]
Just out of curiosity: Would it be possible for moonlight to track the position of the cursor inside the window, so it could automatically disable capturing when it hits the edge? And enable it, when the cursor or focus is returned?

**Comment by cgutman** [comment]
When the cursor is captured, there's no concept of an actual position, just deltas from the last position. 

Depending on how the capture works on each OS, it may stay in the same spot it when it was first captured or it could be automatically warping back to center as it gets toward the edge of the screen.

If we let it hit the edge and uncaptured, that's no different than not capturing at all. The point of capturing is so that you can exceed the bounds of your window.
