### ISSUE TITLE
Mouse / keyboard not working on Steam Link Firmware 692

### ISSUE THREAD

**Issue by geekycow** [moonlight-stream/moonlight-qt#251]
**Describe the bug**
Neither mouse (USB) or keyboard (USB or Bluetooth) events from the Steam Link seem to get sent to the streaming host.

**Steps to reproduce**
- Boot up host computer.
- Quit Steam (to exclude it's input processing from the equation.)
- Ensure GFE is running.
- Add Chrome as a custom Shield Gamestream app link (to use as a test case.)
- Connect a mouse and keyboard to the Steam Link (happens whether or not there's also a Gamepad connected.)
- Boot up Steam Link.
- Select Moonlight with mouse.
- Select Chrome from the list of apps.
- Chrome does not see any mouse or keyboard input.  (Note: sometimes mouse movement-only - seems to work, but only on the first connection, and no keyboard input or mouse clicks.)
- Disconnect.
- Try again, same issue.

**Screenshots**
N/A

**Affected games**
All apps, including Steam, whether or not Steam is running.

**Moonlight settings (please complete the following information)**
- Does the problem still occur after reverting settings back to default?
Happen with default settings, whether or not Raw mouse is selected.

**Client PC details (please complete the following information)**
- Device: Steam Link
- OS: 692 (public)
- Network: 1Gbps
- Moonlight Version: moonlight steam link v1.0.1

**Server PC details (please complete the following information)**
- OS: Windows 10 Pro 17134 64bit
- CPU: Intel i5-4460
- GPU: GTX 960 2Gb
- RAM: 32Gb
- Network: 1Gbps
- GeForce Experience version: 3.19.0.94
- Nvidia GPU driver: 417.01

**Moonlight Logs (please attach)**
Will attach.

**Additional context**
I gather this used to work, so I imagine it's a regression issue?

**Comment by geekycow** [comment]
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/3326943/moonlight.log)

**Comment by cgutman** [comment]
I can confirm the regression. It appears that Steam Link firmware 692 broke Moonlight. I will try to look into it tomorrow.

In the meantime, you can downgrade back to build 688 using the instructions here: https://support.steampowered.com/kb_article.php?ref=3966-EFLV-7805

**Comment by cgutman** [comment]
This is definitely a bug in the SDL library shipping in 692. `SDL_SetRelativeMouseMode(SDL_TRUE)` returns `No relative mode implementation available` now.

**Comment by cgutman** [comment]
It turns out SDL_SetRelativeMouseMode() was silently failing on prior firmwares and an SDL update fixed that bug, causing the regression. I implemented a fallback to deal with this in https://github.com/moonlight-stream/moonlight-qt/commit/16b301236b7ed261fb85cccf3bc57caa9bcef4b1 and https://github.com/moonlight-stream/moonlight-qt/commit/ea8b905f0220cb6bf21529b76f3802c0afc72992

Here is a fixed build: 
[Moonlight-SteamLink-1.0.1-MousePatch.zip](https://github.com/moonlight-stream/moonlight-qt/files/3353433/Moonlight-SteamLink-1.0.1-MousePatch.zip)


However, I think SDL_SetRelativeMouseMode() should be returning 0 since it actually did all we asked for (even if it was just hiding the cursor and relying on evdev events which are relative already). I'm going to also file a bug on SDL upstream to add a no-op SetRelativeMouseMode() implementation for Vivante.

**Comment by geekycow** [comment]
Thank you, the fixed build works perfectly here too.  :)

**Comment by cgutman** [comment]
The SDL bug is fixed in Steam Link 693 firmware, so it's fixed on all fronts now.
