### ISSUE TITLE
[question] how to block hotkeys captured by other apps?

### ISSUE THREAD

**Issue by cainiaocome** [moonlight-stream/moonlight-qt#298]
First of all, wonderful job, moonlight. Moonlight is the only one working streaming solution for me, way much better than steam in home streaming.

I have a mac and a Ubuntu with moonlight installed. On the mac, I have spotlight search with hotkey Ctrl+Space. On the Ubuntu I have Albert installed with hotkey Ctrl+Space.

Problem is, I am playing half life which is an old FPS game. Sometimes I need to press Ctrl and Space to do a jump and squat. But Ctrl+Space will be captured by spotlight(mac) or Albert(Ubuntu) and then their search window will pop up.

I have to disable hotkey every time when I start moonlight to get rid of those pop up windows. Then after streaming I need to turn hotkeys on again. A little tedious.

So my question is is there a setting or proper solution to this?

Sorry about so much muttering, I am practicing my English writing skills recently, so anytime I have a chance to use English I would rather use them more.

**Comment by Forceflow** [comment]
This - imho - sounds like other programs taking precedence over Moonlight, and nothing Moonlight could fix.

Since you're on an Ubuntu / Mac system, maybe you could make a script that, for example on Ubuntu:

1. Kills Albert
2. Starts Moonlight
3. (Gaming here)
4. (moonlight closes, script continues)
5. Start Albert again
