### ISSUE TITLE
Feature Request - Command line launch options

### ISSUE THREAD

**Issue by bellinger61** [moonlight-stream/moonlight-qt#30]
Linux command line support, no documentation available on this currently and previous java based command line options do not function with recommended run commands associated with flatpak

**Comment by cgutman** [comment]
There's no command line option docs because there are no supported command line options yet. This client is a complete rewrite sharing none of the previous Java client code, so none of the previous options will work on this client until we implement them.

**Comment by bellinger61** [comment]
Thank you for the quick response, I've been a long time user of moonlight on many platforms but have been stuck using steam streaming on my repurposed Mac mini retropie linux box, this moonlight client already far surpasses the quality I have gotten from the steam client hands down.

Really appreciate your and the rest of the teams work and look forward to the Linux and PC versions continued development!!!

**Comment by jhakonen** [comment]
I would like to have this feature too. It would be great to have a handy shortcut on desktop to open a game directly in my gaming PC. So, I've been hacking the code and trying to make this feature happen. I have it mostly done. I can open a game stream directly from command line and it works. But, it's very sunny case, no error handling whatsoever. So, still needs work.

Launching the stream shows first a segue window, like the one you get after clicking a game in the actual menu UI, which shows connection progress.

Here's what I have come up with the command line options:
```
> moonlight.exe --help
Usage: moonlight.exe [options] action

Options:
  -?, -h, --help  Displays this help.
  -v, --version   Displays version information.

Arguments:
  action          Action to execute
```
If you don't provide the action, the normal moonlight UI will open.
Here's help for starting game stream:
```
> moonlight.exe stream --help
Usage: moonlight.exe [options] stream host game

Options:
  -?, -h, --help                   Displays this help.
  -v, --version                    Displays version information.
  --720                            Use 1280x720 resolution.
  --1080                           Use 1920x1080 resolution.
  --1440                           Use 2560x1440 resolution.
  --4K                             Use 3840x2160 resolution.
  --width <width>                  Specify horizontal resolution to use.
  --height <height>                Specify vertical resolution to use.
  --vsync                          Use V-Sync.
  --no-vsync                       Do not use V-Sync.
  --fps <fps>                      Specify FPS to use.
  --bitrate <bitrate>              Specify bitrate in Kbps to use.
  --display <display>              Select display mode:
                                   borderless/fullscreen/windowed.
  --audio-config <audio-config>    Select audio config: auto/stereo/surround.
  --multi-controller               Use multiple controller support.
  --no-multi-controller            Do not use multiple controller support.
  --mouse-acceleration             Use mouse acceleration.
  --no-mouse-acceleration          Do not use mouse acceleration.
  --game-optimization              Use game optimizations.
  --no-game-optimization           Do not use game optimizations.
  --audio-on-host                  Use audio on host PC.
  --no-audio-on-host               Do not use audio on host PC.
  --video-codec <video-codec>      Select video codec: H.264/HEVC/auto.
  --video-decoder <video-decoder>  Select video decoder:
                                   auto/hardware/software.

Arguments:
  stream                           Start stream
  host                             Host computer name or address
  game                             Game name
```
Note that on windows you don't actually get this nice text output since UI apps don't have console normally. Instead you get message dialog, e,g,:
![help](https://user-images.githubusercontent.com/1950698/45642437-d41da580-bac0-11e8-8a29-48a682c8c727.png)
It's not pretty, but other option would be to create a QML based dialog for that. That however would require a way more code than the current way. Not sure which way would be better choice.

I've tried to model the parameters after moonlight-pc's and moon-embedded's, but there are differences. Reason for the differences are that, e.g, moonlight-pc has _-fs_ parameter, but moonlight-qt supports 3 different modes; windowed, fullscreen, and borderless. So, I didn't want to create 3 different options which would have been mutually exclusive with each other. So, I used _--display \<mode\>_ instead.

If you don't provide an option when lauching stream, the option's value is read from stored settings. Settings which you may have altered through UI's settings window.

You can also use single dash mode to set options, so e.g. _--display_ can be given also as _-display_. The default help printout that QCommandLineParser provides seems to print options with double dash even with single dash mode on. I guess I could do search&replace on the help text to convert double dash to single dash if it is something you want?

Should I add, change, or remove something regarding these command line options?

Another thing is pairing. If the host hasn't been paired yet, should it try to do that before the game session starts? Or should there be a just an error shown if the host hasn't been paired yet? Or should there be another command or option for pairing like moonlight-pc and moonlight-embedded has? Or is it enough that you can do the pairing through the normal menu UI?

**Comment by cgutman** [comment]
I would prefer `--display-mode` rather than `--display`. I would also change the `--width` and `--height` options to a single option that sets both, since you could get really weird behavior if you only set one and it pulled the other from QSettings.

I don't have a problem with pairing being done via GUI for now.

**Comment by jhakonen** [comment]
Yeah, `--display-mode` sounds better.
To replace `--width` and `--height`, would, say `--resolution <WxH>` work? e.g. `--resolution 3440x1440`.
Could even consolidate `--720`, `--1080`, `--1440` and `--4K` in to it in form of e.g. `--resolution 1080`. Or is it important to have separate "shortcuts" for the more used resolutions?

**Comment by jhakonen** [comment]
Implementation should be done now, made a pull request:
https://github.com/moonlight-stream/moonlight-qt/pull/89

**Comment by shodanx2** [comment]
Hello,

Is there a command line argument equivalent to 

Ctrl+Alt+Shift+M - Toggle mouse mode (pointer capture or direct control)

My command line is

"C:\Program Files\Moonlight Game Streaming\Moonlight.exe" --display-mode windowed   --resolution 1280x720 stream myhost.example.net desktop

The only problem I have is that I have to press Ctrl+Alt+Shift+M every time to be able to move my cursor seamlessly in and out of the window !
