### ISSUE TITLE
[Feature Request] Sli config , dedicate a card for streaming

### ISSUE THREAD

**Issue by rimx92** [moonlight-stream/moonlight-qt#306]
in case of a SLI config with 2 card identical or not, i would like to know if in the futur it would be possible to dedicate a card for streaming only ( video compression) and one for gaming .

**Comment by cgutman** [comment]
This isn't something we can do since we just control the client side, and this would need to be implemented on the host.

With that said, I don't think that would help performance. It would probably make it worse. The fixed function encoding NVENC hardware on the GPU doesn't use the CUDA cores, so the performance impact on games is extremely low. Transferring the raw frame data across GPUs prior to encoding will just increase latency and waste GPU-GPU bandwidth that could be used for other things.
