### ISSUE TITLE
Server crashes/service quits after connecting via Windows remote desktop

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#312]
When I connect with a Windows remote desktop to the server, the server isnt avaibale anymore via Moonlight afterwards, even after quitting the remote connection, and you have to reboot the server PC.

[nvlog.txt](https://github.com/moonlight-stream/moonlight-qt/files/3965653/nvlog.txt)

After the connection of the Windows 10 remote client, this is shown in the Nvidia panel: 

https://i.imgur.com/rVpeMtb.png

How to reproduce:

1. boot server
2. connect with a Windows 10 remote desktop
3. close the connection
4. Nvidia gamestreaming is now not running anymore
5. have to reboot the server PC

**Comment by cgutman** [comment]
This issue is documented on the wiki - https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#known-application-compatibility-issues

RDP creates a special virtual GPU and display device which doesn't support Nvidia GameStream since it's not a real GPU nor does it have any capture or encoding hardware. Any other remote desktop solution besides RDP works fine (Chrome Remote Desktop, TeamViewer, LogMeIn, etc)
