### ISSUE TITLE
Resolution not correct if client/server have different resolutions

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#324]
Not sure why this isnt working anymore, it worked in the past. I wanted to stream in 1440p in a window to a 4k display on the client, and this results in this: https://i.imgur.com/dLG7mAU.jpg

The servers resolution is set to 1440p I even rebooted to make sure: https://i.imgur.com/X1XmJMN.png

Looks like Moonlight thinks the stream is 1080, the moonlight window is correctly using 1440.

[Moonlight-1577463074.log](https://github.com/moonlight-stream/moonlight-qt/files/4005750/Moonlight-1577463074.log)

Log says resolution is "Video stream is 2560x1440x60 " but the moonlight client doesnt scale it properly to the right window size it seems.

Moonlight client:
https://i.imgur.com/AtJkVYE.png

The resolution slider in Moonlight is also ignored it seems, it doesnt change the resolution on the server at all whatever I chose.

**Comment by cgutman** [comment]
These troubleshooting requests are probably best for Discord rather than GitHub, since they're usually problems specific to your individual setup.

Two things to check here:
- Verify that in your NVIDIA Control Panel on the "Adjust video size and position" page, that "Perform scaling on" is set to "GPU".
- Try adjusting your DPI settings to 100% DPI rather than 175% as you have in the screenshot.

**Comment by makedir** [comment]
That has nothing to do with the issue, as you can see, Moonlight is the causer, of not stretching the video to its window.

**Comment by cgutman** [comment]
Trust me, I have seen this issue before and the captured video stream coming from the PC that is the problem. It's not Moonlight's bug. If you don't believe me, you can capture the video data and play it in VLC.

Moonlight doesn't need to scale anything because the 1440p video stream can be displayed without any scaling at all - it's a 2560x1440 stream displayed in a 2560x1440 window. The broken video capture scaling you see is all happening on the host PC. Scaling on the client only needs to happen when the video encoding resolution doesn't match the client output size.
