### ISSUE TITLE
Mouse issues

### ISSUE THREAD

**Issue by stripeyhorse** [moonlight-stream/moonlight-qt#33]
Im using the latest release and my mouse is very unresponsive.

I have also tested the Chrome plugin same thing.

I note testing with parsec mouse is working perfectly.

**Comment by cgutman** [comment]
What games are you testing with? Does the responsiveness get better or worse when forcing software decoding?

**Comment by stripeyhorse** [comment]
testing mainly with windows (and minecraft)

Ill try software. The streaming pc has a 1080TI with a i7 7700k

**Comment by ReindeerG** [comment]
Uhm.. Physical Mouse Property(DPI Setup) is ignored and just set by servers pointer option(Control pannel).

**Comment by cgutman** [comment]
@ReindeerG I don't understand what you're talking about. Can you clarify?

**Comment by ReindeerG** [comment]
The physical setting (DPI) of the mouse connected to the console is ignored, and only the speed of the "Control Panel> Mouse> Pointer Option" is affected. Does not it feel like the mouse sensitivity is different from usual?

**Comment by cgutman** [comment]
@ReindeerG Windows has no built-in mouse DPI management AFAIK. The only configurable settings for mouse speed is the slider in the Mouse Control Panel applet and the Enhance Pointer Precision checkbox (which toggles mouse acceleration). GeForce Experience does set mouse acceleration to disabled when streaming to prevent mouse acceleration from being active when gaming, if that's the sensitivity difference you're talking about.

@stripeyhorse Is your issue that you're seeing input lag that makes the mouse feel sluggish or that you're seeing the mouse move slower than you're expecting due to mouse acceleration being disabled?

**Comment by agrier9** [comment]
I'm having the same issues mouse movement is slower in moonlight but there's significant lag in comparison to the chrome client. For instance if I swipe left the movement is delayed but about half a second.

**Comment by agrier9** [comment]
This issue has to do with the polling rate of most gaming mice. Turn your polling rate to 250 or less and it fixes this issue.

**Comment by cgutman** [comment]
Interesting, thanks for the additional info @agrier9. What OS are you running?

My effective mouse polling rate is about 500 Hz both locally and when streaming via Moonlight as tested by https://zowie.benq.com/en-eu/support/mouse-rate-checker.html

Can you try that site and see what you get locally and via Moonlight?

**Comment by cgutman** [comment]
@agrier9 Your issue is fixed by https://github.com/moonlight-stream/moonlight-qt/commit/203b2fcaca2851d4232a1b152b830569736f10d7
