### ISSUE TITLE
Mouse input lag and stutter on MacOS

### ISSUE THREAD

**Issue by rohithpalagiri** [moonlight-stream/moonlight-qt#343]
**Describe the bug**
When I am streaming to my Macbook Pro, there is noticeable mouse input lag. It's not terrible but it's very apparent compared to something like Steam Remote play which is almost 1:1 movement.

In addition, every 5-10 seconds the mouse input will stutter. So if I move from one side of the screen to another, you don't see the whole movement of the mouse panning over. It just disappears and appears at the destination spot.

This doesn't appear to be an issue with the stream itself. For example, on the Civilization 6 main menu there are images that pan across the screen. These images remain smooth as they pan **while** the mouse is stuttering and suffering these problems.

**Moonlight settings (please complete the following information)**

I have adjusted all of the following settings in an attempt to identify if that was the cause of the issue:

- Raw User Input
- V-Sync
- Bitrate and Resolution (lowered it all the way to 720p and 30 FPS)
- Frame Pacing

**Client PC details (please complete the following information)**
 - OS: macOS 10.14.6
 - Moonlight Version: v1.2.1

**Server PC details (please complete the following information)**
 - OS: Window 10 Home 1909
 - Nvidia GPU: 2080TI
 - CPU: i5-6600k

**Additional context**
In addition to trying to change a few settings I have also attempted the following based off of previous threads.

- Disable Location Services
- Disable Bluetooth
- Disabled Airdrop (should be disabled when Bluetooth is off)

I am running on Gigabit internet with the WiFi speeds around 350 down on my Mac.

**Comment by denschub** [comment]
I can reproduce the same, in various games and even the desktop itself. It doesn't feel like "lag", and more like a really low resolution mouse transfer. The mouse visibly stutters across the stream, even though the image itself is fluent. I double-checked by plugging a second mouse into the target computer and performing the same actions, which were smooth.

**Comment by cgutman** [comment]
Can you try taking an Instruments CPU usage trace?

**Comment by GregFinger** [comment]
Very similar situation, seems to happen on a set time interval, maybe 10 seconds. I also noticed that when I’m downloading (in this instance, it was a fairly large torrent file), having a constant data download stream, got rid of the stutters. 

This leads me to think it’s due to the router do something funky in the background. I have an Arris BGW210, the standard one that AT&T provides for their fiber service. Which router do you @rohithpalagiri @denschub have?

**Comment by cgutman** [comment]
The fact that background traffic changes the behavior is a very interesting find. That leads me to believe it's probably some misbehaving WiFi power management feature like WMM APSD. I'm going to look into that and see if maybe setting our outbound control stream traffic to a higher priority using `SO_NET_SERVICE_TYPE` helps at all.

Can anyone reproduce this _without_ WiFi?

**Comment by denschub** [comment]
> Which router do you @denschub have?

A Cisco piece of datacenter hardware that probably nobody else has. :)

> Can anyone reproduce this without WiFi?

Jup, I only use Moonlight via a wired connection.

**Comment by cgutman** [comment]
After some very helpful testing from plgrm on Discord, I've made a couple fixes that should help.

Try this build and let me know how it goes - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/31807114/job/u598rogrof65o994/artifacts

**Comment by denschub** [comment]
Sorry, it's difficult to find time right now. :)

@cgutman that appears to indeed have made things better. I'm being careful, because the issue wasn't always there, buuuut I couldn't get it to stutter in a couple of sessions now. I'll ping back in a week or so with more complete results.

**Comment by denschub** [comment]
Okay, sorry, took me a while.

This is, unfortunately, not resolved. Even with your custom build, the issue is still there, and there is a notable difference between having the mouse stream over Moonlight and having the mouse directly plugged into the target system. It's super hard to capture on video, as I'd need to capture in 120+fps to not cause more issues during the reencodings, but it's absolutely noticable.

Looking at the CPU activity, it looks like Moonlight is saturating one core occasionally, but since the stuttering is always there, that might not be related:

<img width="1202" alt="Screenshot 2020-04-24 at 19 05 31" src="https://user-images.githubusercontent.com/344777/80238949-a0710d00-865f-11ea-86bb-3fbebdb57418.png">

I can't share you the full trace publicly, as I don't have an isolated environment to capture one without potentially identifying background process names, but please let me know if you need more information or if I can help somehow.

**Comment by cgutman** [comment]
Can you describe the "noticeable difference" a bit more?

Are the pointer ballistics wrong? Is it too slow/fast? Does it stutter as it moves?

The pointer ballistics aren't expected to match the native macOS behavior because Windows uses a different acceleration curve and also because GFE mucks with the settings too. If what you're looking for is 1:1 absolute cursor support for remote desktop usage, the dev builds have it and that might be more suitable for your use case (toggle with Ctrl+Alt+Shift+M) - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/32405030/job/2q4wgjed2o7yp0eo/artifacts

For the CPU issue, a single thread saturating one core would definitely be unexpected, but seeing all of Moonlight's threads adding up to a single logical core's worth of CPU usage wouldn't really be. Can you see if it's just one thread causing most of that CPU usage?

**Comment by denschub** [comment]
> Can you describe the "noticeable difference" a bit more?

Sorry, yeah, this issue isn't doing a good job. I explicitly disagree with the original reporter that this is *lag*, because it's not. It's not a latency issue, and the mouse input delay seems fine. The issue I'm describing is about mouse *stutter*, or what I would call a lack of resolution.

I did some testing in MS Paint (now, that's a sentence that I did not see myself saying, ever), and there are two cases where this is very visible. The first case is on drawing lines. See this image:

![mouse](https://user-images.githubusercontent.com/344777/80245118-65280b80-866a-11ea-973e-49321cd53d11.png)

The first two lines are drawn with the mouse attached to the computer, the second two lines are drawn with the mouse streamed over Moonlight. I have two presets on my mouse to adjust the sensitivity so that both setups have a similar mouse movement on the table. The first lines show overall a smooth motion, while the mouse streamed over Moonlight sometimes keeps going in a straight line and then bumps up/down several pixels, resulting in a very jagged line.

The second test makes this even more noticeable. Take a look at the video at https://stuff.schub.wtf/tmp/cat_and_mouse.mp4 (the same is also attached to this comment as [cat_and_mouse.zip](https://github.com/moonlight-stream/moonlight-qt/files/4530832/cat_and_mouse.zip), but since GitHub doesn't allow attaching .mp4s, I figured this temporary hosted version is easier to access. Both contain the same video file.)

Here, I'm moving a picture of a cat quickly over the screen. Note that this is a screen recording made on the target computer, so the video you're seeing is not transferred over Moonlight at all. The first few swipes are made with the mouse attached to the computer, and you see reasonably smooth movement. You then see a short pause, which is me unplugging the mouse and plugging it into my Macbook, then doing cat swipes again. You'll see that the cat movement is much more... stuttery the second time. This is not an issue in recording setup or in sudden drop of framerate in Paint, this is mouse inputs being transferred stuttery.

I *assume* (I don't actually have any idea what Moonlight is doing internally) that this is a limit of the frequency mouse-positions are transferred, and it may not be a bug, but actually expected behavior. If that's the case, that's fine. However, I will note that this is very noticeable in, for example, first-person shooters, where doing a quick mouse swipe looks like you're having framedrops, when in fact, you don't, and it's just the mouse input that gets transferred with a lower frequency or whatever.

Hope this explanation allows you to understand what I'm talking about. :)

> Can you see if it's just one thread causing most of that CPU usage?

I actually have no idea on how I could convince Instruments to only show me threads of one application, and the default "activity monitor" instrument doesn't show threads. I ran another recording with the Activity Monitor and the Counters per thread, which may give you some insight. Here you are: [moonlight.trace.zip](https://github.com/moonlight-stream/moonlight-qt/files/4530926/moonlight.trace.zip)

---

Also, this is off-topic, but:

> the dev builds have it and that might be more suitable for your use case (toggle with Ctrl+Alt+Shift+M)

I just wanted to add that you just made me very happy.
