### ISSUE TITLE
Raspberry pi4 turning to "no signal" randomly

### ISSUE THREAD

**Issue by mrzever** [moonlight-stream/moonlight-qt#354]
Hey everybody ! I was looking for client stream for my computer, i ended up with a raspberry pi4 with moonlight installed following these steps : https://linustechtips.com/main/topic/1117242-moonlight-project-for-raspberry-pi-34/ 
i'm pretty new into raspbian but i think i've perfectly complete these steps.  

the problem is that randomly the pi turn to "no signal" (the stream session last max 30-45min) on the tv whenever i'm in game session or windows 10, everything except video is ok, audio and controls are still ok, if i switch geforce shield off on my host computer the pi stay on no signal and the only way to fix it is to power off the pi4, i've tried ctrl-alt-maj q but nothing seems happend

i'm launching moonlight via
moonlight stream -1080 
nothing else, streaming windows was one of the main goal when i was looking for client streaming that's why i don't try via -app
i've already update memory split to 200, nothing else for moonlight settings,

for the host computer, it's running win10 64 10.0 ver 18362
with a 970gtx driver 442.59 Geforce exp v 3.20.2.34 

and for the Pi 4 4go ram/raspbian buster, it's a fresh install so everything is up to date following the link in the beginning of the post
 
i don't really know how to create a logs, let me know if necessary 
thx you for reading my post ! good containment to you and take care !

**Comment by cgutman** [comment]
It looks like you're using the Moonlight Embedded client, rather than the Moonlight PC client. For that, you should report bugs here - https://github.com/irtimmer/moonlight-embedded/issues

But you could also try this Moonlight PC client which has early support for Raspberry Pi 4 using the steps here and see if the issue happens using that version too - https://github.com/moonlight-stream/moonlight-qt/issues/160#issuecomment-582768813
