### ISSUE TITLE
Version 2.0.0 does not work with IPv6 and OpenVPN.

### ISSUE THREAD

**Issue by magnww** [moonlight-stream/moonlight-qt#375]
**Describe the bug**
I use openvpn connect to PC. When I enable ipv6 in network adapter settings, moonlight can't connect to PC。
v1.2.1 does not have this problem.

**Steps to reproduce**
1.Enable IPv6 in network adapter settings, and connection status show IPv6 Internet.
2.Connect OpenVPN. 
3.Open moonlight, add PC manually, it says "Unable to Connenct to the specified PC".
4.Disable IPv6 in network adapter settings.
5.Repeat Step 3, it is working fine.

**Screenshots**
![2020-05-02 220017](https://user-images.githubusercontent.com/7497333/80866568-00039400-8cc2-11ea-8443-dc952fa89d22.png)

**Moonlight settings (please complete the following information)**
All default

**Client PC details (please complete the following information)**
 - OS: Windows 10 1903
 - Moonlight Version: 2.0.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 1909
 - GeForce Experience version: 3.20.3.63
 - Nvidia GPU driver: 445.87

**Moonlight Logs (please attach)**
[Moonlight-1588422803.log](https://github.com/moonlight-stream/moonlight-qt/files/4567898/Moonlight-1588422803.log)

**Comment by cgutman** [comment]
It appears the fix for https://bugreports.qt.io/browse/QTBUG-80947 did not fully address the underlying issue.

I've reintroduced the workaround for that bug in https://github.com/moonlight-stream/moonlight-qt/commit/c14404a7c1c16032023804b6045f0a369acc7681 and https://github.com/moonlight-stream/moonlight-qt/commit/f28a4df5eea20677a3944fe1bc7ae554c0a6210d

Here is a fixed build - 
https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/32604482/job/vpnadigsa1cqnstt/artifacts

If you choose to use the installer, you will need to manually uninstall the official 2.0.0 version first.
