### ISSUE TITLE
Client GPU selection

### ISSUE THREAD

**Issue by endyb66** [moonlight-stream/moonlight-qt#388]
My client notebook has an iGPU (Intel UHD Graphics 620) and a Nvidia GeForce MX150, which has more power and VRAM. So is it possible, that moonlight can use the "dedicated" GPU, or does it not matter?

**Comment by cgutman** [comment]
Generally the Intel GPU is plenty capable of decoding H.264 and HEVC, so you want the iGPU for best performance because it avoids a copy from dGPU VRAM to iGPU VRAM to display the video.

In addition, there are a number of Optimus-specific bugs which break various things Moonlight uses. This is why Moonlight blocks itself from using the dGPU on Optimus systems.
