### ISSUE TITLE
Unable to create opengl context on PC Alpha 2

### ISSUE THREAD

**Issue by jrizz43** [moonlight-stream/moonlight-qt#39]
I get "Unable to create opengl context" on any title I try to stream. Re-paired it with GeForce and did fresh install and restart of the moonlight pc client, still get the OpenGL error.

**Comment by cgutman** [comment]
Make sure you're not running the Chrome client by mistake. That "Unable to create OpenGL Context" error sounds like this bug from the Chrome client - https://github.com/moonlight-stream/moonlight-chrome/issues/273

This client doesn't use OpenGL for streaming on Windows, so it shouldn't be possible to see that dialog when streaming.

**Comment by jrizz43** [comment]
You're so smart. I thought I removed all old instances but windows was pulling up the chrome version.

**Comment by Jgr9** [comment]
I'm getting the OpenGL context error message when trying to launch the recent Windows version on my ancient laptop.  Even the portable version.  W10 32bit.

I had attempted the Chrome browser version previously, like before "Apps" was hidden, though I can still get to it.  It's not appearing there, but I still have the crx.  Is there something I need to still delete?  Because again, I'm getting this error with the current portable Windows version (and non-portable).
