### ISSUE TITLE
Add "respect aspect ratio" checkbox option

### ISSUE THREAD

**Issue by kshots** [moonlight-stream/moonlight-qt#396]
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be an option to maintain aspect ratio. In my (admittedly rather extreme case), I have a server running at 4k and a client running at 3440x1440 (16:9 vs 21:9). In this case, the client displays a downscaled 4k->3440x1440 stretched horizontally to fill the screen.

**Describe the solution you'd like**
A button to maintain the aspect the aspect ratio so the downscaled video has black bars on the appropriate sides to maintain the aspect ratio so things don't look horizontally or vertically stretched.

**Describe alternatives you've considered**
Allow the server to send a native stream to the client... appears to be out of the hands of the moonlight team? Can you convince GFE to send a 3440x1440 stream when the connected monitor doesn't support it? Or does the GFE only support what the server is connected to?

Other possibility is to remain in "windowed" mode at a standard (1080p, 720p, 1440p) resolution, but you won't come near your native client resolution that way with a significantly different aspect ratio. At least it would remain true while windowed.

**Additional context**
Attached is a screenshot of my desktop with a 4k->3440x1440 downscaling without maintaining aspect ratio (only possible option outside of windowing on my setup).
![Screenshot from 2020-05-25 03-43-07](https://user-images.githubusercontent.com/7032791/82790365-f0e3b200-9e39-11ea-9070-d87b64be0442.jpg)

**Comment by cgutman** [comment]
The stream you get from the host will always be encoded in the resolution you choose in Moonlight. Moonlight doesn't know what resolution your host display is truly in (and it can change during the stream). We always scale to fit while preserving aspect ratio, but only if the scaling is done on Moonlight's side.

If your host's display resolution doesn't match the stream's resolution, GFE scales the output to fill the encoded resolution. That means the encoded video has already been stretched from 4K to 3440x1440 by the time Moonlight receives it. There aren't any black bars added by Moonlight itself because the 3440x1440 stream matches the aspect ratio of your client's monitor.

If you want black bars (and don't want to change the host's resolution), pick a resolution in Moonlight that matches the aspect ratio that your host is using, like 1440p. The host will encode a 2560x1440 stream and Moonlight will pillarbox the video to fit your client monitor.

**Comment by kshots** [comment]
Using 1440p does indeed add the black bars I was looking for. It beats going to windowed mode, certainly.

It would be nice if I could somehow convince the host to go to a 21:9 AR, but the 4k host screen flat out doesn't support it... and adding it as a custom res via the nvidia control panel makes the system unresponsive and unbootable (have to go into safe mode to revert). That's probably outside the scope of moonlight, though (GFE should do that, and it doesn't (and probably never will)). Thanks for the pointer.
