### ISSUE TITLE
Moonlight works good on iPad but not on Mac

### ISSUE THREAD

**Issue by Rediixx** [moonlight-stream/moonlight-qt#414]
So like the title says, every time I use Moonlight on iPad the experience is really good at 1080p 60fps, no lag no stutters, but when I use it on my MPB Mid 2012 it lags every 10 seconds making it unplayable, the reason why I cant just use the iPad its because I don't have a wireless controller so I was wondering if I can do something on the Mac. I already disabled location services btw. And the network is the same for both the iPad and the MBP, 2.4Ghz on both (I don't have 5Ghz)

**Comment by ngmoviedo** [comment]
Does the Mac have h264 acceleration support? I had a similar issue with older macs, but if that's the case you should probably get a warning when opening Moonlight linking to this wiki article [https://github.com/moonlight-stream/moonlight-docs/wiki/Fixing-Hardware-Decoding-Problems](url)
It shouldn't necessarily mean that your hardware is not able of doing the decoding, just that Mac OS X doesn't support it. If that's your situation and that feature is locked by Apple, a "solution" that worked for me was switching to my GNU/Linux partition and installing Moonlight there. Any common distro will probably work for that.

**Comment by Caeous** [comment]
I've been having the same issue ever since version 2.0. Try the version before and see if that's better.

**Comment by cgutman** [comment]
I will need your logs to have any hope of figuring out what's going on.

On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.

**Comment by GreypaX** [comment]
`00:00:00 - SDL Info (0): Compiled with SDL 2.0.13
00:00:00 - SDL Info (0): Running with SDL 2.0.13
00:00:00 - Qt Warning: Populating font family aliases took 126 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:00 - SDL Info (0): V-sync enabled
00:00:00 - SDL Info (0): NSWindow on display: 42bd098
00:00:00 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] nal_unit_type: 7(SPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] nal_unit_type: 8(PPS), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] nal_unit_type: 5(IDR), nal_ref_idc: 3
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] Format videotoolbox_vld chosen by get_format().
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] Format videotoolbox_vld requires hwaccel initialisation.
00:00:00 - FFmpeg: [h264 @ 0x7fe990924600] Reinit context to 1280x720, pix_fmt: videotoolbox_vld
00:00:00 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "2.1.0"
00:00:01 - Qt Debug: Found update manifest match for current platform
00:00:01 - Qt Debug: Latest version of Moonlight for this platform is: "2.1.0"
00:00:01 - Qt Debug: Update manifest version equal to current version
00:00:02 - Qt Info: "REDPAXWORKPC" is now online at "91.205.8.2"
00:00:10 - Qt Info: Server GPU: "GeForce GTX 1070 Ti"
00:00:10 - Qt Info: Server GFE version: "3.20.3.63"
00:00:10 - SDL Info (0): Video bitrate: 70500 kbps
00:00:10 - SDL Info (0): Audio backend: CoreAudio
00:00:10 - SDL Info (0): Selected audio device: Встроенный выход
00:00:10 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:10 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:10 - SDL Info (0): Audio latency: 0.000000
00:00:10 - SDL Info (0): Audio channel count: 2
00:00:10 - SDL Info (0): Audio channel mask: 3
00:00:10 - SDL Info (0): V-sync enabled
00:00:10 - SDL Info (0): NSWindow on display: 42bd098
00:00:10 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Decoding VPS
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Main profile bitstream
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Decoding SPS
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Main profile bitstream
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Decoding VUI
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Decoding PPS
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Format videotoolbox_vld chosen by get_format().
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Format videotoolbox_vld requires hwaccel initialisation.
00:00:10 - FFmpeg: [hevc @ 0x7fe991822000] Output frame with POC 3.
00:00:10 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:10 - SDL Info (0): Audio backend: CoreAudio
00:00:10 - SDL Info (0): Selected audio device: Встроенный выход
00:00:10 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:10 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:11 - SDL Info (0): Audio latency: 0.000000
00:00:11 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:11 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:11 - SDL Info (0): V-sync enabled
00:00:11 - SDL Info (0): NSWindow on display: 42bd098
00:00:11 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Decoding VPS
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Main profile bitstream
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Decoding SPS
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Main profile bitstream
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Decoding VUI
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Decoding PPS
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Format videotoolbox_vld chosen by get_format().
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Format videotoolbox_vld requires hwaccel initialisation.
00:00:11 - FFmpeg: [hevc @ 0x7fe991822000] Output frame with POC 3.
00:00:11 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:12 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:00:12 - SDL Info (0): Loaded 31 new gamepad mappings
00:00:12 - SDL Info (0): Found host supported resolution: 1920x1080
00:00:12 - Qt Info: Executing request: "https://91.205.8.2:47984/launch?uniqueid=0123456789ABCDEF&uuid=2665d6829ec149b49e7efb84a7b84c13&appid=2007242538&mode=1920x1080x60&additionalStates=1&sops=1&rikey=8b81e3e760a9e5dbf84fb22a6cbae18f&rikeyid=254520438&localAudioPlayMode=0&surroundAudioInfo=196610&remoteControllersBitmap=0&gcmap=0"
00:00:16 - Qt Info: Found matching interface: "en0" "38:F9:D3:0F:3E:B2" QFlags<QNetworkInterface::InterfaceFlag>(IsUp|IsRunning|CanBroadcast|CanMulticast)
00:00:16 - Qt Info: Interface Type: QNetworkInterface::Ethernet
00:00:16 - Qt Info: Interface MTU: 1500
00:00:16 - SDL Info (0): Initializing platform...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Resolving host name...
00:00:16 - SDL Info (0): done
00:00:16 - SDL Info (0): Packet size capped at 1KB for remote streaming
00:00:16 - SDL Info (0): Starting RTSP handshake...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Initializing control stream...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Initializing video stream...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Initializing audio stream...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Initializing input stream...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Starting control stream...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Starting video stream...
00:00:27 - SDL Info (0): Video stream is 1920x1080x60 (format 0x100)
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Starting audio stream...
00:00:27 - SDL Info (0): Audio backend: CoreAudio
00:00:27 - SDL Info (0): Selected audio device: Встроенный выход
00:00:27 - SDL Info (0): Native layout: Stereo (2 channels)
00:00:27 - SDL Info (0): Audio buffer size: 0.030000 seconds
00:00:27 - SDL Info (0): Audio stream has 2 channels
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Starting input stream...
00:00:27 - SDL Info (0): done
00:00:27 - SDL Info (0): Qt UI screen is at (0,0)
00:00:27 - SDL Info (0): SDL found matching display 0
00:00:27 - SDL Info (0): Received first audio packet after 100 ms
00:00:28 - SDL Info (0): Received first video packet after 900 ms
00:00:28 - SDL Info (0): Recreating renderer for window event: 1 (0 0)
00:00:28 - SDL Info (0): V-sync enabled
00:00:28 - SDL Info (0): NSWindow on display: 42bd098
00:00:28 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Decoding VPS
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Main profile bitstream
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Decoding SPS
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Main profile bitstream
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Decoding VUI
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Decoding PPS
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Format videotoolbox_vld chosen by get_format().
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Format videotoolbox_vld requires hwaccel initialisation.
00:00:28 - FFmpeg: [hevc @ 0x7fe990947400] Output frame with POC 3.
00:00:28 - SDL Info (0): NSWindow on display: 42bd098
00:00:28 - SDL Info (0): Frame pacing disabled: target 60 Hz with 60 FPS stream
00:00:28 - SDL Info (0): Using VideoToolbox accelerated renderer
00:00:28 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:28 - SDL Info (0): Requesting IDR frame on behalf of DR
00:00:28 - SDL Info (0): IDR frame request sent
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Decoding VPS
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Main profile bitstream
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Decoding SPS
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Main profile bitstream
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Decoding VUI
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Decoding PPS
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Format videotoolbox_vld chosen by get_format().
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Format videotoolbox_vld requires hwaccel initialisation.
00:00:28 - FFmpeg: [hevc @ 0x7fe992064600] Output frame with POC 14.
00:01:36 - SDL Info (0): Returning RTP packet queued for too long
00:01:36 - SDL Info (0): Received OOS audio data (expected 13714, but got 13716)
00:04:09 - SDL Info (0): Detected quit key combo (SDLK)
00:04:09 - SDL Info (0): Quit event received
00:04:09 - SDL Info (0): Raising 3 keys
00:04:09 - SDL Info (0): Global video stats
00:04:09 - SDL Info (0): ----------------------------------------------------------
Estimated host PC frame rate: 60.00 FPS
Incoming frame rate from network: 60.00 FPS
Decoding frame rate: 60.00 FPS
Rendering frame rate: 59.88 FPS
Frames dropped by your network connection: 0.00%
Frames dropped due to network jitter: 0.20%
Average receive time: 1.55 ms
Average decoding time: 2.53 ms
Average frame queue delay: 0.41 ms
Average rendering time (including monitor V-sync latency): 10.49 ms
00:04:09 - SDL Info (0): Stopping input stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Stopping audio stream...
00:04:09 - SDL Info (0): ENet wait interrupted
00:04:09 - SDL Info (0): Control stream connection failed: -1
00:04:09 - Qt Info: Found "gamecontrollerdb.txt" at ":/data/gamecontrollerdb.txt"
00:04:09 - SDL Info (0): Loaded 31 new gamepad mappings
00:04:09 - SDL Info (0): Audio latency: 0.000000
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Stopping video stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Stopping control stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Cleaning up input stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Cleaning up audio stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Cleaning up video stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Cleaning up control stream...
00:04:09 - SDL Info (0): done
00:04:09 - SDL Info (0): Cleaning up platform...
00:04:09 - SDL Info (0): done
00:04:11 - Qt Info: Executing request: "https://91.205.8.2:47984/cancel?uniqueid=0123456789ABCDEF&uuid=44e62938309c4a5f8f9a8c090b7a0263"
00:04:14 - Qt Warning: Aborting timed out request for "https://91.205.8.2:47984/cancel?uniqueid=0123456789ABCDEF&uuid=44e62938309c4a5f8f9a8c090b7a0263"
00:04:14 - Qt Warning: "cancel"  request failed with error  QNetworkReply::OperationCanceledError
`

**Comment by PolCPP** [comment]
Had the same issue, on a 16inch mbp. Been poking around the code but seems out of my league, in case it helps, actually ended installing bootcamp, moonlight and ran some logs against the same machine on both systems.

https://gist.github.com/PolCPP/8e29276b3a3eefc7ea28587be8d654fb

It feels like some microstutters, on windows it feels super smooth, on osx doesn't feel as much. Tried recording regular/slow mo video but you can't seem to discern it on there.

**Comment by GreypaX** [comment]
problem is exist
