### ISSUE TITLE
Starting Netflix on the Host computer kicks you out and doesn't let you reconnect

### ISSUE THREAD

**Issue by Nerucius** [moonlight-stream/moonlight-qt#441]
**Describe the bug**
Upon connecting to the host using the mstsc.exe, starting Netflix and playing a movie, the stream was interrupted. The computer can still be connected to and the list of games show. But a video stream can't be established.

**Steps to reproduce**
1. Connect using mstsc.exe
1. Start Netflix
1. Play any video
1. Stream ends

**Affected games**
Remote desktop -> Start netflix

**Other Moonlight clients**
I haven't tested it

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? If so, which settings have been changed?
  1080p, 60fps, 60mbps. Haven't had any trouble unitl now.
- Does the problem still occur after reverting settings back to default?
  Yes

**Client PC details (please complete the following information)**
 - OS: Windows 10 Home 10.0.18362 Build 18362
 - Moonlight Client Version: v2.2.0

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro
 - GFE version: "3.20.4.14"
 - Nvidia GPU driver: Latest stable

**Moonlight Logs (please attach)**
[Moonlight-1599816686.log](https://github.com/moonlight-stream/moonlight-qt/files/5208075/Moonlight-1599816686.log)
Relevant lines are:
```
00:00:22 - SDL Info (0): Stopping video stream...
00:00:22 - SDL Info (0): No video traffic was ever received from the host!
00:00:22 - SDL Info (0): done
```

**Additional context**
Had no issues with streaming any other app / game / remote desktop.

**Comment by cgutman** [comment]
This is because of the DRM copy protection on the Netflix video content. You will see something like this in your NvStreamerCurrrent.log on your host:
```
#0(W)[2020-09-06 03:33:50,776]=23:33:50={15144}<Fbc7FrameProvide> Capture failure, reported capture resolution is 0 x 0 pitch 0. Writing a black frame.
#1(I)[2020-09-06 03:33:50,776]=23:33:50={15144}<Fbc7FrameProvide> Capture resolution is now 1280 x 720 pitch 0.
#2(W)[2020-09-06 03:33:50,776]=23:33:50={15144}<Fbc7FrameProvide> Failed to grab frame as it is protected content.
#3(E)[2020-09-06 03:33:50,776]=23:33:50={15144}<Fbc7FrameProvide> Failed to grab frame: -4 (NVFBC_ERROR_PROTECTED_CONTENT).
#4(E)[2020-09-06 03:33:50,776]=23:33:50={15144}<CaptureThread>    Failed to capture frame 0.
```
```
#6(I)[2020-09-06 03:33:51,374]=23:33:51={13180}<StopEvent>        Termination infos:
#7(I)[2020-09-06 03:33:51,374]=23:33:51={13180}<StopEvent>        - Source 'CaptureThread', reason 'Failed to capture frame', code 0x800E9302 NVST_DISCONN_SERVER_VFP_PROTECTED_CONTENT
```

I believe this is a relatively recent thing though. You could try downgrading your Nvidia drivers to 446.xx to see if it's the newer drivers doing it. Folks on our [Discord server](https://moonlight-stream.org/discord) may be able to help you find a workaround (assuming you're not intending to circumvent the DRM for the purposes of actually copying the content).

In any case, this is basically working as intended. Streaming DRM protected content should never have been allowed, and the fact that it worked was a bug on Nvidia's side that has apparently been fixed.
