### ISSUE TITLE
build problem on raspberry pi

### ISSUE THREAD

**Issue by watchha** [moonlight-stream/moonlight-qt#449]
when you build the application on a raspberry pi the rendering is not done with MMAL but with SDL render how can change it? SDL render makes a green screen

**Comment by cgutman** [comment]
Building for Raspberry Pi is tricky because we need newer versions of many of the library than Debian Buster provides. You also need to build FFmpeg with MMAL support, which may be what is missing in your case.

I have a repo with scripts and Dockerfiles for building L4T and RPi packages that might be helpful. https://github.com/cgutman/moonlight-packaging

**Comment by watchha** [comment]
it solved my problem thx
