### ISSUE TITLE
pressing S only shows single / ignored multiple key press?

### ISSUE THREAD

**Issue by gittyup2018** [moonlight-stream/moonlight-qt#462]
I don't know if the key is not being sent, being ignored, etc. but when I press any key in notepad I only see it once and I immediately get a onpressed and on released events while the key is still being held  down.

Example: If I open Notepad and press S  and hold it down for a few seconds, I will only see a single "S" character, not sssss as expected.

This was on ubuntu 20.04 fresh install from version 2.0.0 to the newest, the last working version that shows "ssss" correctly was 1.2.1 which I also tested on the same computer / same geforce version (4.50), etc. so I am certain it is version 2.0.0+ clients. 

This was tested on flatpak's versions 0.80 - 2.20 and snap version 2.20 (I could not figure out how to use old commit's on snap)

Also, I noticed after 1.2.1 the raw input mouse was removed/renamed? please add that back if so I really need that feature

Commits I tested
Moonlight 2.0.0 - 7e142e1d1b26e6b6a0f434004e7f01fb81f09a3db9d07e5135f82

Last working sss (and raw mouse input) 1.2.1 commit b05241612059b60f610b0b19a720dad6a63510d6333dc47352e567f0ead7b268

Also in 1.2.1 I really like being able to click the mouse when I need to  capture it - as I use synergy and sometimes only need the video streaming feature and not the mouse or keyboard) and noticed newer versions capture the cursor automatically

**Comment by gittyup2018** [comment]
Thanks for quick reply and I don't know what GFE version, but I'm using the newest GFE driver 4.56 released  a few days ago

You mean raw mouse input was renamed to "optimize mouse for remote desktop instead of games" ? because the tooltip just says NOT to use it for games and I use raw mouse for the speed, specifically with a trackpad as if I don't enable it the mouse cursor is very slow but with raw it uses the same speed/settings as my "normal" mouse settings. The tooltip doesn't mention any of that?
 
is there a changelog of the names/features? 

and what is gamepad mouse support? the tooltip "when enabled holding the Start button will toggle mouse mode" - what mouse mode? does that mean it will only be activated when holding down the start or you can switch between gamepad mouse and non-gamepad?  these tooltips really need better documentation, I can help if I can figure out what they are :)

**Comment by cgutman** [comment]
> Thanks for quick reply and I don't know what GFE version, but I'm using the newest GFE driver 4.56 released  a few days ago

Please check your GeForce Experience version. The driver version is not relevant here.

> 
> You mean raw mouse input was renamed to "optimize mouse for remote desktop instead of games" ? because the tooltip just says NOT to use it for games and I use raw mouse for the speed, specifically with a trackpad as if I don't enable it the mouse cursor is very slow but with raw it uses the same speed/settings as my "normal" mouse settings. The tooltip doesn't mention any of that?
>  

The toggle simply switches between relative (unchecked) and absolute (checked) mouse control. The pros and cons of these methods is rather complex, which is why the toggle simply boils it down to "remote desktop" vs "games". You can probably find resources on the internet that can explain this in depth.

Raw mouse mode is the opposite of remote desktop mouse mode. "Raw" refers to the fact that the mouse motion deltas are not manipulated by the OS prior to being processed by the application. By definition, absolute mouse motion cannot be raw because the cursor itself is maintained by the OS.

> is there a changelog of the names/features? 

https://github.com/moonlight-stream/moonlight-qt/releases/

> and what is gamepad mouse support? the tooltip "when enabled holding the Start button will toggle mouse mode" -what mouse mode?

Gamepad mouse mode, as in using your gamepad as a mouse.

> does that mean it will only be activated when holding down the start or you can switch between gamepad mouse and non-gamepad?

Yes, you can switch between modes that's why the tooltip uses the word "toggle"

> these tooltips really need better documentation, I can help if I can figure out what they are :)

The tooltips simply aren't meant to explain everything in details. We don't have the space for that. But if you have some concise language that is more clear than what we've got, I'm all ears.

> I noticed some other weird errors like when I press left shift, I see both left and right shift events..this could just be my computer setup as I'm using it in a VM and the alt/shift keys could be weird, so if the ssss thing works for you and raw mouse is then maybe it's a bug with my setup or something on my side and not your client. I will test it in a non-VM setting and open another/real bug report if it is.  

Duplicate left and right key events was fixed in [Moonlight v2.2](https://github.com/moonlight-stream/moonlight-qt/releases/tag/v2.2.0). Are you sure you're up to date?
