### ISSUE TITLE
Render cursor locally to reduce apparent input latency (in Remote Desktop)

### ISSUE THREAD

**Issue by mmeyer724** [moonlight-stream/moonlight-qt#465]
**Is your feature request related to a problem? Please describe.**
While using moonlight for Remote Desktop I've noticed my cursor has a (very) small delay to it. It's subtle, but it's enough to remind me that I'm in fact not using a local desktop. 

This doesn't bother me for the video stream itself, but for things like input devices I think humans are very well tuned to pick out even the tiniest amounts of latency. Especially with a desktop cursor because your movements need to be very accurate to hit the small touch targets (buttons etc). 

**Describe the solution you'd like**
I believe the problem is due to the cursor being rendered on the host side (correct me if I'm wrong here?) which means the cursor is slightly delayed, just like the rest of the video stream. I'm wondering if it would be possible to hide the cursor on the host and instead render a 'fake' cursor on the client side (like RDP does).

This would mask over the latency and make your cursor feel 'real time'. 

**Describe alternatives you've considered**
None

**Additional context**
None

P.S. If this is technically possible with GameStream I'd be happy to help pitch in code for it

**Comment by cgutman** [comment]
Unfortunately, it's not technically possible. I've seen indications that Nvidia may be working on client-side cursor rendering support in the protocol, but it does not exist today.

**Comment by Smoovsky** [comment]
It's now possible with Sunshine as the server.

[Wiki Moonlight](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide)
Ctrl+Alt+Shift+C - Toggle local cursor display in remote desktop mouse mode (remote cursor will always show up due to GameStream limitations)

[Doc Sunshine](https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/usage.html#shortcutshttps://docs.lizardbyte.dev/projects/sunshine/en/latest/about/usage.html#shortcuts)
CTRL + ALT + SHIFT + N - Hide/Unhide the cursor (This may be useful for Remote Desktop Mode for Moonlight)CTRL + ALT + SHIFT + N - Hide/Unhide the cursor (This may be useful for Remote Desktop Mode for Moonlight)

But the client is still not able to synchronize the cursor status(shape), meaning you will always see an arrow instead of pointer(hand)/progress(busy) etc.

I reckon moonlight will need to work with sunshine to achieve syncing cursor status, roughly thinking it's not something hard to implement as parsec is obviously doing such.
