### ISSUE TITLE
Add option for 10-foot UI

### ISSUE THREAD

**Issue by Nerdy314159265** [moonlight-stream/moonlight-qt#466]
**Is your feature request related to a problem? Please describe.**
When used on devices connected to a TV at a distance it can be very difficult to navigate any options menus and select your game.

**Describe the solution you'd like**
I'd like to see the addition of a UI similar to Steam Big Picture or Kodi.
It could start on the game selection screen with larger tiles similar to the Library in Big Picture or some of the views in Kodi.
Option menus would scale larger so that text is readable from long distances.

**Describe alternatives you've considered**
I don't think there are any alternatives that could be considered on a permanent basis.
A temporary solution would be allowing users to set scaling for the icons and text until it's readable.

**Comment by cgutman** [comment]
Is your main issue with the settings page? 

IMHO, the PC and app grids are fine 10-foot UIs. The box art is large with edge to edge content, and the text is easily readable.

**Comment by Nerdy314159265** [comment]
I'd probably describe them more as tolerable than fine. I personally think
they should be larger as if you have titles that lack, have generic or
cluttered cover art, then it'll still be difficult to distinguish at a
distance.

**Comment by cgutman** [comment]
Can you provide more platform details (display, desktop resolution, and OS)? Maybe you're just seeing poor High DPI scaling behavior with Qt. The box art really is quite large on my TV.

We are also limited because the box art that GFE has is only 300x400, so there's not much larger we can make it.

**Comment by Nerdy314159265** [comment]
65 inch display
standard 4k
Raspberry Pi 4 running RetroPie

**Comment by cgutman** [comment]
ok, you're not running in a desktop environment, so it's likely that it is a scaling issue. I believe Qt takes hints from X11/Wayland to set scaling.

You may need to manually set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT variables. https://doc.qt.io/qt-5/embedded-linux.html states:
>Specifies the physical screen's width and height in millimeters. On platforms where the value can't be queried from the framebuffer device /dev/fb0 or via other means, a default DPI of 100 is used. Use this variable to override any such defaults. Setting this variable is important because QWidget- or Qt Quick Controls-based applications rely on these values. Running these applications with the hard-coded settings may result in user interface elements with sizes that are unsuitable for the display in use.

**Comment by Nerdy314159265** [comment]
A partial solution would be to add a DPI scaling setting to the settings menu that configures the needed variables.

**Comment by cgutman** [comment]
I don't think that really makes sense for an option that only applies to a tiny minority of configurations. Remember, these are set correctly out of the box based on OS APIs on Windows, Mac, X11, and Wayland. The _only_ scenario where you must set them manually is on Linux without a desktop environment running _and_ where Qt can't successfully query them from your display (or they are wrong).

I really think environment variables are the correct way to manage this. You set it once in your .bashrc or whatever then it works for all Qt-based apps. RetroPie itself could even set them since it probably has better knowledge of your display configuration based on your settings.

Did setting the environment variables correctly give you the scaling you wanted?

**Comment by Nerdy314159265** [comment]
Setting the environment variable did not give me the scaling that I wanted.
Even when added directly to /etc/environment the variables had no noticeable effect.

I don't believe this is that niche of an idea. I would expect many people would use moonlight to stream from their main PC to client devices connected to things like TVs. If so, many of them are going to be running distros built around a streamlined TV interface. So having a streamlined TV interface within Moonlight would be desirable for that group.

**Comment by jletizia** [comment]
@Nerdy314159265 can you post a picture / screenshot of what you are seeing? I'm streaming from a Linux mean to a PC, and it scales just fine

**Comment by Nerdy314159265** [comment]
> @Nerdy314159265 can you post a picture / screenshot of what you are seeing? I'm streaming from a Linux mean to a PC, and it scales just fine

I'm not referring to the stream. I'm referring to the UI the program itself.

**Comment by jmt-gh** [comment]
@Nerdy314159265 , I was talking about the UI of Moonlight as well. When displayed on my monitor (before I start a stream), it scales as expected and is visible. A screenshot of what you are seeing would help tremendously

**Comment by walterpalagi** [comment]
Hi @jmt-gh and @cgutman, I'm attaching pictures to show this issue. It's happening on a raspberry pi 4, it's running Libreelec and moonlight-qt runs outside of X11 or Wayland. The binary is extracted from a docker image and works flawlessly except for the font size.

Please be advised that my test is currently tainted by an almost certainly unrelated bug: the wrong font is picked, it's one of those "artistic" fonts that shouldn't exist. I'll need a couple of days to rebuild a new system on a different drive so that I can perform a proper untainted test.

My TV is a Sony Bravia A80J, 4k, 65", which is about a meter and a half wide. 

I exported both variables in the script that ultimately launches moonlight. As explained in the documentation:

QT_QPA_EGLFS_PHYSICAL_WIDTH and height: millimeters

QT_QPA_EGLFS_WIDTH and height: pixels

The UI fails to react in any way to those variables. I tried setting the physical size ones, then the pixel size ones, and then all of them rebooting every time.

Silly font:
![silly font](https://i.imgur.com/HItB4Hs.jpg)

Wrong font size in settings:
![Wrong font size in settings](https://i.imgur.com/G7IPzcV.jpg)

This second picture is still a good illustration of the bug. Even when the font itself was OK, the size was this small. You do have to put your face right up to the screen to read it.

If you have any advice while I build the second system I'll be happy to incorporate it in my tests.

Thanks!

**Comment by Nerdy314159265** [comment]
This and the covers being too small were the issues I had. Great shots showing the issue.

I would've taken some but I went through some setup changes at the time and my Raspberry Pi got moved to a different job.

**Comment by walterpalagi** [comment]
OK, so: fresh Raspberry Pi OS on a pi 4. moonlight-qt running as root with the following variables set:

```
export QT_QPA_EGLFS_PHYSICAL_WIDTH=1450
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=835
```

Those are the size of my tv in mm.

Servers:
![Servers](https://i.imgur.com/6NnbkKh.jpg)

Games:
![Games](https://i.imgur.com/bWDBDWV.jpg)

Settings:
![Settings](https://i.imgur.com/YMr0fHz.jpg)

And of course the fonts are OK now:
![Font is OK](https://i.imgur.com/5z3w321.jpg)

I will now try setting all kinds of values, including QT_QPA_EGLFS_WIDTH and QT_QPA_EGLFS_HEIGHT, and see what happens.

**Comment by walterpalagi** [comment]
Setting these values:

```
export QT_QPA_EGLFS_WIDTH=3840
export QT_QPA_EGLFS_HEIGHT=2160

export QT_QPA_EGLFS_PHYSICAL_WIDTH=400
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=225

/usr/bin/moonlight-qt
```
...makes the fonts quite bigger:

![](https://i.imgur.com/DAPkNdj.jpg)

But the game covers and the other UI elements remain at the same size. I'm confused. Setting a lower physical size shouldn't give me bigger fonts, right??

**Comment by walterpalagi** [comment]
Setting different resolutions with QT_QPA_EGLFS_WIDTH and HEIGHT makes no difference.

I'm done until someone tells me how to try something new :(

**Comment by cgutman** [comment]
Try QT_SCALE_FACTOR.

https://www.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6

**Comment by walterpalagi** [comment]
Looks like we're onto something now!

With QT_SCALE_FACTOR=1.8 and no other variables set, the settings are spread over the whole screen. Bigger factors will make them overflow beyond the bottom and they will not be visible (there seems to be no scrollbar).

However, the bar at the top becomes black and so large that it covers the top of the UI!!! That happens throughout the whole UI.

![](https://i.imgur.com/87FRYad.jpg)

![](https://i.imgur.com/lnIIqsA.jpg)

Thanks

**Comment by walterpalagi** [comment]
@cgutman more attempts at setting and unsettling variables didn't produce a correct UI. I suggest this bug should be re-opened, even if it's probably a low priority one. If you need me to do additional tests I'll be happy to. Thanks for everything so far.

**Comment by MopheusDG** [comment]
Same here. How do we SAVE at least the QT settings to get persistence ?

By the way, the app is AMAZING, I really really love you all.
