### ISSUE TITLE
moonlight won't show all games

### ISSUE THREAD

**Issue by Shiroe93** [moonlight-stream/moonlight-qt#472]
hello i have been experiencing a strange issue lately 
geforce experience and nvidia game streaming on shield show me 4 games but moonlight only shows me one both from android and other pc
![Screenshot_189](https://user-images.githubusercontent.com/56954468/99425703-7d5fc080-2903-11eb-9158-9bb3abffe0fa.png)

**Comment by cgutman** [comment]
This is by design. Nvidia GameStream only shows GameStream-tested games by default, even if GFE has optimal playable settings for other games.

You can add any game you want manually - https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#adding-custom-programs-that-are-not-automatically-found

**Comment by Shiroe93** [comment]
But on my shield TV all my games are showing up only moonlight doesn't show them

**Comment by cgutman** [comment]
They are probably showing up as GeForce Now games. Can you actually launch them on your PC using the Shield UI?

**Comment by Shiroe93** [comment]
No I can assure you it starts a connection with my pc because before the games open I can clearly see my desktop
I know the difference between ge force now and nvidia gamesteeam

**Comment by cgutman** [comment]
If you didn't hide them in Moonlight, they almost certainly aren't present in the applist XML response from GFE. Note that the official Shield client communicates with GFE using a different protocol that operates through Nvidia servers, so it's possible that it is returning additional games that way (though it's never been seen before).

It's also possible that there's an XML parsing bug in Moonlight but I highly doubt that is the case because:
- it impacts 2 different clients that have totally different XML parsers
- the XML parsing code in Android has basically been the same for 6 years
- there's never been an XML parsing bug in any client that would lead to games disappearing

Do the games show up in Moonlight if you add them manually in GFE?

Can you post some screenshots of the Shield client showing your game library on SHIROE-PC?

**Comment by Shiroe93** [comment]
At the moment my TV is occupied and I can't verify what your asking I will try as soon as possible though
In the meantime thank you for answering me

**Comment by cgutman** [comment]
I tried on my Shield Android TV and I cannot confirm the behavior you're reporting.

I followed these steps:
- Open the NVIDIA Games app
- Selected the "My Library" tab
- Scrolled right to the "View My Library" tile and opened that

The game list I see is the exact same as what Moonlight has, despite my library containing name games that aren't officially GameStream-tested.
