### ISSUE TITLE
Having Error While Building Moonlight-qt project 

### ISSUE THREAD

**Issue by S4nfs** [moonlight-stream/moonlight-qt#478]

**Comment by cgutman** [comment]
It looks like you're trying to build with the MinGW toolchain which is not supported. When you install Qt, you need to select a version of Qt 5.15 with the MSVC 2019 toolchain to build successfully.

**Comment by S4nfs** [comment]
Thanks for the reply Dev. I'll try with the MSVC compiler and hope it'll solve the problem.

**Comment by S4nfs** [comment]
Will you explain the build process more briefly as now i am having problem while building, debugging with x86 works fine ..i am now using MSVC compiler as you mention earlier and it compiles without any error

I want to build for both x86 and x64 bit
![Screenshot (5)](https://user-images.githubusercontent.com/75138345/100640932-ec560400-335c-11eb-9ec7-27815a125140.png)

**Comment by S4nfs** [comment]
Also with the other method:

![Screenshot (10)](https://user-images.githubusercontent.com/75138345/100645474-bae03700-3362-11eb-964f-3eed881bd6f0.png)


![Screenshot (11)](https://user-images.githubusercontent.com/75138345/100645476-bb78cd80-3362-11eb-8acb-6f7af79439d4.png)

Executing Moonlight.exe
![Screenshot (9)](https://user-images.githubusercontent.com/75138345/100645472-b9af0a00-3362-11eb-854a-97ecc3bbc637.png)

**Comment by cgutman** [comment]
That's because your DLL search path isn't including the `libs` folder at the root of the repo. If you build from the Qt Creator IDE, it takes care of all this for you. I recommend trying that.

**Comment by S4nfs** [comment]
I had the same error while building the project both from QT and from cmd. 

Am i missing something ? I am using QT 5.15.0 with MSVC 2015 64bit kit

**Comment by S4nfs** [comment]
While Building on QT it showing the following errors 

![Screenshot (13)](https://user-images.githubusercontent.com/75138345/100871096-b2ecd800-34c5-11eb-8138-cba79357f935.png)



Is there anything after the build process as my release project won't showing folders with dlls inside

![Screenshot (14)](https://user-images.githubusercontent.com/75138345/100871297-0eb76100-34c6-11eb-9e48-687400266b35.png)

**Comment by cgutman** [comment]
Neither of those messages in your Qt Creator screenshot would have prevented the build from completing. They're just warnings. What happens when you actually try to run Moonlight from within Qt Creator?

If you _really_ want a command-line or redistributable build, you can use the `generate-arch.bat` script that is referenced in the readme. But I would really advise against it, especially given that the (simpler) Qt Creator build doesn't even work for you yet.

**Comment by S4nfs** [comment]
I build the Android project (Moonlight) within few hours but this one taking so much time.. i am sure there's some misconfiguration with the path or kits while installing, although i reinstalled QT several times.

Here is what am i doing while building with QT 
https://drive.google.com/file/d/112i3jYm_mhhWl95yK5Wp5lQok3vnmGMe/view?usp=sharing

**Comment by cgutman** [comment]
Moonlight compiled and ran correctly when you started it from Qt Creator, exactly as it's supposed to.

As I mentioned before, you can't simply click on the Moonlight.exe in the output directory, because not all the DLLs and other dependencies are deployed to that location. Qt Creator fixes up the DLL search path when it runs Moonlight.exe, so it can find the appropriate Qt DLLs and other dependencies.

Can you explain what your goal is? If you're just trying to make some basic local changes and/or submit a PR, you should just build and run from Qt Creator. Only if you're trying to build redistributable binary packages would you need to use `generate-arch.bat` and `generate-bundle.bat`.

**Comment by S4nfs** [comment]
I want to build a complete package with some customization on GUI and controller.

**Comment by cgutman** [comment]
Ok, in that case you'll need to use the scripts then.

Make sure you have everything installed from https://github.com/moonlight-stream/moonlight-qt#windows-build-requirements and then do the steps from https://github.com/moonlight-stream/moonlight-qt#build-setup-steps

When you run your x86 build, make sure you run `scripts\generate-arch.bat Release x86` from the Qt 5.15 x86 command prompt, and run `scripts\generate-arch.bat Release x64` from the Qt 5.15 x64 command prompt.

For installers, you'll need to run `scripts\generate-bundle.bat Release` from the Qt 5.15 x86 command prompt, and don't forget to make sure WiX and 7-zip tools are in your path.

**Comment by S4nfs** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/75138345/101392420-c47e1780-38eb-11eb-8717-20910e3c59fd.png)

**Comment by cgutman** [comment]
The readme states (emphasis mine):
> For Windows builds, use scripts\build-arch.bat and scripts\generate-bundle.bat. **Execute these scripts from the root of the repository within a Qt command prompt.** Ensure WiX and 7-Zip binary directories are in your %PATH%.

They can't find the project file because you're not running them from the root of the repo.

**Comment by S4nfs** [comment]
Ok finally i was able to generate the portable build version (sorry i was running the .bat inside the script path)
![Screenshot (20)](https://user-images.githubusercontent.com/75138345/101486442-aa434880-3982-11eb-8d1e-be66585dbdad.png)


Error while generating bundle: 
[ Already configures the WiX and 7-Zip %PATH% but I will use inno for generating the executable file]

C:\moonlight-qt>scripts\generate-bundle.bat Release x86
**Unable to build bundle - missing binaries for release x86
You must run 'build-arch.bat release x86' first**

**Comment by S4nfs** [comment]
How do i create custom themes for Moonlight using QT, there are no .gui files in the project ?

**Comment by cgutman** [comment]
I don't know. I don't use Qt Designer. I just write the QML files manually.

You can use the prebuilt Qt Quick Controls 2 styles and the environment variables to control them - https://doc.qt.io/qt-5/qtquickcontrols2-styles.html

Moonlight sets these variables in main.cpp.

**Comment by S4nfs** [comment]
I choose Universal Theme (Dark) for my

**Comment by S4nfs** [comment]
I changed the Application name in the target variable but its showing error:1327 [failure during running mt.exe] while building.

unix:!macx {
    TARGET = nstreamer
} else {
    # On macOS, this is the name displayed in the global menu bar
    TARGET = Nstreamer
}

**Comment by cgutman** [comment]
> Will you recommend some guidance stuff related with Moonlight working, I want to know how it works how it captures and uses Nvstream to send the packets from host to client. Also i want to fix bugs related with mouse acceleration while on RDP mode.

The GameStream protocol is not formally documented by NVIDIA. The reference implementation of a client is Moonlight itself. To understand it, I encourage you to read the code (especially moonlight-common-c) and step through it in a debugger if that helps.

> I changed the Application name in the target variable but its showing error:1327 [failure during running mt.exe] while building.

Sounds like you've probably got stale build output and you need to clean and rebuild.

> Also how do i build the Moonlight hosting tool.exe there's nothing said about this in Doc.

It's very easy, just open mish.sln in VS 2019 and build for Win32.

Since your original issue is solved, I'm closing this bug now as it's gone way off-topic. Keep in mind that I can't provide individualized help for your particular build problems/customizations/issues. Many of your questions can be answered with existing Qt documentation (like the stuff I pointed to you to earlier), Stack Overflow posts, Googling, or just splunking around a bit in the code/scripts/etc in the repos. If you still have questions, you can join our [Discord server](https://moonlight-stream.org/discord) and ask in the development channel (though really searching the Internet will probably be faster).

**Comment by S4nfs** [comment]
One last thing i forgot to discuss that i change the Material theme to Universal but now it won't display my server in my main panel. There's nothing there. I changed the variables again to Material and it fixes the issue but  I want to add the Universal theme. How can it be possible?
