### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by Bauzival** [moonlight-stream/moonlight-qt#481]
Hi

First of all, I would like to thank for this awesome software.

I use Moonlight to stream the desktop using "mstsc.exe". Now I wonder if there's a way to auto-login into windows e.g. using some command line parameters?

**Comment by igno2k** [comment]
You should be able to setup this in Windows settings. Check this:
https://www.lifewire.com/how-do-i-auto-login-to-windows-2626066

**Comment by Bauzival** [comment]
Thanks. For security reasons I'd prefer an auto-login option that submits credentials from the client machine (like e.g. Splashtop does). The method from your link is more like disabling user authentication.

**Comment by cgutman** [comment]
Handling plaintext credentials is very tricky. Command-line options aren't a good option because that credential will sit in memory (and can even be viewed without any external tools by enabling the Command Line column in Task Manager). 

The only viable approach here is a method for securely saving and inputting user credentials in Moonlight itself. However, for security reasons, this is not really something I want to be doing. The last thing I want is for some bug in that code to result in someone password getting leaked. I want Moonlight to stay as far away from any user data as possible.

And if that's not enough, there is no mechanism by which GameStream tells clients that they're at the login screen. This means that any sort of scripted key entry mechanism would risk typing your password into a completely unrelated window or application.

Closing this as "won't fix" due to the above.

**Comment by Eniff** [comment]
Is there a way to start GameStream right after startup before login?
