### ISSUE TITLE
if you delete the PC once connected and connect again, you can connect even if the PIN number is wrong.

### ISSUE THREAD

**Issue by TaDi2S** [moonlight-stream/moonlight-qt#484]
Occurs when building and running in qt. Is this no problem?

**Comment by cgutman** [comment]
Thanks for the report.

Fortunately, I don't think there's any security impact because GFE pins the client certificate, so it is only possible to "pair" with the wrong PIN if the PC has already been paired with Moonlight. In that case, the only thing pairing does is just pin the server certificate, because GFE already has pinned the client certificate.
