### ISSUE TITLE
Moonlight crashes Horizon Zero Dawn & Assassin's Creed Valhalla

### ISSUE THREAD

**Issue by DaddyDerek81** [moonlight-stream/moonlight-qt#489]
Game freezes in Moonlight lately past 3 weeks when playing Assassin's Creed Valhalla and Horizon Zero Dawn. Host PC is Win 10, GTX 1660 Super and i7 4770, 16GB RAM. Games play sometimes for a few minutes but then the video freezes but I can still hear audio, I have to back out and restart session but would keep happening. I'm playing on Nvidia Shield TV Pro hardwired ethernet. Those are the only games I have had any problems with for some reason.

**Comment by cgutman** [comment]
Please include the information from the [bug report issue template](https://github.com/moonlight-stream/moonlight-qt/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) so we have enough information to try to help.

**Comment by rockingdice** [comment]
Actually I did meet a lot of crashes during the streaming. It always glitches for a second, then the game crashes. Some games are made by Unreal, which send crash reports that the "d3d device is empty".

The games are all full-screen mode, heavy 3D games. How could I provide more information like logs or something? I really like this app and I am an engineer too and would like to help diagnose this issue.

Is there a way to collect crash-related information?

**Comment by cgutman** [comment]
That sounds like the D3D device was "removed" as part of handling of a [TDR](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery) event due to hang or driver crash. In the past, this has been caused by GPU overclocks (even factory ones).

Sometimes an OC might be stable for just gaming or just encoding, but together they can cause issues.
