### ISSUE TITLE
Artifact flickering on Borderless Windowed on Mac Os 

### ISSUE THREAD

**Issue by PolCPP** [moonlight-stream/moonlight-qt#493]
Hi, i've been having this for a while and never got to a process where i can reproduce it. 

Sometimes Moonlight on osx gets this kind of strange artifacting flickering 1-2 frames when there's a lot of changes on screen (for example going to menus and such). Restarting moonlight does not change it, using the latest build from #477 does nothing either.  

![image](https://user-images.githubusercontent.com/1311365/103303043-f111e480-49fc-11eb-9921-ead2771d9ee9.png)

This is all i figured out

- I had to to take a photo of the screen because if i tried to use quicktime to record the screen it stops doing it
- It does not happen on Fullscreen or windowed
- I've seen it happen on Catalina too, so its not Big Sur specific 
- Using new GFE/Drivers (updated after cyberpunk 2077 released, both old/new had the same issue).
- Using a MBP16 with an i9/5500M/16GB
- Restarting the client seems to fix it
- Doesn't seem to be game related, also seems to happen on desktop.
- Logfile from when that was taken https://pastebin.com/tR46QNp6

Edit seems to happen way more frequently if you have v-sync disabled (on moonlight i mean)

**Comment by btorresgil** [comment]
I have the same issue consistently on Borderless Window on Mac. I'm using Fullscreen for now to workaround the problem. Happy to collect more info as it's easily reproducible.

<img width="241" alt="2021-01-13_18-45-56" src="https://user-images.githubusercontent.com/4164289/104537853-974e1480-55cf-11eb-8671-2df7c13cbc5c.png">

**Comment by cgutman** [comment]
I'm not sure if there's anything we can do. It seems to be some sort of bug with macOS or the display drivers.

If it was a Moonlight bug, it wouldn't change behavior when screen recording.

**Comment by PolCPP** [comment]
@btorresgil  if you have it consistently try enabling v-sync that gets rid of it mostly for me.

@cgutman I'm starting to think its related to the Radeon Pro? since Btorres also has the same gpu? I'll be receiving an m1 air tomorrow so i can try in there.

**Comment by vhd** [comment]
I've had exact same issue on MBP16 and it's definitely related to GPU.
Temporary workarounds i've found
 - Force using dGPU. In terminal `sudo pmset -c gpuswitch 1` (0 - force iGPU, 1 - force dGPU, 2 - auto)
 - Plug in external USB-C monitor, this will also force to use dGPU
 - Play in windowed mode (for some reason that works even with iGPU)

**Comment by btorresgil** [comment]
> Force using dGPU. In terminal `sudo pmset -c gpuswitch 1` (0 - force iGPU, 1 - force dGPU, 2 - auto)

@vhd This seems to have solved it for me. Thank you very much!

**Comment by jordanebelanger** [comment]
> sudo pmset -c gpuswitch 1

Surprisingly important fix, is there anyway to fix this properly for those with dual gpus?

**Comment by vhd** [comment]
There is definitely a bug at VideoToolbox/macOS side.
After some tweaking I found a couple possible "fixes" (more like hacks)
at file `vt.mm` add 
```obj-c
m_DisplayLayer.opacity = 0.99f;
```
...or...
```obj-c
m_DisplayLayer.shouldRasterize = YES;
m_DisplayLayer.rasterizationScale = 2.0f;
```
This fixes flickering on Intel MPB 16" macs, also color bleeding and color accuracy on M1 macs.

BUT! There is another workaround
at `ffmpeg.cpp` func `FFmpegVideoDecoder::createFrontendRenderer`
forcefully set "FrontendRenderer" to SDL
```cpp
    m_FrontendRenderer = new SdlRenderer();
    if (!m_FrontendRenderer->initialize(params)) {
        return false;
    }
```
The last one fixes both flickering and color accuracy on M1 **and** when paired with patched `sdlvid.cpp`\* fixes VSYNC on all my macs.
At this point VSYNC doesn't work at all on macOS.

My first attempt to tackle down the vsync issue on Discord:
https://canary.discord.com/channels/352065098472488960/465369864534491146/854027004504703046

\* sdlvid.cpp patch means removing the condition
`if ((SDL_GetWindowFlags(params->window) & SDL_WINDOW_FULLSCREEN_DESKTOP) == SDL_WINDOW_FULLSCREEN) {`

P.S. I'm C/C++ noob, so I'm not opening PR. Also sorry for my english.

**Comment by cgutman** [comment]
> There is definitely a bug at VideoToolbox/macOS side. After some tweaking I found a couple possible "fixes" (more like hacks) at file `vt.mm` add
> 
> ```objc
> m_DisplayLayer.opacity = 0.99f;
> ```
> 
> ...or...
> 
> ```objc
> m_DisplayLayer.shouldRasterize = YES;
> m_DisplayLayer.rasterizationScale = 2.0f;
> ```
> 
> This fixes flickering on Intel MPB 16" macs, also color bleeding and color accuracy on M1 macs.
> 

Can you elaborate on these color bleeding/accuracy bugs? I have not heard of anything like that.

> BUT! There is another workaround at `ffmpeg.cpp` func `FFmpegVideoDecoder::createFrontendRenderer` forcefully set "FrontendRenderer" to SDL
> 
> ```c++
>     m_FrontendRenderer = new SdlRenderer();
>     if (!m_FrontendRenderer->initialize(params)) {
>         return false;
>     }
> ```
> 
> The last one fixes both flickering and color accuracy on M1 **and** when paired with patched `sdlvid.cpp`* fixes VSYNC on all my macs. At this point VSYNC doesn't work at all on macOS.
> 

Using the SDLRenderer is suboptimal because it requires CPU read-back of decoded video frames and it doesn't properly handle HDR or 10-bit content.

Moonlight doesn't use V-Sync on macOS and this is intended (AVSampleBufferDisplayLayer doesn't even support it). Since the Quartz compositor is always running, we don't need it to prevent tearing (similar to running with DWM on Windows, where Moonlight also doesn't use V-sync).

The way you're supposed to sync with VBlank for frame pacing purposes is via the CVDisplayLink API, which we use when the "enable frame pacing" checkbox is checked.

**Comment by vhd** [comment]
@cgutman Can you ping me on Discord?
I have an 40Mb archive with photo and video to demonstrate

**Comment by vhd** [comment]
Got some pictures. Actually photos, since that color issues only appears on actual display.
From left to right
1. original game screenshot opened in macOS default viewer app
2. Moonlight with CALayer hack (`shouldRasterize = YES`)
3. default Moonlight without any patches
4. Moonlight with SDL patch
Take a close look at the edges of the red cross, the brick wall (especially at bricks), and the sky nearby treetop.
![diff-1](https://user-images.githubusercontent.com/487056/148241108-9c0b7ac7-a6cf-4fc2-81fa-28fa05a3a3a4.jpg)
And here take a close look at red and blue text and at a power plug icon
![diff-2](https://user-images.githubusercontent.com/487056/148241783-27486353-7472-463a-9436-05a5ec425b5a.jpg)

In general, default moonlight appears darker and desaturated.
Interestingly, the SDL version looks oversaturated at first glance, but this is exactly how Windows itself and Windows version of Moonlight look on my Intel MPB 16" with BootCamp. Steam and DosBox on macOS look oversaturated too compared to windows-not-on-a-mac version, so I'm not sure which version is more correct.

There is more to the story.
When I point my iPhone's camera at this red cross, I see a similar black outline on the iPhone screen. But when I take a photo, the artifact disappears, so it's definitely Apple's fault.

**Comment by vhd** [comment]
Can someone test [this](https://ci.appveyor.com/api/buildjobs/o2agl830fxpn15cn/artifacts/Moonlight-r1.dmg) version?
It should fix flickering on 16" and color bleeding on M1 (at least it fixed it for me)

**Comment by cchaz003** [comment]
I'm not sure if I'm running into the same problem or something else but whenever I play in borderless window mode I see lots of artifacts when there is motion on screen similar to the OP screenshot. Proper fullscreen works great so thanks for that tip! I also noticed that when I put the stream stats on screen the issue disappears in borderless windowed mode. 

Happy to try to provide more help if this seems like a similar issue that someone can investigate. @vhd The link to that test version was dead so I couldn't try yours but I'm running the latest github release 4.1.0. 

MacOS 12.5 (Monterey) on 16" Macbook Pro 2019
