### ISSUE TITLE
Additional Keyboard Shortcuts (alt-tab/minimize, toggle capturing system key combinations). Customizable keyboard shortcuts. 

### ISSUE THREAD

**Issue by somerandomperson123** [moonlight-stream/moonlight-qt#500]
**Is your feature request related to a problem? Please describe.**
The new ability to capture system keyboard combinations in full screen mode is great but there is a tradeoff in that there is no one step method to actually minimize/switch out of Moonlight with the feature on. As far as I know the only way currently would be to quit session or a 2 step function of toggling to window mode and than minimizing.

In addition being able to define shortcuts would be beneficial for frequent usage compared to the currently hard defined 4 key combinations.

**Describe the solution you'd like**

Adding a keyboard combination to minimize Moonlight while in full screen.

Adding the ability to define our own shortcut combinations that overrides combinations sent to the hosts.

Adding a keyboard shortcut to toggle on/off capturing of system key combinations.

**Comment by tboby** [comment]
Similar requirements here.

My client is Ubuntu with I3 as window manager. I normally place moonlight on its own workspace, and swap between moonlight and other workspaces with Super + 1/2/3/4/.... Nor can I use my window manager's kill command (Super + shift + q).

With the latest release I can alt-tab (which is wonderful), but I can no longer access my client's machine. As there is no simple way to kill Moonlight from the server, I'm not even sure how I would kill a session if Moonlight stopped responding to its disconnect command.

> Adding the ability to define our own shortcut combinations that overrides combinations sent to the hosts.

Seems easiest, or even the opposite: Adding the ability to opt in to shortcut combinations that are forwarded to the host.

**Comment by cgutman** [comment]
Moonlight already has a Ctrl+Alt+Shift+Z combo that releases mouse and keyboard capture.

**Comment by cgutman** [comment]
> **Describe the solution you'd like**
> 
> Adding a keyboard combination to minimize Moonlight while in full screen.

I think that's doable. I could do maybe Ctrl+Alt+Shift+Tab or something.

> Adding the ability to define our own shortcut combinations that overrides combinations sent to the hosts.

Unfortunately I don't think that's going to be feasible. It's not universally possible to reinject the system shortcuts to the OS, so I don't think Moonlight can offer that functionality.

> Adding a keyboard shortcut to toggle on/off capturing of system key combinations.

Ctrl+Alt+Shift+Z will ungrab the mouse and keyboard. Due to SDL and OS limitations, it's not currently possible to change this mode on the fly (outside of totally ungrabbing input or switching out and back into fullscreen on macOS, which is a horrible UX).

> My client is Ubuntu with I3 as window manager. I normally place moonlight on its own workspace, and swap between moonlight and other workspaces with Super + 1/2/3/4/...
> With the latest release I can alt-tab (which is wonderful), but I can no longer access my client's machine to swap workspace, nor can I use my window manager's kill command (Super + shift + q). As there is no simple way to kill Moonlight from the server, I'm not even sure how I would kill a session if Moonlight stopped responding to its disconnect command.

Yep, capture is a double-edged sword. I'm not sure if there's a better solution. SDL only offers full keyboard capture, not specific keys.

**Comment by tboby** [comment]
Docs currently say:

>Ctrl+Alt+Shift+Z - Toggle mouse pointer capture

But that's a better workaround, thanks.

And it turns out that the new setting only applies to the Super/Windows key. So if I turn off "Capture system keyboard shortcuts..." then Alt-Tab and Ctrl-Alt-Del are still forwarded, but Super + key is not. So there is a workaround there if you can move shortcuts on your client to use the Windows key, and move shortcuts on your desktop away from the Windows key.

Not sure if that's intentional though!

**Comment by cgutman** [comment]
Yeah it’s intentional. There’s no universal list of keys to capture and different OSes (and even key combos) behave differently. Sometimes system keys are delivered to the app and the OS and other times they go to the OS only.

The only system key modifier that Moonlight chooses not to intercept when system key capture is disabled is the Super key.

I’ll fix the docs to reflect the new keyboard grab behavior.

**Comment by cgutman** [comment]
Added Ctrl+Alt+Shift+Down Arrow shortcut to minimize in https://github.com/moonlight-stream/moonlight-qt/commit/d38ff5759af051879eff1e426f35214c62639453

**Comment by shodanx2** [comment]
A mute button would be nice. 
In my case I have moonlight client connected to a collectively shared virtual machine with my friends
We always let it play music, sometimes I just want to mute it, not turn down the sound inside the VM, just mute my moonlight instance since I still want to remain connected to and displaying in my second monitor.
