### ISSUE TITLE
multithreaded download

### ISSUE THREAD

**Issue by manaboy** [moonlight-stream/moonlight-qt#519]
**Is your feature request related to a problem? Please describe.** 
Ok so when I'm streaming under statistics I "get frames drop by your network 7%" every now and then, my download speeds on speed test shows 50mbps, when downloading any files, with internet download manager or Firefox multithreaded downloader I get a constant speed of 5.5/6MBps, this is constant,

**Describe the solution you'd like**
I'm thinking would performance improve if audio and video was downloaded on separate download streams/threads or if moonlight implemented multithreaded download Steam.

**Describe alternatives you've considered**

**Additional context**

**Comment by manaboy** [comment]
Any insights on my hypothesis?

**Comment by cgutman** [comment]
Moonlight already downloads video and audio over separate connections on separate threads.

I've never seen a case where the problem was Moonlight itself being too slow to consume the data off the wire. The packet loss is pretty much always exactly what it says "frames dropped by your network" whether due to exceeding available bandwidth between the client and host or just being the victim of an unreliable network medium (like 2.4 GHz WiFi).
