### ISSUE TITLE
HEVC doesn't work on GTX 1650

### ISSUE THREAD

**Issue by lswill1** [moonlight-stream/moonlight-qt#530]
Same as rtx3080, HEVC can't be turned on when using moonlight

**Comment by lswill1** [comment]
Rtx3080 using GFE3.20.5.83 can solve the problem, but gtx1650 is not

**Comment by lswill1** [comment]
The driver has also been re installed with the old version of.
#0(I)[2021-02-27 06:08:15,736]=14:08:15={8892}<AdapterContext>   Driver version is 442.74, branch is r442_70.
#1(I)[2021-02-27 06:08:15,736]=14:08:15={8892}<AdapterContext>   System is NOT co-proc.
#2(I)[2021-02-27 06:08:15,736]=14:08:15={8892}<ServerMiscUtils>  Found a match at [22]
#3(D)[2021-02-27 06:08:15,736]=14:08:15={8892}<VideoEncoder>     Creating NvEnc10VideoEncoder.
#4(I)[2021-02-27 06:08:15,736]=14:08:15={8892}<VideoEncoder>     Initializing NvEnc10VideoEncoder.
#5(I)[2021-02-27 06:08:15,736]=14:08:15={8892}<NvEnc10VideoEnco> Using NvEnc header version 9.1.
#6(I)[2021-02-27 06:08:15,767]=14:08:15={8892}<ServerMiscUtils>  Found a match at [22]
#7(I)[2021-02-27 06:08:15,767]=14:08:15={8892}<NvEnc10VideoEnco> Device '' does not support HEVC.

**Comment by lswill1** [comment]
[Moonlight-1614405919.log](https://github.com/moonlight-stream/moonlight-qt/files/6053840/Moonlight-1614405919.log)

**Comment by cgutman** [comment]
You should probably report the lack of HDR GameStream on the GTX 1650 to Nvidia. That's how the affected RTX 3000-series users got the problem resolved. This is a driver/GFE problem that we can't override in the client (attempting to request HEVC just causes the entire connection to fail)

**Comment by lswill1** [comment]
Thank you for your reply, but how should I contact nvidia? Is it on the GameStream forum?

**Comment by cgutman** [comment]
I believe the previous users left feedback here - https://www.nvidia.com/en-us/support/consumer/

**Comment by neotaburiss** [comment]
I've already submit a ticket via 

Question Reference # 210319-000750

Pls kindly help submit if you encounter same issue that will solve this problem faster.

**Comment by lswill1** [comment]
我在英伟达论坛联系了Greybear先生，他说GTX1650不支持b-Frame，不知道是不是和这个有关
https://www.nvidia.com/en-us/geforce/forums/notifications/topic/224886/

**Comment by lswill1** [comment]
> 我已经通过提交了票证
> 
> 问题参考号210319-000750
> 
> 如果遇到相同的问题，请尽快帮助您解决问题。

Can you send me a link address

**Comment by lswill1** [comment]
I contacted Mr. Greybear on the Nvidia forum, he said that GTX1650 does not support b-Frame, I don’t know if it is related to this
https://www.nvidia.com/en-us/geforce/forums/notifications/topic/224886/

**Comment by lswill1** [comment]
> I've already submit a ticket via
> 
> Question Reference # 210319-000750
> 
> Pls kindly help submit if you encounter same issue that will solve this problem faster.

Can you send me a link address

**Comment by neotaburiss** [comment]
> > I've already submit a ticket via
> > Question Reference # 210319-000750
> > Pls kindly help submit if you encounter same issue that will solve this problem faster.
> 
> Can you send me a link address

关于这个问题Nvidia已经回复 详细的询问了我关于使用环境的情况,我编不下去.只能说我用moonlight,然后他回复不能对moonlight的情况进行反馈,本身gfe支持h265串流  下次反馈的时候请记得一定要咬定用的是shield
关于这个问题,我查了下, 因为1650有两种核心 TU117(老-不支持hevc b-frame) TU116(新-支持hevc b-frame),  所以可能gfe里对这个支持不好
我的显卡是翔升1650单槽半高那款(TU117), 不知道你是哪个品牌哪个型号? 我估计应该是通病
----------------------------Transled by deepl---------------------------------------
On this issue Nvidia has replied asking me in detail about my environment, I can't go on. All I can say is that I'm using moonlight and he replied that he couldn't give feedback on moonlight, so please remember to make sure commenting that you're using shield when you give feedback next time.
About this problem, I checked, because 1650 has two cores TU117 (old - no hevc b-frame support) TU116 (new - hevc b-frame support), so maybe this support is not good in gfe
My card is a 1650 single slot half height model of Xiangsheng, I don't know which brand and model you have? I guess it's a common problem

Translated with www.DeepL.com/Translator (free version)

**Comment by neotaburiss** [comment]
另外我之前用的是P600显卡(GP107核心), 用h265串流完全没问题, 所以这个必然是一个bug
----------------------------Translated by deepl---------------------------------------
Also I was using a P600 card (GP107 core) before and had no problem streaming with h265, so this must be a bug
