### ISSUE TITLE
Gain host OS control by Cmd-Tab (macOS)

### ISSUE THREAD

**Issue by witchcraftsman** [moonlight-stream/moonlight-qt#535]
Setup:
Host OS: macOS
Remote PC's OS: Windows

Issue:
Currently, it's only possible to switch to remote PC's desktop (by doing alt-tab in Windows) while having action connection

Request:
That would be awesome to be able to switch to host OS (macOS) to gain control by doing Cmd-Tab or other key combination, if it's even possible by design
Also requested as possible workaround for [this issue](https://github.com/moonlight-stream/moonlight-qt/issues/534)

**Comment by witchcraftsman** [comment]
Not sure how alt-tabbing works when you steam to Windows host (or even Linux), so requesting for macOS only

**Comment by cgutman** [comment]
It sounds like you might be in "full-screen" rather than "borderless windowed" On macOS this prevents you from Cmd-Tabbing. The tooltip also warns of this:
![image](https://user-images.githubusercontent.com/2695644/110209641-2569ad00-7e53-11eb-802c-8d7fb9038259.png)

This is why we default to borderless windowed on macOS. I suggest you use that.

**Comment by witchcraftsman** [comment]
Ok thanks, didn't notice the tip
