### ISSUE TITLE
3.1.0 Steam link device problems

### ISSUE THREAD

**Issue by coolwhg** [moonlight-stream/moonlight-qt#545]
Hello, I am using version 3.1.0 of Steam link device, and there are currently several problems:
1. The Simplified Chinese font library is incomplete, and some Chinese are displayed as boxes;
2. Before entering the game, the program crashes before the game screen is displayed

**Comment by cgutman** [comment]
> Hello, I am using version 3.1.0 of Steam link device, and there are currently several problems:
> 
> 1. The Simplified Chinese font library is incomplete, and some Chinese are displayed as boxes;

Yeah, the Steam Link firmware probably lacks the full set of Chinese fonts as you have guessed. I guess we will have to disable the Simplified Chinese translation on Steam Link.

> 2. Before entering the game, the program crashes before the game screen is displayed

I'll need more information on this. Moonlight itself is crashing or the game on your PC is crashing?

Please fill out the issue template for filing a Moonlight bug report.

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce**
Any special steps that are required for the bug to appear.

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
List the games you've tried that exhibit the issue. To see if the issue is game-specific, try streaming Steam Big Picture with Moonlight and see if the issue persists there.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on iOS or Android?

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Client PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - Moonlight Version: [e.g. v0.9.0]
 - GPU: [e.g. Intel HD Graphics 520]

**Server PC details (please complete the following information)**
 - OS: [e.g. Windows 10 1809]
 - GeForce Experience version: [e.g. 3.16.0.140]
 - Nvidia GPU driver: [e.g. 417.35]
 - Antivirus and firewall software: [e.g. Windows Defender and Windows Firewall]

**Moonlight Logs (please attach)**
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`

**Additional context**
Anything else you think may be relevant to the issue

**Comment by coolwhg** [comment]
Describe the bug
After the steam link is installed with moonlight 3.1.0, and then enter any game, including the streaming desktop, will flash back
But it works in v2.2.0,Not working since 3.0.0

Steps to reproduce
The steam link version is 791, and entering the game, including the desktop, will happen

Screenshots
No photos

Affected games
any

Other Moonlight clients

Does the issue occur when using Moonlight on iOS or Android?
No

Have any settings been adjusted from defaults?
It should be the default, it works in v2.2.0, and If I modify it, how can I restore it?

If so, which settings have been changed?
NONE

Does the problem still occur after reverting settings back to default?
YES

Do you have any gamepads connected to your host PC directly?
YES

OS: [e.g. Windows 10 20H2]
Moonlight Version: [3.1.0]
GPU: [1660 super]

**Comment by cgutman** [comment]
Is this still happening with Steam Link firmware 806 and Moonlight v3.1.1?

**Comment by coolwhg** [comment]
I tried:
NVIDIA experience v3.22.0.32
Steam Link firmware 806 and Moonlight v3.1.1
but when streaming any games，all display
`Starting RTSP handshake failed:Error 111
Check your firewall port forwarding rules for port(s):TCP48010,UDP 48000,UDP 48010
`

**Comment by coolwhg** [comment]
I tried:
NVIDIA experience v3.22.0.32
Steam Link firmware 806 and Moonlight v3.1.1
but when streaming any games，all display
`Starting RTSP handshake failed:Error 111 Check your firewall port forwarding rules for port(s):TCP48010,UDP 48000,UDP 48010`

and strange，when displayed error, I check the game direct launch,and back and re entry to the host, it's working !!!

**Comment by coolwhg** [comment]
can add traditional Chinese ？ because simplified Chinese has problems
