### ISSUE TITLE
Issue at installation

### ISSUE THREAD

**Issue by chosebine501** [moonlight-stream/moonlight-qt#549]
Hi,
since version 3.0 I am no longer able to install.
I always get this error.
![errorfirewall](https://user-images.githubusercontent.com/79770276/111874415-8a50f700-896b-11eb-904e-aac8257b04c5.PNG)
the service is functional.

regards

**Comment by cgutman** [comment]
In an administrator command prompt, please run the following 2 commands and paste their output here:

```
sc qc mpssvc
sc query mpssvc
```

**Comment by chosebine501** [comment]
SERVICE_NAME: mpssvc
TYPE : 20 WIN32_SHARE_PROCESS
START_TYPE : 1 SYSTEM_START
ERROR_CONTROL : 1 NORMAL
BINARY_PATH_NAME : C:\Windows\system32\svchost.exe -k LocalServiceNoNetworkFirewall -p
LOAD_ORDER_GROUP : NetworkProvider
TAG : 0
DISPLAY_NAME : Windows Defender Firewall
DEPENDENCIES : mpsdrv
: bfe
SERVICE_START_NAME : NT Authority\LocalService

C:\Windows\system32>sc query mpssvc

SERVICE_NAME: mpssvc
TYPE : 20 WIN32_SHARE_PROCESS
STATE : 4 RUNNING
(NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
WIN32_EXIT_CODE : 0 (0x0)
SERVICE_EXIT_CODE : 0 (0x0)
CHECKPOINT : 0x0
WAIT_HINT : 0x0

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cgutman** [comment]
Ah, the problem is that your MpsSvc service is configured as `SYSTEM_START` instead of `AUTO_START`. System start is only meant for drivers.

Run the .reg file in this zip and it will restore the service configuration back to the default start value. [mppsvc_start.zip](https://github.com/moonlight-stream/moonlight-qt/files/6176495/mppsvc_start.zip)
