### ISSUE TITLE
Settings Menu scrolls constantly to the top if a vJoy Device exists

### ISSUE THREAD

**Issue by kyoubate-haruka** [moonlight-stream/moonlight-qt#550]
**Describe the bug**
If a vJoy Device exists (basically a virtual controller driver: http://vjoystick.sourceforge.net/site/), the Settings menu (and only the Settings menu, not the game selection) will attempt to scroll up constantly, even if no input is made with that device, preventing me from changing some settings. Only Moonlight appears to pick up input from that driver for some reason as I've not seen this happening anywhere else (I use that driver for developing a couple things; I am NOT trying to use this device for input in Moonlight)

**Steps to reproduce**
Have a vJoy device enabled, and go to the settings menu in Moonlight.

**Screenshots**
Video of what is happening:

https://user-images.githubusercontent.com/46010460/111885127-12fc8100-89c6-11eb-96a4-3cb7021cfbd7.mp4

Status of the input device when the issue occurs (basically no input): 
<img width="298" alt="HqW3h 1" src="https://user-images.githubusercontent.com/46010460/111884593-e8f58f80-89c2-11eb-9847-a74b6719879c.png">

**Affected games**
N/A

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
Visible within the video if they should be relevant

**Gamepad-related issues (please complete if problem is gamepad-related)**
Only the vJoy Device as described above, with these settings:
<img width="277" alt="HqW6U 1" src="https://user-images.githubusercontent.com/46010460/111885281-193f2d00-89c7-11eb-930b-3df169359fa7.png">

**Client PC details (please complete the following information)**
 - OS: Windows 10 1909
 - Moonlight Version: 3.1.0
 - GPU: GeForce GTX 1070

**Server PC details (please complete the following information)**
N/A

**Moonlight Logs (please attach)**
[Moonlight-1616252666.log](https://github.com/moonlight-stream/moonlight-qt/files/6176364/Moonlight-1616252666.log)
(Sensitive data has been removed)

**Additional context**
If this is out of scope, it would be nice to have an option to disable Moonlight menu input from gamepads.

**Comment by cgutman** [comment]
OK, there are a few problems that are causing this.

The main problem is that the default vJoy Feeder configuration has Axis RX and Axis RY at 0 by default, rather than centered at 50% as is appropriate for the right stick. This is the cause of the errant right stick input that is forcing Moonlight to scroll up. 

Second, SDL_GameControllerDB had the wrong mappings for the vJoy device's right stick which I fixed here https://github.com/gabomdq/SDL_GameControllerDB/pull/450. The result was that the zeroed axis behavior in SDL was not being triggered, causing the errant idle state to result in movement.

I have pushed the updated SDL_GameControllerDB to the website, so Moonlight will pick it up once you restart it. You'll need to restart Moonlight twice (once to download the new mappings and once more to actually load them), but the issue should disappear after that.
