### ISSUE TITLE
New client clipboard feature is broken in some locales

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#554]
Tried out the new clipboard paste feature in 3.1.0.

Copying this:
https://github.com/moonlight-stream/moonlight-qt/releases

Results in pasting that:
httpsÖ--github.com-moonlightßstream-moonlightßqt-releases

Mostly some wrongly conversion (or no conversion at all) of unicode or other language related issue. I am using German Windows 10. I have set language in streaming client to English btw because I like English better, but that shouldnt result in this issue obviously.

Also, it should work the other way around too, and Ctrl+Alt+Shift+C should copy the server clipboard you then can just normally paste via ctrl+v on the client. So you have to change that new Ctrl+Alt+Shift+C for cursor to something else. Tested setting language to German in client, but that seems to be irrelevant for this issue.

Also as a suggestion: Moonlight client should have some sort of overlay GUI, where you can access / see all the shortcuts.

**Comment by cgutman** [comment]
It's probably some locale conversion thing.

Copying clipboard text back to Moonlight cannot because GameStream does not support passing clipboard data back. We can do this from client->host because we simply type the clipboard text, which requires no protocol support. The support (and limitations) of typing clipboard text is basically the same as the Microsoft Hyper-V client provides.

**Comment by makedir** [comment]
Like I said, German. So its just a QWERTZ QWERTY issue. You have to use unicode or uft8 for that so its properly on regardless what region someone uses.

**Comment by cgutman** [comment]
> Like I said, German. So its just a QWERTZ QWERTY issue.

Both are set to QWERTZ?

> You have to use unicode or uft8 for that so its properly on regardless what region someone uses.

It's not that simple. The clipboard text string we get from SDL [is already UTF-8](https://wiki.libsdl.org/SDL_GetClipboardText). However, the GameStream protocol doesn't accept strings (UTF-8 or otherwise); it accepts key presses using [Windows Virtual-key codes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes). We have to take the string and convert it as best we can to ASCII which we can then convert to Virtual-key codes for GameStream.

The problem could really be one of three things:
1. SDL is mangling the keyboard text (unlikely, but also easy to confirm)
2. The `const char*` to QString conversion is mangling the text (also unlikely, given that `QString::append()` assumes UTF-8 input)
3. The virtual keys sent from Moonlight are "correct" but are getting misinterpreted due to the QWERTZ layout on the host PC.

**Comment by abusse** [comment]
I just put in some debug prints and it seems to be problem 3. It's basically like having a physical US keyboard and a German keyboard set in Windows.

So the most straight forward solution for the issue, but probably the most inconvenient one, would be to set the target Windows to a US keyboard layout.

The more convenient solution would be to have a setting in Moonlight for the target keyboard layout and do a mapping before sending the scan code. Even though that sounds like a problem that someone else might have stumbled upon, I couldn't find a library that achieves that goal so far. We could off course write mappers ourself, but with so many keyboard layouts out there that sounds like a very tedious task and feels like reinventing the wheel.

However, as an initial work, it might be a good idea to mangel each character through a conversion function as there are already some characters that get converted. Further down the road we could simply "plugin" a library that does the conversion for different keyboard layouts. What do you think?

**Comment by cgutman** [comment]
This is fixed in v3.2.0. Clipboard text is sent as UTF-8 now.
