### ISSUE TITLE
Maximized Windowed Mode on MacOS Big Sur enables Do Not Disturb

### ISSUE THREAD

**Issue by Proplex** [moonlight-stream/moonlight-qt#564]
Howdy y'all,

First off, thanks for all the work on Moonlight, I use it daily for productivity and video games.

I'm currently experiencing an issue where when I launch a program in Moonlight, my Mac enables DND and silences notifications. This appears to be an issue with some other programs as well. This has started ever since upgrading to Big Sur.

I haven't done much research, but I believe this is caused when programs are not using the native full screen API. Mozilla also had this issue with FF enabling DND when [videos went full-screen](https://bugzilla.mozilla.org/show_bug.cgi?id=1677266#c7). It was solved by enabling the native full screen calls, which I don't believe Moonlight-qt currently uses.

Any ideas?

**Comment by cgutman** [comment]
Does the same issue happen when you use Fullscreen or Borderless windowed mode instead of just maximizing the window?

Those modes do use the full-screen APIs in macOS.

**Comment by Proplex** [comment]
Sorry I wasn't clear, I was trying this with Borderless Windowed (recommended) mode. The DND occurs when Moonlight is in focus on the "full screen desktop" that macOS creates for it. Swiping to another virtual desktop disables the DND.

**Comment by dannystewart** [comment]
This one’s driven me crazy for months and I finally did a deeper dive on it to learn more. Based on research it seems like apps that implement fullscreen non-natively (not sure of the specifics) can suppress system notifications to where they don’t display a banner or make a sound. I’ve missed messages for hours because of this on occasion.

I thought maybe if I could get Moonlight to use the standard system fullscreen behavior that might fix it, so I tried running Moonlight in windowed mode and then manually putting it in fullscreen by clicking the green button in the titlebar, and sure enough, that did it! Notifications worked normally again!

I assumed Moonlight used the standard system fullscreen because it looks and functions exactly like it, right down to creating its own space you can swipe back and forth between, but apparently that's not the case. This only happens with borderless windowed. Fullscreen takes over completely and even blacks out other monitors if you have more than one, which is worse than either of the other two options.

Moonlight obviously already supports native fullscreen as it is today with no changes—it’s just a manual two-step process to get it to do that. A minor inconvenience, but not the end of the world. Is there a reason that borderless windowed mode operates the way that it does instead of using native fullscreen? Might it be possible to fix? I would love to know more.

**Comment by cgutman** [comment]
Moonlight uses SDL for window management, so this bug should probably be [reported to them](https://github.com/libsdl-org/SDL/issues).

You could try compiling their tests and running one in full-screen to see if the behavior is identical. I suspect it will be.
