### ISSUE TITLE
Decoder performance much poorer than moonlight-mac in high packet loss situations

### ISSUE THREAD

**Issue by benwwchen** [moonlight-stream/moonlight-qt#57]
**Describe the bug**
When I use [moonlight-mac](https://github.com/FelixKratz/moonlight-mac) which is based on [moonlight-ios](https://github.com/moonlight-stream/moonlight-ios) on an early-2015 MBP and an i7-3770 Hackintosh both running macOS High Sierra, the 1080p 60fps video streams very smoothly when it's set to use H.264 just like it is on iOS. The Hackintosh can even choose to force decode HEVC smoothly without any noticeable stutter.

However, the moonlight-qt version stutter a lot and often skips many frames on both computers. Besides,  it'll freeze for around 1 second every couple of seconds. The Force HEVC option is unusable (very slow) even on the i7 machine.

I wonder if it's related to the decoder (FFmpeg vs AVSampleBufferDisplayLayer?) or just other reasons causes this to happen.

**Moonlight settings (please complete the following information)**
1080P, 60fps, 20Mbps.
Force H.264/HEVC.

**Client PC details (please complete the following information)**
 - OS: macOS High Sierra 10.13.6
 - Moonlight Version: v0.3.0

**Logs (please attach)**
[Moonlight-1535698517.log](https://github.com/moonlight-stream/moonlight-qt/files/2339532/Moonlight-1535698517.log)

**Comment by benwwchen** [comment]
@cgutman 

- But with moonlight-mac, even with the system provided software decoder, the CPU is able to handle HEVC streaming, while it's not on moonlight-qt.

- For H.264, here is the log with V-sync enabled. Stutter remains. And I can feel that the mouse cursor is noticeably smoother in moonlight-mac than in moonlight-qt while the color quality looks better in moonlight-qt. Is there some parameters other than bitrate (which is the same on both) related to quality/speed?
[Moonlight-1535740787.log](https://github.com/moonlight-stream/moonlight-qt/files/2341203/Moonlight-1535740787.log)

**Comment by cgutman** [comment]
- yep, but I can't guarantee that so clients can handle the stream with the software decoder. Not everyone will have a desktop quad-core CPU for decoding. I'd much rather be conservative and use H.264 rather than possibly tank performance with a bad choice of codec. Most hybrid and software decoders are only good for <= 30 FPS.

- the stutter in this log is definitely network packet loss. Moonlight-mac has a different algorithm for bitrate calculation that makes the effective bitrate lower than what other Moonlight clients would use (probably also why the video quality looks worse). This is because it's reducing the bitrate slightly to account for audio overhead. I believe it also does other optimizations if you say you're streaming remotely which may further reduce the actual video bitrate. Try reducing the bitrate in Moonlight Qt and see if that makes performance similar.


While working on the macOS decoder, I did an implementation that was purely AVSampleBufferDisplayLayer (basically copied from Moonlight iOS like Mac was) and the performance was identical. In fact, the pure AVSampleBufferDisplayLayer solution was harder to synchronize with V-blank since we were dealing with an undecoded video frame with variable size and decode time rather than raw YUV data.

**Comment by benwwchen** [comment]
Reducing the bitrate in Moonlight Qt does work at some level. It's much smoother now. However, stutter still appears every several seconds no matter V-sync is on or off. Here is the log reducing the bitrate to 14Mbps: 
- V-sync on: [Moonlight-1535744169.log](https://github.com/moonlight-stream/moonlight-qt/files/2341376/Moonlight-1535744169.log)
- V-sync off: [Moonlight-1535744609.log](https://github.com/moonlight-stream/moonlight-qt/files/2341407/Moonlight-1535744609.log)

Although the stuttering is probably caused by network packet loss, the video freezes noticeably longer in Moonlight Qt than in Moonlight Mac. Because when I constantly moves the cursor, at the time it stutters, the cursor jumps directly to a new location in Moonlight Qt while it only moves not so smoothly in Moonlight Mac.

Thanks so much for your patience.

**Comment by cgutman** [comment]
Oh, I think I know why. Moonlight Mac has the reference frame invalidation option turned on for H.264, so the error recovery can be much quicker (and doesn't require a full key frame). I'll take a look at turning that on for the VideoToolbox decoder to make sure there's no performance regressions.

**Comment by euroclydon37** [comment]
I have this issue (where the video drops frames/freezes every 30 seconds or so. It's unplayable. But one thing I'd like to add is that I experienced this on iPad Pro, and iPhone 6s Plus as well.
