### ISSUE TITLE
Can't install on Raspberry Pi OS 64bit (aarch64)

### ISSUE THREAD

**Issue by r00k135** [moonlight-stream/moonlight-qt#570]
I'm trying to install moonlight-qt on Raspberry Pi OS 64bit with an architecture reporting of aarch64, I followed the standard install instructions for the Raspberry Pi 4, but when I try and run "sudo apt install moonlight-qt", I get "E: Unable to locate package moonlight-qt".

Can you provide a package for the 64bit OS?

**Comment by cgutman** [comment]
I will check on this. We were blocked because MMAL is broken on the 64-bit OS. https://www.raspberrypi.org/forums/viewtopic.php?t=275423

We require MMAL for H.264 decoding because the V4L2 M2M performance of the H.264 codec is terrible.

**Comment by cgutman** [comment]
Here is a highly experimental build: https://drive.google.com/file/d/15X57gdkZg-r9YymL78eESr3ZPpp-eCwS/view?usp=sharing

You can install it with `dpkg -i` and you may need to run `apt install --fix-broken` afterwards to download dependencies.

As mentioned before, there are significant caveats to this build since 64-bit MMAL support is not available:
- H.264 decoding performance is quite poor when running within the desktop environment. If you do run it from the desktop environment, running it in windowed mode seems to perform the best.
- 720p 60 FPS H.264 is playable in windowed mode within the desktop environment, or full-screen when running from the console
- 1080p 60 FPS H.264 is unplayable in all scenarios (1080p 60 FPS HEVC performs well though, see below).
- It is _highly_ recommended that you enable the HEVC decoder by adding `dtoverlay=rpivid-v4l2` to your /boot/config.txt. The HEVC decoder performs _significantly_ better than the H.264 decoder when MMAL is not supported.
- It is _highly_ recommended that you run Moonlight from the console. HEVC support only works when running outside of the desktop environment.

There will need to be significant performance improvements to the Raspberry Pi's GLES implementation and H.264 V4L2 codec before we can possibly consider officially supporting this. That, or they fix and re-enable 64-bit MMAL.

**Comment by cgutman** [comment]
I managed to build the 64-bit MMAL libraries myself and bundle them into the moonlight-qt package.

There are now aarch64 packages as of Moonlight Qt v3.2.0.

**Comment by jgabriel98** [comment]
got it (kinda):
so, instead of running with `distro=raspbian codename=buster`, i downloaded setup.deb.sh (from https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh) and exectuted it,

so it detected correctly the OS:
```
pi@raspberrypi:~ $ sudo ./setup.deb.sh
Executing the  setup script for the 'moonlight-game-streaming/moonlight-qt' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=debian  version=11  codename=bullseye  arch=aarch64
 >>>>:
 NOPE: Checking for apt dependency 'apt-transport-https' ...
   OK: Updating apt repository metadata cache ...
   OK: Attempting to install 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'moonlight-game-streaming/moonlight-qt' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'moonlight-game-streaming/moonlight-qt' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock
```

after this, when trying to install, got this error:
```
pi@raspberrypi:~ $ sudo apt install moonlight-qt
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package moonlight-qt
```

but if run the setup with `distro=raspbian codename=buster`, like this
```
 curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian codename=buster sudo -E bash
Executing the  setup script for the 'moonlight-game-streaming/moonlight-qt' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'moonlight-game-streaming/moonlight-qt' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'moonlight-game-streaming/moonlight-qt' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!
```

it manages to find and install `moonlight-qt` (`sudo apt install moonlight-qt`) with no problems.


But why is the package available only for raspbiOS buster?
even when is a aarch64, that will be bullseye (raspiOS 64-bit have official support only after bullseye)

**Comment by cgutman** [comment]
The packages are built on buster, but run on both buster and bullseye.
