### ISSUE TITLE
Moonlight fails (QNetworkReply::HostNotFoundError) when connecting via CLI

### ISSUE THREAD

**Issue by kirasm** [moonlight-stream/moonlight-qt#581]
**Describe the bug**
Moonlight fails to connect to host when using the 'moonlight stream host [IP]' command. It works fine when starting moonlight without arguments and manually selecting the host.

**Steps to reproduce**
Run the command 'moonlight stream host [IP]'

**Screenshots**
![screenshot_moonlight_bug](https://user-images.githubusercontent.com/18591529/115986238-91dd6e80-a5af-11eb-94bb-de22b5888f0c.PNG)

![screenshot_moonlight_failed_to_connect](https://user-images.githubusercontent.com/18591529/115986138-34e1b880-a5af-11eb-99be-1b89ece0b551.PNG)

**Client PC details**
 - OS: Lubuntu (Ubuntu 18.04.5 LTS)
 - Moonlight Version: 3.1.1
 - GPU: Nvidia GT 745m

**Server PC details**
 - OS: Windows 10 120H2
 - GeForce Experience version: 3.22.0.32
 - Nvidia GPU driver: 466.11
 - Antivirus and firewall software: No Windows Defender or Windows Firewall

**Moonlight Logs**
[moonlight_log.txt](https://github.com/moonlight-stream/moonlight-qt/files/6371531/moonlight_log.txt)

**Additional context**
The problem is the same through flatpack.

**Comment by cgutman** [comment]
It's because the command-line arguments are wrong. It's trying to stream from a host named literally "host".

I'm not sure where you got that command-line from but the correct options for Moonlight Qt are:
`moonlight [options] stream <host> "<app>"`

Where `<host>` is an IP address, PC name, or hostname.

You can also run `moonlight stream --help` for more usage info.
