### ISSUE TITLE
Microstutter introduced with Version 3.0

### ISSUE THREAD

**Issue by koshisan** [moonlight-stream/moonlight-qt#583]
Hi,

I asked a few times on discord about the problem before, but since nobody else seems to be experiencing this and it did persist for a few releases now and I am finally "forced" to update because of the new GFE Version, I decided to file a "formal" bug report:

**Describe the bug**

Since upgrading to Version 3.0 I experience "microstutter". It seems to be very regulary - every second the game freezes for a few milliseconds. Because of the nature of the problem it is sometimes barely noticable (on desktop/in menus), sometimes it renders the game to be unplayable (in fast action scenes, etc).

**Steps to reproduce**

I experience the bug every time I launch Moonlight - It also does not depend on any options (at least not the once I did suspect could have an effect - Encoder, Bitrate, Resolution, Frequency - the problem always stays the same).
While I am mainly using moonlight-qt on Windows, I also did install the Android version which is experiencing the same issue!

**Screenshots**

It is a bit difficult to show stutter on screenshots ;) However, I made a video (from the android version - but as mentioned, the problem is exactly the same): https://youtu.be/eG4jmxQ65Kg

**Affected games**

Since the problem was introduced with version 3.0, I do not think it is game-dependend, but I did test with a second game (Nier) just to be sure...

**Other Moonlight clients**
Yes, the problem also exists on Android. I did not test iOS, but I would be able to if needed

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? <- I am normally running at 4k60, but the problem also persists for lower resolutions/fps
- If so, which settings have been changed? <- So far I tried changing resolution/bitrate/ftps/v-sync/frame pacing - without any success
- Does the problem still occur after reverting settings back to default? <- Yes! However, reverting back to version 2.2.0 fixed the issue every time - unfortunately with the new GFE that is not an option anymore...

**Gamepad-related issues (please complete if problem is gamepad-related)**
I do not believe the problem to be gamepad-related

**Client PC details (please complete the following information)**
 - OS: Windows 10 20H2
 - Moonlight Version: Every version newer than 2.2.0
 - GPU: Geforce 1070

**Server PC details (please complete the following information)**
 - OS: Windows 10 20H2
 - GeForce Experience version: 3.22.0.32 - the problem also existed with previous versions
 - Nvidia GPU driver: 461.72
 - GPU: Gefore 3090
 - Antivirus and firewall software: Windows Defender in default configuration, Firewall disabled

**Moonlight Logs (please attach)**

Now, this is where it gets interesting! 

[Moonlight-1619480880.log](https://github.com/moonlight-stream/moonlight-qt/files/6381146/Moonlight-1619480880.log)

At first I did start a session with 3840x2160x60. The logfile implies that the frameloss is network-related:

Unrecoverable frame 1474: 21+0=21 received < 109 needed / Network dropped an entire frame

However - as mentioned - this issue did not exist before upgrading from 2.2.0...

Also I did start a session with 1920x1080x30 next, which completely solves the "Unrecoverable frame" issues in the log - However, the perceived microstutter is unchanged...

**Additional context**

I should add that unfortunately I have to connect Client and Server through Wifi here, but both PCs are connected to a (Wifi 6/2400Mbps backbone) mesh bridge endpoint with a LAN cable. For the Android testing the client was connected directly to the same AP as the server - without any difference

Since I use Moonlight on a daily basis to stream from my gaming rig in the living room to my office PC, I really hope we can sort this out. Please let me know if I can supply any additional debugging information!

**Comment by cgutman** [comment]
At least part of the problem is the lack of support for multi-FEC frames with GFE 3.22 which is causing excessive frame loss in your environment.

Can you try out this build and upload a new log? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38886929/job/l6o9k9i5u7of0gf3/artifacts

One other thing that stuck out to me is:
```
00:01:52 - Qt Info: Found matching interface: "Ethernet 4" "XXX" QFlags<QNetworkInterface::InterfaceFlag>(IsUp|IsRunning|CanBroadcast|CanMulticast)
00:01:52 - Qt Info: Interface Type: QNetworkInterface::Ethernet
00:01:52 - Qt Info: Interface MTU: 1472
```
The MTU of the network connection that you're streaming over is less than 1500 (standard MTU for Ethernet/WiFi) which is causing Moonlight to run in Internet/VPN streaming mode. You're not streaming over a VPN or anything, are you? What brand and model of network adapter is "Ethernet 4"?

**Comment by koshisan** [comment]
Here is the new log: 
[Moonlight-1619504752.log](https://github.com/moonlight-stream/moonlight-qt/files/6382362/Moonlight-1619504752.log)

The problem still does persist. 

The MTU thing is quite interesting. I am not streaming over VPN. The adapter is a Realtek PCIe GbE Adapter - nothing exotic.

But (!) while I do see that the MTU in the log is reported as 1472, netsh on Windows reports the MTU as 1500:

C:\WINDOWS\system32>netsh interface ipv4 show subinterfaces

   MTU  Medienerkennungsstatus   Bytes eingehend  Bytes ausgehend  Schnittstelle
------  ---------------  ---------  ---------  -------------
4294967295                1          0     339533  Loopback Pseudo-Interface 1
  1500                5          0          0  Ethernet 3
  1500                5          0          0  ???? ?????* 11
  1500                5          0          0  WLAN
  1500                1   14688146    6594608  ?????? 3
  1500                1  194319299  152945545  ?????? 4
  1500                1   36177345   11380057  ?????? 5
  1500                5          0          0  ?????? 6
  1500                5          0          0  ?????? 7
  1500                5          0          0  ?????? 8
  1500                5          0          0  ?????? 9
  1500                5          0          0  ?????? 10
  1500                1  31705972859  1622417377  Ethernet 4
  1500                5          0          0  ?????? 14
  1500                5          0          0  Bluetooth-Netzwerkverbindung

(Please ignore all the VPN adapters - they are all split tunnels)

**Comment by koshisan** [comment]
For comparison: I did find an older log which seems to have the same problem with the MTU - but did work without stutter:

[Moonlight-1619308567.log](https://github.com/moonlight-stream/moonlight-qt/files/6382496/Moonlight-1619308567.log)

**Comment by koshisan** [comment]
Anything I can do on my side to provide additional information?

Additional things I tried meanwhile without success:

* Disabeling all VPN adapters on client
* Changing to WiFi connection on client
* Switching to very low bitrates
* netsh int ip reset on both client and server (MTU still reported incorrectly/different from Windows)

**Comment by cgutman** [comment]
These issues are notoriously tricky to diagnose. You could downgrade to GFE 3.21 and collect host-side logs with the 2.2.0 and 3.1.1 so we can see if there's some difference in the streaming parameters that might be causing extra packet loss.

To downgrade, you'll have to uninstall GeForce Experience, then install GFE 3.21 from this link: https://ota-downloads.nvidia.com/ota/GeForce_Experience_Update_v3.21.0.36_Official_AED7C0.exe

You'll also need to modify your hosts file to add an entry to your hosts file to stop GFE from auto updating:
`127.0.0.1 ota.nvidia.com`

Once that's done:
1. Use Moonlight 2.2.0 to start a stream, let the stream run for a couple minutes, then quit the stream within Moonlight.
2. On your host PC, collect `C:\ProgramData\NVIDIA Corporation\NvStream\NvStreamerCurrent.log` (name it NvStreamerCurrent-2.2.0.log or something)
3. Next use Moonlight 3.1.1 to start a stream, let the stream run for a couple minutes, then quit the stream within Moonlight again.
4. Collect `C:\ProgramData\NVIDIA Corporation\NvStream\NvStreamerCurrent.log` (name it NvStreamerCurrent-3.1.1.log)

**Comment by cgutman** [comment]
Actually never mind that for now. I have something else for you to try.

Download the latest build from https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/38961104/job/5uqqlb0c4e9wnkrk/artifacts

1. Extract and run the build of Moonlight linked above
2. Pair with your host PC and adjust your streaming resolution options in the Moonlight settings
3. Close Moonlight
4. Inside the Moonlight portable folder you extracted, open `Moonlight Game Streaming Project\Moonlight.ini` in notepad
5. Change the line that says `packetsize=0` to `packetsize=1392`, then save and close Moonlight.ini
6. Reopen that build of Moonlight and try streaming

Upload the Moonlight logs from your test (whether it's successful or not).

**Comment by koshisan** [comment]
Nailed it! It is a day and night difference!

[Moonlight-1619847943.log](https://github.com/moonlight-stream/moonlight-qt/files/6408966/Moonlight-1619847943.log)

I guess the parameter overrides the autodetection of the MTU size? 

Can this be integrated into the Android Client also?

**Comment by cgutman** [comment]
Excellent. So the problem was indeed the VPN detection because of your MTU, but it didn't begin causing problems until v3.0.0. The reason it started in v3.0.0 was a fix to disable QoS tagging of packets over VPNs and the Internet. This is necessary to avoid problems with some broken ISP hardware that drops QoS tagged packets and results in being completely unable to stream at all from networks like that. Unfortunately, it looks like your router heavily relies on those QoS tags to treat the Moonlight traffic as high priority.

I can't revert that change because it will reintroduce that bug, but you can continue to use the `packetsize` workaround. I suspect that there's something odd about your network that triggers the lower than expected MTU size (perhaps an errant IPv6 router advertisement with a 1472 MTU or something).

However, all that said, I don't think this is the same issue as Android. Android doesn't allow access to the MTU. Instead we can directly ask the OS whether we're connected with a VPN in the code https://github.com/moonlight-stream/moonlight-android/blob/823593ddae0b0b2f1a8fcfdf29665b4d834d9c26/app/src/main/java/com/limelight/utils/NetHelper.java#L11-L30

If you start a stream from your Android device and send me the host PC logs from `C:\ProgramData\NVIDIA Corporation\NvStream\NvStreamerCurrent.log`, I can confirm whether QoS tagging is enabled or not.

**Comment by koshisan** [comment]
No need - thanks to your description I was able to figure this one out myself: My Android device does report it is connected to a VPN because it is. My company's mailserver is only reachable with a VPN, therefore my phone is connected all of the time. This is also a split tunnel, so the Moonlight packets aren't routed through the tunnel, but if you are just getting the VPN info from the OS, it will report the active connection. Disabling the tunnel/using another Android device does indeed solve the problem!

If I may add one suggestion:
Wouldn't it be easier to check if the IP Moonlight is connecting to is within the range of reserved, private IP addresses and use this to toggle QoS? This way you can use the same code on both platforms and should have a reliable detection if data is actually routed through the internet. This would enable QoS on WAN VPN links, since they also use reserved IP addresses, but they also do support QoS most of the time - worst case they should ignore it, not drop it...

While it is clearly an error with my network setup here (I suspect the Deco Mesh WIFI), it is not unheard of to run local Network Interfaces with modified MTUs...

**Comment by cgutman** [comment]
Moonlight does check if the host's IP address is in the RFC 1918 range when it chooses to enable QoS tagging, however the reason for the VPN check is because we don't want to treat a VPN as a LAN. We have seen problems in the past caused by MTU issues and QoS tagging on VPNs and other WAN traffic. Unfortunately what they "should" do with DSCP tagged traffic doesn't always match what they actually do (see this research paper: https://www.sciencedirect.com/science/article/pii/S0140366417312835).

The risk/benefit analysis here favors us being more aggressive with disabling QoS. QoS tagging doesn't usually make a big performance difference in most LANs, yet the penalty for using QoS tagging in an intolerant environment is the complete inability to stream.

There is more we could do though with the newer Android APIs to identify the correct network that our traffic is traversing (to avoid your split-tunnel VPN issue).

**Comment by koshisan** [comment]
Too bad - and I thought I had a good idea ;)
But if that is the case this issue is closed - or do you wan't to keep it open until the Android change is implemented?
For PC I will keep using the ini parameter.

Thank you very much for your support :)
