### ISSUE TITLE
question about reed-solomon

### ISSUE THREAD

**Issue by HongZhouyang** [moonlight-stream/moonlight-qt#605]
I want to find about reedsolomon encoding, but in this project we have only decoding part.  Can you give some clue on where can I find code that achieves reedsolomon encoding. Thank ya again, ~ big god ~

**Comment by cgutman** [comment]
Moonlight never needs to encode any data using Reed-Solomon, since it is only receiving audio and video data from the host.

If you want a reference to encoding, you can look at the [Sunshine](https://github.com/loki-47-6F-64/sunshine/) project which is a FOSS server for Moonlight.

https://github.com/loki-47-6F-64/sunshine/blob/fd43ebc2bf52282e7bfb213d74181d6e4877c570/sunshine/stream.cpp#L317-L362

**Comment by HongZhouyang** [comment]
Yes it does! Please search
 "ret = reed_solomon_reconstruct(rs, packets, marks, totalPackets, receiveSize);" 
on file "moonlight-common-c/src/RtpFecQueue.c" Line 233.
 I am sure Moonlight used it to prevent packet loss.
However thank ya big-god。

**Comment by HongZhouyang** [comment]
OKKKKK   thank yaaaaa   big-god
