### ISSUE TITLE
Request for modifying stream ports

### ISSUE THREAD

**Issue by FeverKing** [moonlight-stream/moonlight-qt#611]
I'm always frustrated when using frp and cannot connect to the port I set.
So I want to modify the ports myself, but I can't find it in moonlight settings.
I think you can add an option for user to set the port to connect.
This is a great work, thank you guys anyway.

**Comment by cgutman** [comment]
Supporting modifying ports is more complex than it would seem on the surface.

There are 3 separate types of addresses that Moonlight tracks for every PC: WAN, LAN, and Manual (arbitrary, could be VPN or something else). Even when you add the PC with one address, Moonlight is always keeping track of any others it can find, to allow you to seamlessly roam between LAN, WAN, VPN, and other networks you may use while keeping connectivity with your host.

GameStream uses significantly more ports than many protocols which might only use 1 or 2. GameStream requires 6 separate ports for streaming. Since ports can differ for each address (especially WAN vs LAN due to NAT) that means each address requires its own set of 6 ports. Since NATs may not be able to allocate ports sequentially, we couldn't just use a central port number and offset to find each of the other ports.

The result is that we'd basically need the user to fill out a huge 3x6 matrix for every one of their PCs, which is incredibly tedious and error prone. Instead, I've chosen to let the host software indicate the ports to Moonlight via the GameStream protocol itself. It's not a perfect solution, but it allows dynamic ports to work seamlessly on WAN and LAN.

[Sunshine](https://github.com/loki-47-6F-64/sunshine) will support this soon. Moonlight can connect to Sunshine on a custom port by using mDNS or specifying an `address:port` in the Add PC dialog.
