### ISSUE TITLE
moonlight.exe cmd argument (fullscreen)

### ISSUE THREAD

**Issue by goodandrewsoft** [moonlight-stream/moonlight-qt#618]
1. How run moonlight.exe gui in fullscreen ? Any cmd arguments?

![image](https://user-images.githubusercontent.com/2471892/123546561-c1525800-d765-11eb-8859-b062e122e676.png)

Any idea, how run moonlight.exe from Kodi (like theater version)?

**Comment by cgutman** [comment]
There is currently no command-line argument to change the GUI display mode. The thinking was that it wasn't required, since users that want the GUI can just adjust the setting in the GUI. The only parts of the GUI that even appear during a CLI initiated stream is the loading indicator when the stream starts, so it didn't seem like much of a problem. What's your use case for it?

How are you attempting to use Moonlight from Kodi? Do you just want to launch the Moonlight GUI? If so, just run Moonlight.exe with no arguments. If you want to launch a specific app, you can use the `Moonlight stream` command.

**Comment by goodandrewsoft** [comment]
> What's your use case for it?
1. Run from desktop as normal window app..
2. Run from kodi as fullscreen app (so, because i need --fullscreen cmd argument)
