### ISSUE TITLE
Moonlight stream on Plasma Wayland is bad, fine on X11

### ISSUE THREAD

**Issue by Tromzy** [moonlight-stream/moonlight-qt#625]
When I use Moonlight-qt on Plasma in a Wayland session, the stream has very poor quality, colors are bad and sound crackles a lot. When I use it in a Plasma X.org session, everything is fine. It looks like it does not use some harware acceleration on Wayland ? Which is too bad because it seems snappier, though.

Client PC details

    OS: Arch Linux
    Moonlight Version: 3.1.4
    GPU: AMD Ryzen 4300U graphics

Server PC details

    OS: Windows 10
    GeForce Experience version: latest
    Nvidia GPU driver: latest

**Comment by Tromzy** [comment]
When I use Moonlight-qt on Plasma in a Wayland session, the stream has very poor quality, colors are bad and sound crackles a lot. When I use it in a Plasma X.org session, everything is fine. It looks like it does not use some harware acceleration on Wayland ? Which is too bad because it seems snappier, though.

**Comment by pm16** [comment]
When using the flatpack 3.1.4 version in Wayland there are noticeable problems with color gradients. Color banding might describe what is happening. I've attached a screenshot that shows what the problem looks like. I don't have this problem using the same host with the windows client. The issue is really noticeable in the full size screenshot.
![Screenshot_20210807_080005](https://user-images.githubusercontent.com/13075367/128601057-243c0d87-c75d-4d53-8510-224ca06f6868.png)

Client info:
Operating System: Fedora 34
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Kernel Version: 5.13.6-200.fc34.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 PRO 4750U with Radeon Graphics
Memory: 29.1 GiB of RAM
Graphics Processor: AMD RENOIR

**Comment by cgutman** [comment]
Do you see this banding in other VAAPI enabled apps running on Wayland (not XWayland)?

**Comment by vampywiz17** [comment]
My problem is connected this issue.

I affect this problem: https://github.com/moonlight-stream/moonlight-qt/issues/397

So i use `QT_QPA_PLATFORM=xcb` In this case, the window mode is working, but no HW decode... Any option, to use HW decode, Wayland (or Xwayland) in window mode? the X11 is not option from me.
