### ISSUE TITLE
Command + Tab in macOS

### ISSUE THREAD

**Issue by animaion** [moonlight-stream/moonlight-qt#650]
Please make Command+Tab macOS shortcut working in fullscreen mode for switching between Moonlight/Windows window and macOS apps.

**Comment by cgutman** [comment]
It works if you use borderless windowed mode (which is the default "fullscreen" mode on macOS). The tooltip for the window mode also mentions this.

It is blocked by macOS in "true" fullscreen mode by design

**Comment by animaion** [comment]
There are two options now:
1. In borderless windowed mode a Command+Tab works for macOS app switching but Command key does not work for Windows.
2. In fullscreen mode Command key works in Windows but Command+Tab does not work for switching macOS apps
In both cases the workflow is broken.

**Comment by cgutman** [comment]
Using fullscreen mode to get system keyboard shortcut capture is definitely not recommended. It's a kludge at best. That mode is really designed for situations where you need to change the display mode for streaming (such as using a higher refresh rate).

If you would like to pass system keyboard shortcuts like Command+Tab to the host, enable the "Capture system keyboard shortcuts" checkbox in the settings page.

To interact with the system again, you can either press Ctrl+Alt+Shift+Z to unbind the keyboard and mouse from Moonlight and use Command+Tab (or any other key combo) normally, or press Ctrl+Alt+Shift+D to minimize the streaming window. You can also use the normal macOS 3-finger swipe trackpad gestures to switch between Moonlight and other applications (my personal favorite).

> In borderless windowed mode a Command+Tab works for macOS app switching but Command key does not work for Windows.

That's because we have no way of knowing the user's intention. Maybe you meant for Command+Tab to trigger Win+Tab on the host PC? Maybe you pressed it to switch apps on the client PC? There's no way for Moonlight to know which one you intended.

That's why we have the "Capture system keyboard shortcuts" option and unbind key combo. It lets you pick where you want your keyboard input going.

**Comment by animaion** [comment]
> That's because we have no way of knowing the user's intention. Maybe you meant for Command+Tab to trigger Win+Tab on the host PC? Maybe you pressed it to switch apps on the client PC? There's no way for Moonlight to know which one you intended.

Moonlight does not need to know what the user wants at all. It just would be great to have OPTION to use Command+Tab combination **ALWAYS** for macOS app switching (from Moonlight window to other apps). This way the running Windows app in Moonlight window would behaves as macOS app from Mac user point of view. Command+Tab is absolutely essential combination in macOS. Using Ctrl+Alt+Shift+Z or any other keys combinations is not good solution – it ruins workflow. At the moment I click with mouse to a second display space and the use Command+Tab to switch from Moonlight (Windows app) to different Mac app. You may laugh, but that one extra action really does significantly degrade Moonlight's use if you have to switch between apps dozens or hundreds of times a day.

**Comment by cgutman** [comment]
> Moonlight does not need to know what the user wants at all. It just would be great to have OPTION to use Command+Tab combination ALWAYS for macOS app switching (from Moonlight window to other apps) however Command key alone should be usable in Windows. 

The problem is that Moonlight has to decide whether to send the keystroke to the host at the moment when it gets the Command key event. It doesn't know whether the Command key will be followed by a Tab key event.

> For example: at the moment in borderless windowed mode I click with mouse to a second display space and then I use Command+Tab to switch from Moonlight (Windows app) to different Mac app.

Moonlight should relinquish keyboard grab when it loses input focus (like when you click on a different window).

I don't have a second monitor handy at the moment, but I launched Moonlight in windowed mode with system key capture and remote desktop mouse mode enabled. When focus was on the Moonlight window, Cmd+Tab went to the host PC, but when I clicked on an empty space outside the window (changing focus to Finder), Cmd+Tab went to macOS, as expected.

Is that not the behavior you're seeing?

**Comment by animaion** [comment]
> The problem is that Moonlight has to decide whether to send the keystroke to the host at the moment when it gets the Command key event. It doesn't know whether the Command key will be followed by a Tab key event.

I understand. I was afraid it was like that.

> Is that not the behavior you're seeing?

What I am looking for is: when I'm working in Moonlight windows, Cmd+Tab shows macOS app switcher and I can directly switch from Windows app to Mac app and vice versa. I have remapped LWin to LCtrl key in Windows so I can use Magic Keyboard just like in macOS (copy, paste etc.) – I have to use Cmd (remapped Ctrl) key in Windows ('Capture system keyboard shortcuts' option is ON).

**Comment by zurce** [comment]
@animaion can we make it so in Mac the left command always respond to system calls? 

As it is right now, when Capture system keyboard shortcuts is turn off, right command does act as windows key on windows, allowing you to use the left command for Mac OS

If we had the option to keep the right command as always listening to Mac OS ,then if `Capture system keyboard shortcuts` option is on, we can exit whenever we want using the right side command + tab

**Comment by animaion** [comment]
I think it won't change much, but it won't hurt either. Perhaps someone find it useful.
Muscle memory is assigned to LCmd + Tab for apps switching so the 'problem' still remain.

**Comment by zurce** [comment]
Yes this is mostly for muscle memory improvements, since when i wanna do stuff on windows with that key i keep switching windows on mac instead of windows (win+tab)
