### ISSUE TITLE
Error try build "moonlight" in windows

### ISSUE THREAD

**Issue by levioase** [moonlight-stream/moonlight-qt#671]
following the readme of project, after run command "git submodule update --init --recursive", i receive this error:
![Captura de Tela (1)](https://user-images.githubusercontent.com/93149471/141347807-93536c7d-6b7e-4130-9296-242ac9cb0b65.png)

how can i solve that error?

**Comment by cgutman** [comment]
It looks like you're building with MinGW instead of MSVC, so you're missing a bunch of headers and definitions that Moonlight requires. Rerun the Qt Maintenance Tool, uncheck the MinGW build of Qt and check the MSVC 2019 version, install Visual Studio 2019+ (if you haven't already), then try building again.
