### ISSUE TITLE
gamecontrollerdb.txt overwrite if edited (impossible to configure new controller)

### ISSUE THREAD

**Issue by salaroli** [moonlight-stream/moonlight-qt#681]
**Describe the bug**
`moonlight-qt` use `gamecontrollerdb.txt` for input configuration. This file lives on `~/.cache/Moonlight\ Game\ Streaming\ Project/Moonlight/gamecontrollerdb.txt`
If you want to configure a new controller that its not on the file (in my case, Mad Catz Brawlstick for Xbox 360), you should be able to edit the file to add the new configuration.
There is no way to overwrite this file, because if you do, when you start `moonlight-qt`, it downloads a the old `gamecontrollerdb.txt` and overwrite the new one you just created

**Steps to reproduce**
Try to edit the file in `~/.cache/Moonlight\ Game\ Streaming\ Project/Moonlight/gamecontrollerdb.txt`, start `moolight-qt`, look at the file again

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
  - Yes, Mad Catz Brawlstick for Xbox 360
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - This whole story begins because I have a weird behavior with this particular gamepad, some inputs are shifted. When I connect to https://html5gamepad.com it behaves the same weird way. I used SDL2 to remap this input and pass to moonlight, but the output should be written on `gamecontrollerdb.txt`, that have the issue I'm reporting

**Client PC details (please complete the following information)**
 - OS: Raspbian Buster
 - Moonlight Version: latest? Just installed on my Raspberry Pi 4
 - GPU: n/a

**Other info**

This was discussed on the official Discord, on this thread:
https://discord.com/channels/352065098472488960/912882973009932338

**Comment by cgutman** [comment]
This happens because Raspbian Buster has an older version of Qt that doesn't support the `IfModifiedSince` header.

https://github.com/moonlight-stream/moonlight-qt/blob/4de3aa96b67412870aaabcaafa3c35d8cc0f7f02/app/settings/mappingfetcher.cpp#L39-L57

I guess we're stuck supporting Qt 5.9 for a while, so maybe it's worth implementing that for older Qt versions.

In any case, I encourage you to submit your new mapping to the [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) project, which is where Moonlight and many other games get gamepad mappings. If you do that, I can pull in those changes in Moonlight's copy and it will automatically start working without you needing to manually map it.
