### ISSUE TITLE
Is it possible to encode HEVC by Intel graphics card?

### ISSUE THREAD

**Issue by SerLinux** [moonlight-stream/moonlight-qt#683]
I have a graphics card with GTX 1650 (TU 117) core. It is known that this graphics card does not support HEVC B Frame encoding, so I cannot enable HEVC on my client.
But besides that, I have an Intel core graphics card (UHD 630). Is there a way to use UHD 630 to encode HEVC B Frame? Grateful!
My CPU: Intel Core i7 9750H
GPU driver: 496.76

**Comment by cgutman** [comment]
The GTX 1650 _does_ have HEVC encoding support, but it is not working with GameStream due to either a bug in the drivers or a bug in GeForce Experience. B frame support is not required for HEVC streaming with GameStream (Maxwell and Pascal GPUs can stream HEVC without B frames). You could try to file an issue with Nvidia to try to get it fixed if you want.

As for using your Intel GPU, it's not possible to use an alternate GPU for encoding with GeForce Experience.
