### ISSUE TITLE
Unable to install on Raspian (bullseye) following instructions.

### ISSUE THREAD

**Issue by zulrang** [moonlight-stream/moonlight-qt#690]
**Describe the bug**
Following the install instructions on Raspian bullseye results in "E: Unable to locate package moonlight-qt"
https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4

**Steps to reproduce**
```
$ curl -1sLf 'https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh' | distro=raspbian codename=buster sudo -E bash
Executing the  setup script for the 'moonlight-game-streaming/moonlight-qt' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
   OK: Importing 'moonlight-game-streaming/moonlight-qt' repository GPG key into apt ...
   OK: Checking if upstream install config is OK ...
   OK: Installing 'moonlight-game-streaming/moonlight-qt' repository via apt ...
   OK: Updating apt repository metadata cache ...
   OK: The repository has been installed successfully - You're ready to rock!

$ sudo apt update
Hit:1 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports hirsute-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease
Get:5 https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/deb/raspbian buster InRelease [5072 B]
Fetched 5072 B in 2s (2099 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

$ sudo apt install moonlight-qt
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package moonlight-qt
```

 - OS: Raspian (bullseye) Linux moonlight 5.11.0-1015-raspi 16-Ubuntu SMP PREEMPT Wed Jul 14 11:04:58 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
 - Moonlight Version: N/A
 - GPU: N/A

**Comment by zulrang** [comment]
It looks like there are no package in the repo:
```
$ grep ^Package: /var/lib/apt/lists/dl.cloudsmith.io_public_moonlight-game-streaming_moonlight-qt_deb_raspbian_dists_buster_InRelease
$ 
```

**Comment by cgutman** [comment]
Yep, this is because you're using the 64-bit version of Raspbian. 64-bit Raspbian doesn't support MMAL, which means no low latency hardware decoding (especially in a window with X running). MMAL overlays are critical to get good performance on the Pi, since OpenGL on the Pi GPU is too slow to do 1080p60 and can just barely manage 720p60.

In theory, the changes required to support Raspbian Bullseye and the Full KMS driver should benefit your case here. Bullseye is no longer shipping MMAL libraries out of the box (and rendering via MMAL wouldn't work anyway due to Full KMS). That means we'll need to use the standard V4L2 APIs for decoding and OpenGL for rendering. Getting rid of the Raspberry Pi-specific code is great in theory, but in practice it seems impossible to get the same performance out of V4L2+GL as we did from MMAL.

If you want to play with it, it should possible to build Moonlight Qt for aarch64 with a [custom patched FFmpeg](https://github.com/cgutman/FFmpeg/commits/moonlight-rpi_4_4_1) to get okay performance (not as good as MMAL yet) as long as you run it from the console directly (not inside X).

**Comment by zulrang** [comment]
Thanks for the detailed (and quick) response.

Okay so the solution here is to use 32-bit Raspbian?  Would it also be easier to go back to Buster?

**Comment by cgutman** [comment]
You can use either Bullseye or Buster as long as it's 32-bit. If you choose Bullseye, you'll need to adjust your `/boot/config.txt` per the instructions on the wiki to get video to display properly.

**Comment by cgutman** [comment]
For the 64-bit side of things, that is tracked by #570

**Comment by zulrang** [comment]
I tried a fresh install of Buster 32-bit, followed the instructions, and am met with this:
```
mmalipc: mmal_vc_init_fd: failed to initialise vchiq
mmal: mmal_vc_component_create: failed to initialise mmal ipc for 'vc.ril.video_render' (7:EIO)
mmal: mmal_component_create_core:  could not create component 'vc.ril.video_render' (7)
00:00:02 - SDL Error (0): mmal_component_create() failed: 7 (EIO)
```
I can't find any info on anyone having a similar issue.   I asked on Discord and got no replies. Hopefully you may be able to point me in the right direction.

**Comment by cgutman** [comment]
I'd make sure everything is up to date and that you haven't done anything special to your `/boot/config.txt`. Other than that, I have no idea either.
