### ISSUE TITLE
Request for clarification on Raspberry / Bullseye documentation

### ISSUE THREAD

**Issue by esistgut** [moonlight-stream/moonlight-qt#705]
I just finished installing moonlight-qt on a Raspberry Pi 4 system using Raspberry OS Bullseye. The moonlight-qt client is using HEVC hw decoding and it is running from terminal (without X).
I'm opening this issue because I did not follow the steps on this section of the guide https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4#raspbian-bullseye and everything is working just fine. Can you please explain what is the point of using the old driver? Maybe it is related to h264 decoding? My system currently does not work if I ask moonlight-qt to use h264 and it is not working on X in any way (both hevc and h264). Maybe this section of the guide is meant to make moonlight-qt run on X/h264?
Thank you.

**Comment by cgutman** [comment]
> Can you please explain what is the point of using the old driver? Maybe it is related to h264 decoding? My system currently does not work if I ask moonlight-qt to use h264 and it is not working on X in any way (both hevc and h264). Maybe this section of the guide is meant to make moonlight-qt run on X/h264?

Yes, the Firmware KMS driver is required for H.264 decoding. MMAL is the only current way to render H.264 video inside X that is performant enough on the Raspberry Pi, and those overlays require Firmware KMS (they silently fail on the Full KMS driver). Using V4L2+GL isn't fast enough to sustain 1080p 60 FPS, so MMAL is our only feasible choice. I'm still trying to get GL to perform acceptably, but I haven't had any luck yet.

Not all host GPUs support encoding HEVC (only 900-series and later do), so you'd just randomly end up with a black screen trying to stream from certain PCs. Moonlight Qt v3.1.4 doesn't detect when MMAL is unavailable due to Full KMS, so you'd have no warning or indication of what was going wrong.

Moonlight Qt master does detect this case now and will refuse to use MMAL with Full KMS enabled. This will cause a fallback to software decoding, rather than just a black screen, and will provide a launch warning to indicate the problem.

**Comment by esistgut** [comment]
I'm currently using HEVC decoding for 1440p streaming from sunshine. I would like to test 2560x1440 streaming on my first monitor while keeping Xfce running on a second 1920x1080 monitor. Could this be possible using h264 MMAL streaming?

**Comment by cgutman** [comment]
Hmm, I haven't actually tested multiple monitors before on the Pi. There's more that needs to be done to handle the MMAL overlay showing on the non-primary display, but it should be possible.

There is a limitation of 1080p 60 FPS on the Pi 4's H.264 decoder, so 2560x1440 won't work. 1080p 60 FPS should theoretically work though. Depending on your use case, you may also run into issues related to the way the MMAL overlay is disabled when Moonlight is not currently in focus (even if it is visible).

**Comment by cgutman** [comment]
I have updated the documentation to clarify H.264 and provide a workaround for it, so I'm going to close this.
