### ISSUE TITLE
Right clicking on the game to QUIT GAME doesnt close the session. [PC][0.4.0 Portable]

### ISSUE THREAD

**Issue by kedirakevo** [moonlight-stream/moonlight-qt#71]
**Describe the bug**
Right clicking on the game to QUIT GAME doesnt close the session. It was working fine in the previous version. Android version is also working fine.

**Moonlight settings (please complete the following information)**
Redownloaded a fresh copy but it still doesnt work. 

**Client PC details (please complete the following information)**
 - OS: 10 1803]
 - Moonlight Version: 0.4.0 PC Portable

**Comment by cgutman** [comment]
I think I fixed this yesterday, but it hasn't been released yet.

Can you try this linked dev build? If you want to use the installer instead of the portable build, you'll need to uninstall your existing version first to prevent conflicts.

https://ci.appveyor.com/project/cgutman/moonlight-qt/build/0.0.0.216/job/j6tll4jxksqjiopc/artifacts

**Comment by kedirakevo** [comment]
Oh cool it worked. I assume this will get pushed out soon?

**Comment by cgutman** [comment]
I'm out of town for the next few days, but yes I'll release it when I'm back.

**Comment by cgutman** [comment]
Fixed in https://github.com/moonlight-stream/moonlight-qt/commit/b8169ae08b5973eeb0841a8f82a4b26c6e5a0b9f

**Comment by cgutman** [comment]
Fix released in v0.5.0 (Beta 2).
