### ISSUE TITLE
Performance overlay not displaying properly on Linux

### ISSUE THREAD

**Issue by JPenuchot** [moonlight-stream/moonlight-qt#721]
**Describe the bug**

Performance overlay text doesn't display properly, as if the strides were shifted.

**Steps to reproduce**

`CTRL+ALT+SHIFT+S`

**Screenshots**

![](https://i.imgur.com/ffShvb6.jpg)

**Moonlight settings (please complete the following information)**

Default settings, 1080p streaming on both server and client, no resize.

**Client PC details (please complete the following information)**
 - OS: ArchLinux
 - Moonlight Version: 3.20
 - GPU: Intel HD Graphics 520

**Server PC details (please complete the following information)**
 - OS: ArchLinux
 - Sunshine version: 0.11.1
 - Nvidia GPU driver: 495.46

**Moonlight Logs (please attach)**

[moonlight-log.txt](https://github.com/moonlight-stream/moonlight-qt/files/7904470/moonlight-log.txt)

**Additional context**

Both client and server are running Xorg.

**Comment by cgutman** [comment]
Hmm, I've never seen that before. AFAICT, the surface containing our overlay text should be tightly packed, making it safe to `glTexImage2D()` it without having pitch-related issues like what it looks like here. I have very similar hardware (HD 620) on Fedora 35 and it doesn't reproduce for me.

A few things to try to narrow down the cause:
- Does it happen if you force software decoding?
- Does it happen if you try the AppImage?
- Does it happen if you try the Flatpak or Snap?
- Did it happen with Moonlight v3.1.4?

**Comment by JPenuchot** [comment]
>     * Does it happen if you force software decoding?

I'm getting a black screen when using software decoding.
[moonlight-log-software.txt](https://github.com/moonlight-stream/moonlight-qt/files/7907146/moonlight-log-software.txt)

I tried using SW decoding on the AppImage and had the same issue.

>     * Does it happen if you try the AppImage?

Performance overlay won't display at all.

>     * Does it happen if you try the Flatpak or Snap?

I can't tell you until I get home because I have to reconfigure Moonlight since the Flatpak version has a separate config.

>     * Did it happen with Moonlight v3.1.4?

Never happened, I've been using the performance overlay successfully with that version.

I'm using Moonlight through that AUR package: https://aur.archlinux.org/packages/moonlight-qt/

**Comment by cgutman** [comment]
OK, I understand all the weirdness going on.

The reason the overlay rendering is broken is actually not related to the Moonlight v3.2.0 update at all. It's caused by SDL_ttf 2.0.18, which was recently picked up by Arch. With SDL_ttf 2.0.15, we always got a tightly packed surface, but SDL_ttf 2.0.18 now gives us a surface that is SIMD-aligned (thus not tightly packed).

EGLRenderer does not handle this case properly, so the texture is mangled during upload by GL which is assuming the pitch is equal to the width. This bug has existed since the EGLRenderer itself was written back in May of 2020. It just wasn't caught until now because SDL_ttf was always giving us tightly packed surfaces before.

Anyway, this is fixed by https://github.com/moonlight-stream/moonlight-qt/commit/dd941154d695fa4b091b5bf4ef08f8e3e5360fda. You can pick up the fix with `moonlight-qt-git` and/or ask the AUR maintainer of `moonlight-qt` to include that patch.

> I'm getting a black screen when using software decoding.

That's most likely a Sunshine bug. It appears to be sending a corrupt H.264 SPS that the software decoder rejects.

> Performance overlay won't display at all.

Indeed, the AppImage build uses much older libraries (Ubuntu 18.04) which I think have broken EGL support. You end up with the VAAPI direct renderer which does not support overlays.

> I can't tell you until I get home because I have to reconfigure Moonlight since the Flatpak version has a separate config.

Those will both work, because they are using SDL_ttf 2.0.15 included in the runtime.

**Comment by JPenuchot** [comment]
Wonderful, thanks a lot! :)
