### ISSUE TITLE
Mouse dragging if moved out of window on Windows / mouse lock feature

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#737]
Following issue in a lot of games, that if you use Moonlight client in a window, and move out the mouse cursor, the game interpreters this as mouse being dragged against the corners of the screen and scroll into that direction.

Please change it either that if you drag mouse out of the Moonlight window, that the mouse cursor gets reset into the middle of the screen, or give an option (better both implemented), to lock mouse cursor into the moonlight window, and you cant drag out of the window, except you press tab for example.

**Comment by cgutman** [comment]
> Please change it either that if you drag mouse out of the Moonlight window, that the mouse cursor gets reset into the middle of the screen 

This is an interesting idea. I took a stab at this and there are some problems with the approach. Not all Moonlight platforms allow this behavior to be implemented reliably because they don't allow the mouse position to be tracked outside the window. This is the case for macOS and Wayland.

>  or give an option (better both implemented), to lock mouse cursor into the moonlight window, and you cant drag out of the window, except you press tab for example.

Well the idea is that you'd use the normal mouse capture mode for gaming like this, since it behaves in exactly this way. Remote desktop mouse mode is designed to allow seamless entry and exit into the window.

**Comment by makedir** [comment]
Please implement both, and make it just optional as setting. Lock also please. I want to play in window mode where window mode is below screen size, I am using a 4k laptop, and  I want to have a lock feature, to prevent mouse to leave the window, except I manually press tab for example.

**Comment by cgutman** [comment]
> Please implement both, and make it just optional as setting.

Options like this are not free of development and maintenance cost. The more obscure options we have, the greater the odds that one unexpectedly breaks during unrelated changes. It is also a challenge to explain to users why the option doesn't work for them, especially for Linux where it may work or not work depending on which desktop session they use when logging in.

Of course none of these are insurmountable challenges, but it's a question of whether the benefit outweighs the cost. Since it's not possible to do for all platforms and we do have an existing mouse mode that locks the mouse, I don't think it's worthwhile to implement this additional option.

> I want to play in window mode where window mode is below screen size, I am using a 4k laptop, and I want to have a lock feature, to prevent mouse to leave the window, except I manually press tab for example.

This already exists with the non-remote desktop mouse mode. The key combo to unbind input is Ctrl+Alt+Shift+Z.

**Comment by makedir** [comment]
No it does not exist. Please implement a lock function, make it optional. I said why it matters, and it is important. Every normal app like this has a lock function.

**Comment by cgutman** [comment]
I introduced a key combo Ctrl+Alt+Shift+L that locks the cursor to the video area

**Comment by makedir** [comment]
@cgutman Thank you very much! Can you please implement a gui, where you can change all shortcuts? That way you can also see them, which is still lacking in Moonlight. I would like to change a few of them to other combos.
