### ISSUE TITLE
Gamestream in Background

### ISSUE THREAD

**Issue by o0TheRat1010o** [moonlight-stream/moonlight-qt#740]
Hey : )

is there any way to stream Games to an other device while I've bin working on the Host Computer. Game streaming via Moonlight is working.
Is there any way to make this work in Background? Multiuser, Sandbox, Multi-Desktop?

Every concrete Idea is welcome. Host Computer has more than enough power ;)

Best Regards

**Comment by cgutman** [comment]
I've done it via virtual machines. I use a host running several GameStream-compatible GPUs and ESXi. I believe some others have had success with Proxmox too.

**Comment by o0TheRat1010o** [comment]
> I've done it via virtual machines. I use a host running several GameStream-compatible GPUs and ESXi. I believe some others have had success with Proxmox too.


Yes you are right. After tons of Websites i found it that way, too. I created a Virtual Machine via Hyper V and connected the Network "external" to the Router. Then i found that tutorial to !SHARE! the Graphiccard.

https://forum.level1techs.com/t/2-gamers-1-gpu-with-hyper-v-gpu-p-gpu-partitioning-finally-made-possible-with-hyperv/172234

It worked without any Problems on my RTX 3090.
I writeed myself a little Batch (included FreeFileSync) for oneclick Updating the Driver on the VM:
1. Give the VM Readonly access to the Driver Files on the Host.
2. Create FreeFileSync batch with the File-Rules in the Link mirrowing to the VM.
3. Create Windows Batchfile to start the FreeFileSync Batch in Admin-Mode
4. Important: Set "LockDirectoriesDuringSync" in FreeFileSync to false


Now you have to connect the VM remotly (i preffere Moonlight) like on any other Computer before.

I can work, play, what ever i want on my Computer and the user on the virtual Machine can do the same.
"I Spy" Benchmark working really well. Host on 4K and Virtual on Full HD. Both on Maximum Settings. Host never under 60 fps (~100-120 fps). VM never under 40 fps (~60-80 fps).
Seems like the Host will always be preferred and the VM´s will get the rest.

**Comment by mohammadmansur** [comment]
Hi, @o0TheRat1010o. I got this solution working using this tutorial:
https://www.tenforums.com/virtualization/195
![image](https://user-images.githubusercontent.com/11576240/216645029-fbc5e23b-667e-4672-825d-c6e7088aeccf.png)
745-tutorial-passing-through-gpu-hyper-v-guest-vm.html

I've got it working to the extent that I have the VM sharing the RTX 3060 with my Host. However, I'm stuck with 2 problems:

1. I can't use Enhanced Mode on Hyper V. If I do, Moonlight starts terminating sessions. The moment I turn off Enhanced mode on hyper V, Moonlight starts connecting

**Comment by mohammadmansur** [comment]
Hi, @o0TheRat1010o. I got this solution working using this tutorial:
https://www.tenforums.com/virtualization/195745-tutorial-passing-through-gpu-hyper-v-guest-vm.html

I've got it working to the extent that I have the VM sharing the RTX 3060 with my Host. However, I'm stuck with 2 problems:

1. I can't use Enhanced Mode on Hyper V. If I do, Moonlight starts terminating sessions. The moment I turn off Enhanced mode on hyper V, Moonlight starts connecting fine. The Sunshine/Moonlight combo works perfectly when connecting directly to the host, but connecting to the VM only works when Enhanced mode is turned off. That's a problem because I need Enhanced Mode to access resources of the host and also because the mouse behaves funny in Basic Mode. 

2. Hyper V prefers to use my Radeon iGPU instead of my RTX dGPU. The only way to force the VM to use the dGPU is to disable the Radeon on the host before booting the VM, and then enabling it back again. This is very inconvenient. 

Do you have any suggestions / work arounds for this?

**Comment by o0TheRat1010o** [comment]
Hi @mohammadmansur.
I'm not an expert in Hyper-V, but let's take a look.

1. I had some issues with working on the VM via Moonlight, too. I don't know if Moonlight supports the Enhanced Mode, because it's more specialized on game streaming. Because of that i have switched to https://parsec.app/
It's easier to connect and there are some more build in futures for optimal usage like and audio driver, a automatic fallback, if there is no monitor connected and a connection on the go via the website as well.
You can try parsec if that solves you problem. Otherwise i think i would connect the local storages or other things via a "network connection" to the host computer. You can create "virtual devices" on your VM that are linked to the devices you need. For USB connections, there exist some third party software to tunneling them to the VM.

2. So i think you want to use the Radeon driver on your host computer? I don't know exactly if your tutorial is other than mine. But the first i would check is: if i could separate the driver files that has been copied to the virtual machine, to not coping the files for the iGPU.
An other way is: you maybe can deactivate or uninstall the Radeon in the Device-Manager of the VM? This should not have any affect to the host computer.

Hope that helps :)

Best regards

**Comment by mohammadmansur** [comment]
Hey thanks for the response. I've figured out 2 and now I can force my VM to use my Nvidia RTX 3060.

I've also switched to Parsec, but I'm having the following issues:

1. In Enhanced Session mode I get a black blank screen, even though I know I get connected because my I can control the mouse on the VM from my Android Parsec client .
2. I can connect without the Enahced Session mode, and it works headless too (with the VM not connected on the host, but then I have no audio driver installed, so there's no sound. 

Do you think I can create a 'virtual sound card' that utilizes my host sound card?

**Comment by o0TheRat1010o** [comment]
@mohammadmansur 
1. Sorry i have no explain for that. But i found this in Google: https://www.elevenforum.com/t/windows-11-and-hyper-v-enhanced-session.8/

You can try post #17:
"If using MS account and enhanced mode, "Require Windows Hello sign-in for Microsoft accounts" must be OFF.
Settings > Accounts > Sign-in options.

Windows Hello is for local logins only.

.... "


2. That should not be a big deal. I would recommend you to download "virtual audio cable" and install it on the VM.
https://vb-audio.com/Cable/index.htm?gclid=CjwKCAiAxP2eBhBiEiwA5puhNY7H7hSAs7z8d4hb6yfo84JH0P5_SFAMPLdlqJ9ETXCdihnfiUj9GxoCFT8QAvD_BwE
It's a audio driver particularly suitable for using in virtual machines. Install it on the VM and choose in Parsec >> Settings >> Host >> Audio >> Cable.
Be aware that some VM are toggle off the sound every time you log in. Just turn it on again in your windows task-bar.

**Comment by mohammadmansur** [comment]
Thanks so much, I have the audio working, and now I have the setup working in non-enahanced-session mode in both Parsec and Sunshine+Moonlight.

I know about the Windows Hello thing, that's already turned off. I believe it may have something to do with my laptop having both a Radeon iGPU and Nvidia dGPU, and the iGPU being needed to display the rendering output of the dGUP. 

I was facing black screens in Parsec because of this (but not Sunshine+Moonlight), and I had to put my laptop in MUX mode so I could display directly through the dGPU (otherwise Parsec couldn't capture video). 

This may or may not having something to do with my black screen problem in Enhanced Session mode. 


Just to clarify, you DID get parsec working fine on a VM in enhanced session mode? 

I ask because I'm starting to think that it's a yet unsolved problem (every tutorial directs to turn of Enhanced Session).

**Comment by o0TheRat1010o** [comment]
@mohammadmansur

I'm glad to hear that you got the audio working and that the setup is working in non-enhanced-session mode for Parsec and Sunshine+Moonlight.

I had no issues with Parsec in enhanced session mode when I last used it about a year ago, but things may have changed with updates. You can try going through my setup step-by-step again to see if there is a small mistake that slipped through.

In addition to the solutions I mentioned earlier, you can also try starting from scratch, following my tutorial step-by-step. Here's a summary of the other potential solutions:

1. Check drivers: Make sure all drivers are up to date, especially the graphics drivers.
2. Check virtual machine settings: Check the graphics and resolution settings in the virtual machine settings.
3. Disable hardware acceleration: Try disabling hardware acceleration in the operating system settings within the virtual machine.
4. Use an older version of Hyper-V Enhanced Mode: Check if an older version of Hyper-V Enhanced Mode is compatible with your system.
5. Disable Aero interface: Check if disabling the Aero interface in the operating system within the virtual machine fixes the problem.
6. Recopy the graphics card files: Be sure to recopy the graphics card files after every graphics card update!

Unfortunately, if none of these solutions work, it seems to be a known issue and may only be resolved by Microsoft in a future update.

Good luck, and let me know if you get it work!
