### ISSUE TITLE
Cannot WOL outside network

### ISSUE THREAD

**Issue by brutu583** [moonlight-stream/moonlight-qt#748]
I am able to WOL when i'm on my local network. However, when i am outside my local network, it doesnt work.

Any ideas?

**Comment by cgutman** [comment]
This is expected behavior of WoL due the use of broadcast traffic and the ARP timeout of your router.

Unless your PC is connected standby enabled, the entry in your router's ARP table will time out because the PC is not online to answer ARP requests from the router. Without an ARP entry, the router is unable to pass the WoL traffic to your PC from the port forward.

WoL works when on your local network because it uses broadcast traffic which doesn't require an ARP response. This is not possible over the Internet because broadcast traffic is not routable.

Some routers are smart enough to proxy WoL traffic for you if you turn on the option. Others may have the option to set a static ARP entry for your PC, which will allow the WoL traffic to reach it. If your router can do none of those things, your only option would be to run a low power device (such as a Raspberry Pi) to relay the WoL traffic.

https://superuser.com/a/1484641
