### ISSUE TITLE
Add option to enable cmd+tab

### ISSUE THREAD

**Issue by raggi** [moonlight-stream/moonlight-qt#79]
I would like to be able to easily cmd+tab to other applications. I'd like an option to keep cmd+tab working.

**Describe alternatives you've considered**
I can use the window mode switch or the mouse capture switch, but it's not as convenient.

**Comment by cgutman** [comment]
It looks like macOS purposefully avoids making Cmd+Tab available when in full-screen exclusive mode. It does work in Borderless Windowed mode, so I guess I'd use that if you want it to work.

I tried to write a trivial Cmd+Tab handler to minimize the window and return to the OS GUI, but it doesn't work because focus is immediately forced back to Moonlight for some reason.

**Comment by raggi** [comment]
Oh strange. Thanks for taking a look.

It seemed to work in the 0.2 release, but maybe that was in borderless window mode.

**Comment by cgutman** [comment]
Yep, macOS fullscreen was always borderless window mode until v0.4.0 when I added the option to switch between full-screen and borderless windowed. Full-screen became the default in that release.

You can get the old behavior with working Spaces switching and Cmd+Tab using borderless windowed.

**Comment by cgutman** [comment]
I added a tooltip for the window mode selector that notes the limitation of Alt+Tab on some platforms.
