### ISSUE TITLE
Turn off HDR on Host automatically

### ISSUE THREAD

**Issue by Maz111111** [moonlight-stream/moonlight-qt#810]
So I don´t know if this is a bug or a feature request. I try a search on github and on google but I did not find anything that fits.

I might have a strange setup:
I build my own handheld with a nacon mg-x pro and a lenovo m7. It is much cheaper then a steam desk.

It works with geforce now and moonlight basically like a charm.

the problem:

when I stream with moonlight my host pc is connected to a hdr monitor and hdr is turned on in win11 (I also stream to my shield with HDR)

When I start a stream with moonlight to the lenovo it streams in HDR. So its much too bright. If I turn off HDR in win 11 manually everything looks great.

Is there a possibility to let the client (Lenovo M7) turn off the hdr on the host pc when I start a game stream and turn it on again when the stream stops.

**Comment by cgutman** [comment]
GeForce Experience cannot control OS HDR state, so Moonlight can't either. However, you can use software like https://github.com/lyckantropen/moonlight_hdr_launcher to do so.

**Comment by Maz111111** [comment]
So would there be a possibility to send the shortcut "win+alt+b" after the stream is enabled?
This toggles HDR on / off in win 11
I'm just looking for a way to turn off HDR from client
The andromedafix seems only to force hdr on

**Comment by cgutman** [comment]
The problem is that we can't determine if HDR is actually enabled before we do that, so we could be turning it off.

You should be able to enable the "capture system keyboard shortcuts" option in Moonlight and then press Win+Alt+B yourself. You may need to disable the Game Bar on your client or it will intercept that keypress before it reaches Moonlight.

**Comment by charnet3d** [comment]
I use a .bat script like this to enable or disable HDR:

```
@echo off
SETLOCAL EnableDelayedExpansion

set SUNSHINE_CLIENT_WIDTH=%1
set SUNSHINE_CLIENT_HEIGHT=%2
set SUNSHINE_CLIENT_FPS=%3
set SUNSHINE_CLIENT_HDR=%4

timeout 4
D:\Programs\MonitorProfileSwitcher\MonitorSwitcher.exe -load:%APPDATA%\MonitorSwitcher\Profiles\GameStream%SUNSHINE_CLIENT_HEIGHT%p%SUNSHINE_CLIENT_FPS%.xml

timeout 1

if %SUNSHINE_CLIENT_HDR%==true (
	D:\Programs\HDRTray\HDRCmd.exe on
)
if %SUNSHINE_CLIENT_HDR%==false (
	D:\Programs\HDRTray\HDRCmd.exe off
)

exit /b 0
```


Then in sunshine I set it to call this script before stream start in "General->Command Preparations->Do Command":

`cmd.exe /c start /min cmd.exe /c D:\Programs\Sunshine_display_game.bat %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR%`

The reason I call it this way (a cmd calling a cmd calling my script) is because first I want the script to run minimized, and I don't want moonlight to wait for it to finish and then it starts the stream (I feel sometimes it messes up the monitor layout). So sunshine starts the script minimized, the stream starts and 4s later the commands are executed correctly.

You can see I also use MonitorSwitcher.exe, this way I can use a virtual monitor ([Virtual Display Driver](https://github.com/itsmikethetech/Virtual-Display-Driver)) to stream with, avoiding the need to keep my actual monitors on during the stream. MonitorSwitcher enables you to save profiles for monitor layouts, resolutions and refresh rates, so you can load them at any point and they work as intended. I have a few GameStreamXXXXYYY profiles already saved up: XXXX being the resolution and YYY being the refresh I want. The script gets these from sunshine and it loads the correct layout for that device. For example I play sometimes on a 1440p90hz phone and I have a profile GameStream1440p90 that gets loaded on these sessions. Then another for 2160p144 and any other resolutions you may need.

Finally I have a 2nd script that is run when the stream ends to reset the monitor layout again to my physical monitor (or I will be "locked out" of the PC and have to Win+P multiple times to switch my physical monitors on again). I set the script in sunshine: "General->Command Preparations->Undo Command". And the script is something like this :

```
@echo off
SETLOCAL EnableDelayedExpansion

set SUNSHINE_CLIENT_WIDTH=%1
set SUNSHINE_CLIENT_HEIGHT=%2
set SUNSHINE_CLIENT_FPS=%3
set SUNSHINE_CLIENT_HDR=%4

D:\Programs\MonitorProfileSwitcher\MonitorSwitcher.exe -load:%APPDATA%\MonitorSwitcher\Profiles\MainOnly.xml

exit /b 0
```
