### ISSUE TITLE
Green line on bottom since upgrade to latest GFE, drivers or Win 11 22h2

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#885]
Not sure whats causing this, could be latest GFE upgrade, Nvidia driver or Win 11 22h2 or Moonlight 4.2.1 upgrade. There is a 1pixel green line on the bottom of the stream which was not there before:

![image](https://user-images.githubusercontent.com/6721083/198143805-52a899df-dc9a-4812-8bfd-89433f8cf396.png)

The issue seems on the client side not server, if you switch to software decode, there is no green line. Also when choosing H.264 there is also no green line, just H.265.

Client is Intel UHD630 with latest drivers 31.0.101.2114 Win 11 22h2 with Moonlight 4.2.1.

**Comment by cgutman** [comment]
What resolution are you streaming?

**Comment by makedir** [comment]
1440p, window mode.

**Comment by makedir** [comment]
Wait what caused this? Where and when was this introduced and why, and why just h265?

**Comment by cgutman** [comment]
It's been there since D3D11VA was introduced, but it's probably been visible since v4.2.0 which started to default to D3D11VA on compatible systems. Whether it will show or not depends on the GPU driver and streaming resolution, since it's basically blending with uninitialized memory (which generally is green). I can see it on my Intel system too at certain resolutions.

It happens with HEVC specifically because it requires more alignment padding than H.264 (128 vs 16). 1440 is evenly divisible by 16, so there is no alignment padding, but it is not evenly divisible by 128.

Try this build and let me know if it fixes the issue for you: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/45195433/job/npq1u7thiv4ixu7r/artifacts

**Comment by makedir** [comment]
Yes that fixed it thank you. Im confused a little bit though, what do you mean with different alignments for 264 and 265? Arent the screen sizes always the same pixel size for both 2560 x 1440 pixels in this case? why is/was there one green line more? so it was 2560 x 1441 pixels ? Did you fix/change change something on the true resolution size for what the client sees? That would be important to have not blurred image if you resize I would assume.

**Comment by cgutman** [comment]
The screen size is the same, but DXVA requires different surface alignment for H.264 and HEVC.

For H.264, the texture dimensions must be a multiple of 16. HEVC requires they be a multiple of 128. That means there is extra padding for HEVC when streaming at 1440p that isn't present when using H.264 (because 1440 is already a multiple of 16). To satisfy the DXVA HEVC alignment requirement, we allocate a texture that 2560x1536 which results in some extra padding at the bottom of the texture.

On the bottom edge of the screen, the shader can end up sampling from both video data and alignment padding (if padding is present). When it samples from the padding area, that will appear green.
