### ISSUE TITLE
moonlight becomes unresponsive every time it starts streaming

### ISSUE THREAD

**Issue by wayne0926** [moonlight-stream/moonlight-qt#888]
He freezes for a long time and also causes me to lose control of the volume etc.
![image](https://user-images.githubusercontent.com/63389859/198715348-c34beee9-6b22-4c55-82a1-0c12a487cb1c.png)
At the same time, I need to wait for a long time to start the moonlight main program
![捕获11](https://user-images.githubusercontent.com/63389859/198717203-8920ec6c-3e71-4e62-ade1-75ebb57d862f.JPG)

The version is `4.3.0`, both computers are this version

**Comment by cgutman** [comment]
Usually this issue is caused by some misbehaving input device that causes a long delay.

When Moonlight is not responding, can you right click Moonlight.exe on the Details tab and select "Create dump file"? If you upload that file somewhere and post a link here, I can look to see what device seems to be delaying it.
