### ISSUE TITLE
Host Gaming PC Requirements

### ISSUE THREAD

**Issue by Crudelis98** [moonlight-stream/moonlight-qt#947]
Hi, Im sorry in advance for posting here, it is quite urgent, according to wiki:
Host Gaming PC Requirements:
1.
2.
3. 720p or higher display (or headless display dongle) connected to the NVIDIA GPU
4.

Will USB adapter like USB ->HDMI do the trick?
Do I need to plug into this adapter dongle anyway?
Its server case, I have access to 2x USB only, any other ways to trick nvidia?
Thank you for your help!

**Comment by cgutman** [comment]
Your PC requires some sort of display output connected to the GPU to stream properly. You may be able to try creating a virtual display with https://github.com/roshkins/IddSampleDriver, but this is not guaranteed to work. You may also try [Sunshine](https://github.com/LizardByte/Sunshine) instead of GeForce Experience, since it uses a different method of display capture.
