### ISSUE TITLE
Moonlight app hangs on macOS when trying to quit streaming session under "Fullscreen" mode

### ISSUE THREAD

**Issue by rramnel** [moonlight-stream/moonlight-qt#973]
I have the issue where Moonlight app hangs when I close the streaming session if I use "Fullscreen" mode. This issue does not happen when I use "Windowed Borderless". 

When the app hangs, the only option I have is to press the power button twice where my MBP goes to the lockscreen. Then when I login again I see that the app has closed the streaming session. I am on the MBP M1 Pro running macOS Ventura

**Comment by airyimbin** [comment]
I am having the same issue consistenly. Moonlight hangs and shows a still frame of the last screen seen.
Also need to press power button and unlock.

MacBook Pro (2021) M1 Max

**Comment by Write** [comment]
Same issue. Requires to use Borderless mode, but the side effect is you can't have a real fullscreen mode where the screen actually goes under the notch.

**Comment by rramnel** [comment]
That's still ok for me as I am used to the "notch" already. I am now on macOS Sonoma (Public Beta), and the issue is still there.

**Comment by Write** [comment]
I'm on Sonoma too, What I'd want is the screen to be behind the notch ! Not under. But this is only working with "Fullscreen" option in Moonlight, not "Borderless" unfortunately. Borderless force the screen to adapt and go under the notch. And Fullscreen is not an option for me since I can't quit Moonlight as it will just freeze everything (weirdly) and I'll have to reboot the mac.

**Comment by rramnel** [comment]
I agree, for the issue where you are not able to quit Moonlight due to this bug, close the laptop completely and open it again. You don't need to do a full reboot.

**Comment by Write** [comment]
> I agree, for the issue where you are not able to quit Moonlight due to this bug, close the laptop completely and open it again. You don't need to do a full reboot.

Ok thanks !

**Comment by rramnel** [comment]
How can I get logs from the Moonlight app for macOS and post them here so that the devs can fix this issue? Tried Discord but no response

**Comment by Write** [comment]
> How can I get logs from the Moonlight app for macOS and post them here so that the devs can fix this issue? Tried Discord but no response

The dev can't do anything about this specific issue since it's a macOS issue. (?).
Not sure how to get the log anyway. Well, last time I needed help on my Android client they were fast enough to answer on Android channel, can't help you much, sorry.

**Comment by cgutman** [comment]
It seems clear that fullscreen is just broken on M1 Macs, between this bug and #999. It's unclear to me how you can even stream without encountering #999. Can you ever stream fullscreen without encountering one of these bugs or do you always hit it?

Is there a reason you want to use full-screen rather than the recommended borderless windowed mode? I'm tempted to just disable full-screen mode on Apple Silicon Macs. It's clearly not well tested on the SDL side.

**Comment by Write** [comment]
> It seems clear that fullscreen is just broken on M1 Macs, between this bug and #999. It's unclear to me how you can even stream without encountering #999. Can you ever stream fullscreen without encountering one of these bugs or do you always hit it?
> 
> 
> 
> Is there a reason you want to use full-screen rather than the recommended borderless windowed mode? I'm tempted to just disable full-screen mode on Apple Silicon Macs. It's clearly not well tested on the SDL side.


Border less windows mode won't go under the notch.

**Comment by rramnel** [comment]
I stream daily using Moonlight with Sunshine on my MBP M1 Pro and not once I have encountered #999 

I also use the fullscreen mode to make use of the complete screen (also the notch area). 

There is a workaround which works for me but I was hoping the bug can be fixed
1. Before quitting your moonlight session, swipe from right to left (similar to invoking the notification panel)
2. For some reason, it will show a black screen. Click once to get rid of the black screen
3. Then quit the streaming session as normal and it will quit without any issue

**Comment by Write** [comment]
> I stream daily using Moonlight with Sunshine on my MBP M1 Pro and not once I have encountered #999
> 
> I also use the fullscreen mode to make use of the complete screen (also the notch area).
> 
> There is a workaround which works for me but I was hoping the bug can be fixed
> 
>     1. Before quitting your moonlight session, swipe from right to left (similar to invoking the notification panel)
> 
>     2. For some reason, it will show a black screen. Click once to get rid of the black screen
> 
>     3. Then quit the streaming session as normal and it will quit without any issue

Yup same, can't remember having #999 myself, M1 Max, 32 Gb

**Comment by cgutman** [comment]
Ok, since I don't have an M1 Mac, I'd like you to try a couple things to help me identify a possible workaround.

First, try forcing Moonlight to run using Rosetta and see if the hang still happens. I don't expect this to work, but I need to be sure.

Second, try pressing Ctrl+Alt+Shift+X to toggle out of fullscreen mode before quitting and see if it still hangs on quit (or when exiting fullscreen).

If it doesn't hang or crash when using Ctrl+Alt+Shift+X, try to press the combo a few times while streaming to toggle in and out of fullscreen to see if a hang or crash (or other bug) is ever triggered.

**Comment by rramnel** [comment]
Just tried both options
1. forcing Moonlight to run using Rosetta - no change, the app hangs when you quit
2. Pressing Ctrl+Alt+Shift+X gives the same output like pressing Ctrl+Alt+Shift+Q - it hangs and can't quit the app

The only workaround so far that works for me is the one I mentioned earlier (swiping from right to left, dismissing the black screen and then quitting the app)

**Comment by rramnel** [comment]
Yes correct, that as well

**Comment by cgutman** [comment]
Ok, thanks for testing. I'd like to try a few more things.

First, can you try the latest nightly build just to confirm it's still impacted: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/47974506/job/6t4xjp5clp02iqb7/artifacts

Can you also attach the Moonlight logs from your `/tmp` folder on your Mac after the hang happens? If you're streaming remotely, you may want to remove any IP addresses from the log file before uploading.

Finally, if it's possible, I'd like you to try to get a spindump of Moonlight while it's hung. You can try attaching a second monitor, so you can hopefully still interact with the machine while it's hung on the other display. If that works, open Activity Monitor, click on the gear icon, then Run Spindump. Depending on how large it is, you can attach it directly or upload it to Google Drive or something and send me a link.

If you're not able to use a separate monitor to get the spindump while Moonlight is hung, you can try [enabling SSH](https://support.apple.com/guide/mac-help/allow-a-remote-computer-to-access-your-mac-mchlp1066/13.0/mac/13.0) then using ssh from another machine to remote in and run `sudo spindump -file ~/Desktop/spindump.txt` to capture a spindump to your desktop.

**Comment by rramnel** [comment]
Sure, more than happy to help. Just tried the nightly build. The issue still exists. 

Attached is the Moonlight Log after the hang happens. I have removed all IP addresses from it. 
[Moonlight-1694089539.log](https://github.com/moonlight-stream/moonlight-qt/files/12549011/Moonlight-1694089539.log)

I am not able to get a spindump as when connecting a second display interacting with it is not possible. Maybe @Write can you help if you are able to get a spindump?

**Comment by cgutman** [comment]
Okay, a couple more things to try:
- Disable V-Sync in Moonlight
- Set the video decoder to "force software decoding"

See if either of those settings make any difference.

**Comment by rramnel** [comment]
Looks like "force hardware decoding" is causing the issue. Tried the following:
1. Disable V-Sync, force software decoding - no issue 
2. Disable V-Sync, force hardware decoding - issue still there
3. Enable V-Sync, force software decoding - no issue 

But moonlight streaming performance is much worse when forcing software decoding compared to hardware decoding

**Comment by cgutman** [comment]
Ok, that's helpful. It at least narrows down the cause to the VideoToolbox video renderer.

Please give these builds a try and let me know if any of them fix the bug or change any behavior of the bug:
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/47993429/job/nqg7s3d6ig3i2fmo/artifacts
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/47993456/job/lhr644fujyjlilah/artifacts
- https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/47993482/job/lji18vv3ahjx1vrl/artifacts

**Comment by rramnel** [comment]
Thanks, Just tried all the versions
- 0.0.0.2154 - issue still there
- 0.0.0.2155 - issue still there
- 0.0.0.2156 - issue still there

**Comment by cgutman** [comment]
OK, I went a different direction and decided to use the same rendering code as the software decoder uses on Apple Silicon. This is less efficient because it requires more CPU-GPU data transfers, but the performance penalty of this is hopefully very small since Apple Silicon is a unified memory architecture (and it still takes advantage of the hardware decoder).

We still have to use the old renderer for HDR streaming because it's the only path on macOS that supports rendering 10-bit video, so you will still see the bug if you enable HDR. Once I have time to write a Metal renderer, that should fully replace the existing renderer and avoid having to fall back when streaming HDR content.

The old approach also had noticably higher rendering latency, despite the numbers in the performance overlay being very low. This newer approach has slighly higher (and more accurate) latency numbers in the overlay, but in reality feels lower latency to me (though I didn't test for very long).

Let me know how this build performs for you (and of course if the bug is still there): https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/47995155/job/sc1gktlskvxe5gaq/artifacts

**Comment by rramnel** [comment]
Thanks will test it out tomorrow as I get the following message when I try to download the artifact - "Artifacts download limit (1024 MB/day) exceeded"

**Comment by cgutman** [comment]
Oh, that's a strange error. Here is a build if you want to try earlier: https://drive.google.com/file/d/1R8HH7AcutzR8lIGSGJmM3fX5npmZq_gq/view?usp=sharing

**Comment by rramnel** [comment]
Thanks. Build 0.0.0.2159 seems to work now 😀 The app does not quit immediately though. When I press Ctrl+Alt+Shift+Q it takes around 4-5 seconds before the app quits. But definitely better than before where I couldn't quit the app at all.

**Comment by cgutman** [comment]
Do you mean it takes 4-5 seconds to return to the app grid after you exit the session or do you mean it takes that long for the Moonlight icon to disappear in the dock when you exit Moonlight itself? I'm aware of the latter bug.

If you're referring to a 4-5 second delay to quit the stream and return to the app selection page, does that only occur in fullscreen or also windowed and borderless windowed modes?

Is the video latency and performance good with the new build? Better or worse than before or no change?

**Comment by rramnel** [comment]
It takes 4-5 seconds for the app to quit and return back to the main macOS screen. For some reason now, it's gone after I switched to borderless windowed mode and then back. 

I don't see any significant changes with regards to performance. If I am not mistaken I do see better decoding times compared to the stable version. 

And I also noticed that the new version seems to use more battery. Usually macOS doesn't report Moonlight app as using significant energy in the battery meter, but with this version it does.
